### ISSUE TITLE
TemporalInterpreter temporalRangeParser.parse exceptions 

### ISSUE THREAD

**Issue by adam-collins** [gbif/pipelines#1011]
Running the TemporalInterpreter::interpretTemporal is throwing new exceptions for invalid eventDate ranges. e.g.
-  `1922-11-02T21:01/1922-11-02T01:01`  throws `Invalid range: (1922-11-02T21:01, 1922-11-02T01:01)`
- `1918-07-21T20:01:00/1918-07-21`, throws `Unable to obtain LocalDateTime from TemporalAccessor: 1918-07-21 of type java.time.LocalDate`

I think the old behaviour was to set the parsed eventDate to the first part of the invalid date range, e.g. `1921-12-15T21:31:00/1921-12-15T01:31:00` sets the eventDate to `1921-12-16` [example](https://biocache.ala.org.au/occurrences/a8d6e45f-872c-4d45-8d68-7e6249b10f9b) and [code](https://github.com/gbif/pipelines/blob/dev/livingatlas/pipelines/src/main/java/au/org/ala/pipelines/transforms/ALATemporalTransform.java#L87)

**Comment by adam-collins** [comment]
Currently testing with branch https://github.com/gbif/pipelines/tree/ala-2024

**Comment by MattBlissett** [comment]
I've handled all the exceptions found in GBIF's data, and wrapped the parser to catch any possible other exceptions and return a general INTERPRETATION_ERROR issue.

**Comment by adam-collins** [comment]
I double checked. The parser is throwing exceptions for some data.

1. The first example I gave is calling `new IsoDateInterval(from, to)` without testing `from < to` and without catching the [exception thrown](https://github.com/gbif/gbif-api/blob/f9ac80fb9cca1cc34544d5127d3a3e9c07f9d0b4/src/main/java/org/gbif/api/util/IsoDateInterval.java#L71).

Can be reproduced with:
```
    String date = "1922-11-02T21:01/1922-11-02T01:01";
    Map<String, String> map = new HashMap<>();
    map.put(DwcTerm.eventDate.qualifiedName(), date);
    map.put(DwcTerm.year.qualifiedName(), "1922");
    map.put(DwcTerm.month.qualifiedName(), "11");
    map.put(DwcTerm.day.qualifiedName(), "2");
    ExtendedRecord er = ExtendedRecord.newBuilder().setId("1").setCoreTerms(map).build();

    TemporalRecord tr = TemporalRecord.newBuilder().setId("1").build();

    TemporalInterpreter temporalInterpreter =
            TemporalInterpreter.builder().explicitRangeEnd(false).create();

    temporalInterpreter.interpretTemporal(er, tr);
```

2. The second example exception is due to LocalDateTime attempting to parse only a date, without a time. This is the [point of failure](https://github.com/gbif/gbif-api/blob/f9ac80fb9cca1cc34544d5127d3a3e9c07f9d0b4/src/main/java/org/gbif/api/util/IsoDateInterval.java#L91)

Reproduce with:
```
    String date = "1922-11-02T21:01/1922-11-02";
    Map<String, String> map = new HashMap<>();
    map.put(DwcTerm.eventDate.qualifiedName(), date);
    ExtendedRecord er = ExtendedRecord.newBuilder().setId("1").setCoreTerms(map).build();

    TemporalRecord tr = TemporalRecord.newBuilder().setId("1").build();

    TemporalInterpreter temporalInterpreter =
            TemporalInterpreter.builder().explicitRangeEnd(false).create();

    temporalInterpreter.interpretTemporal(er, tr);
```

**Comment by adam-collins** [comment]
It appears I misunderstood a reply. Inclusion of a link to a pull request or commit, or a pull request or commit referencing this issue would have helped me.
