### ISSUE TITLE
K8s: Revise the install-workflow.sh and run-workflow-schema-migration.sh occurrence scripts

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#1015]
The install-workflow.sh and run-workflow-schema-migration.sh scripts are used for pipelines reinterpretation scripts and Jenkins projects.

**Comment by marcos-lg** [comment]
I created this script to run the wfs in airflow: https://github.com/gbif/occurrence/blob/feature/stackable-hadoop-3-test/occurrence-download/install-workflow-airflow.sh

It's pretty simple since we can't change the params of the dag but we can add more options if we need them.
