### ISSUE TITLE
K8s: Spark jobs logging/history

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#1018]
Some logs are available through Airflow, but not all. We need to have comprehensive logs or a detailed history, perhaps using ELK or another common approach for K8s.

**Comment by muttcg** [comment]
There is a conflict between yunikorn and running a sidecar pod for logging. When the template uses the yunikorn driver and executor pod override to add _**yunikorn.apache.org/task-groups**_ and a logging section, the job gets stuck in _**pending**_ mode. Removing the pod override or the logging part resolves this issue.

**Comment by zaultooz** [comment]
The conflict is resolved in PR: https://github.com/gbif/gbif-airflow-dags/pull/9
