### ISSUE TITLE
isSequenced filter should take extensions into account

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/pipelines#1032]
I think the `isSequenced` filter currently only looks at the `associatedSequences` field.
As mentioned here https://github.com/gbif/pipelines/issues/515#issuecomment-952021548 it should also include occurrences that has any of these extensions:

1. DNA derived data
2. GGBN/amplification
3. GGBN/cloning
4. GGBN/gelimage

**Comment by MortenHofft** [comment]
I believe we sometimes have extensions with absolutely no data in them. I would think those should be excluded.

**Comment by muttcg** [comment]
Deployed to PROD. Reinterpreting related datasets
