### ISSUE TITLE
K8s: Docker images can be unavailable 

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#1054]
`stream logs failed container "vector" in pod "hdfs-view-95db4db8-f762-11e1-a439-00145eb45e9a-148-exec-10" is waiting to start: trying and failing to pull image for gbif-develop/hdfs-view-95db4db8-f762-11e1-a439-00145eb45e9a-148-exec-10 (vector)`

3rd-party image registry is throwing HTTP 502, so jobs get errors or can't be start

We can use the GBIF repository as cache and middleman for the image registry

**Comment by zaultooz** [comment]
Nexus has been configured with a proxy repository to the stackable nexus and all charts that uses the stackable image had a "repo" field added under image (Except spark which uses sparkImage) to point to the proxy repository. 

The proxy repository cache the images indefinitely so we should see problems with Stackable nexus potentially blocking us.
