### ISSUE TITLE
Minimum support of GBIF API v1

### ISSUE THREAD

**Issue by fmendezh** [gbif/pipelines#118]
This aims to have an initial implementation of the GBIF [v1/occurrence/search](https://www.gbif.org/developer/occurrence) API backed by ElasticSearch. 
Initially it should support filters and facets by:
 -  country
 -  basisOfRecord
 -  datasetKey
 -  all taxa keys

This can be implemented as replacement for  https://github.com/gbif/occurrence/tree/master/occurrence-search or else can be implemented as new ws (dropwizard?) project

Restrictions to be taken into consideration:
  - The GBIF API v1  allows multi select faceting ([https://www.gbif.org/developer/occurrence#p_facetMultiselect](https://www.gbif.org/developer/occurrence#p_facetMultiselect) and [https://lucene.apache.org/solr/guide/6_6/faceting.html#Faceting-TaggingandExcludingFilter](https://lucene.apache.org/solr/guide/6_6/faceting.html#Faceting-TaggingandExcludingFilters) ), in ES this could be implemented by using a combination of aggregations and filters since the facet API has been deprecated.
  -  facetLimit and facetOffset can be ignored

**Comment by asturcon** [comment]
So far, supported queries by all fields but dates, full text search and facets. It'll be implemented in different tasks.
