### ISSUE TITLE
Create a Hive table to query raw occurrence Avro data

### ISSUE THREAD

**Issue by fmendezh** [gbif/pipelines#14]

**Comment by asturcon** [comment]
@aalbatross can you please post here the query you have used to create the table? Thanks!

**Comment by aalbatross** [comment]
Please commit this 
CREATE TABLE raw_avro
ROW FORMAT SERDE
'org.apache.hadoop.hive.serde2.avro.AvroSerDe'
STORED as INPUTFORMAT
'org.apache.hadoop.hive.ql.io.avro.AvroContainerInputFormat'
OUTPUTFORMAT
'org.apache.hadoop.hive.ql.io.avro.AvroContainerOutputFormat'
TBLPROPERTIES (
'avro.schema.literal'='{
  "name": "ExtendedRecord",
  "namespace": "org.gbif.pipelines.io.avro",
  "doc": "A container for an extended DwC record (core plus extension data for a single record)",
  "type": "record",
  "fields": [
    {"name": "id", "type": "string", "doc": "The record id"},
    {"name": "coreTerms", "doc": "The core record terms", "default": {}, "type": {
      "type": "map", "values": "string"}
    },
    {"name": "extensions", "doc": "The extensions records", "default": {}, "type": {
      "type": "map", "values": {
        "type": "array", "doc": "The extension records", "default": [], "items": {
          "type": "map", "doc": "The extension record terms", "default": {}, "values": ["null", "string"]
        }
        }
      }
    }
  ]
}
');
