### ISSUE TITLE
Enable flag to skip creating index in ES

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#143]
It is necessary to be able to load multiple DwC-A into an ES index using the standalone pipeline.
Currently on each invocation it recreates the index. 

Suggest adding a flag called `createIndex` or similar that the user has to explicitly set to create the index. It would be safer that it defaults to not recreating to avoid deleting existing data.

**Comment by muttcg** [comment]
The current behaviour is:
1) The existing index will be used for indexing
2) If it doesn't exist, will be created before indexing
