### ISSUE TITLE
Comments about using the ES index

### ISSUE THREAD

**Issue by MortenHofft** [gbif/pipelines#146]
Just a place for me to log my small suggestion/issues about using the index.

* [ ] the index says `coordinatePoints` yet there are only one point. it used to be singular.

**Comment by MattBlissett** [comment]
https://en.oxforddictionaries.com/definition/coordinate

I think the word should be `coordinates`, since it is composed of a latitude coordinate and a longitude coordinate. Adding "points" is a [tautology](https://en.oxforddictionaries.com/definition/tautology).

**Comment by timrobertson100** [comment]
Suggest `coordinatePoints` become `coordinates` (plural because it comprises of a latitude coordinate and a longitude coordinate).
