### ISSUE TITLE
GBIF IDs missing in index

### ISSUE THREAD

**Issue by MortenHofft** [gbif/pipelines#150]
The existing GBIF IDs aren't in the new index. 
in http://api.gbif.org/v1/occurrence/search they are called key

**Comment by timrobertson100** [comment]
We have not yet decided upon a public identifier strategy. It is not for sure that running integer IDs will be used, perhaps replaced with e.g. datasetKey/occurrenceID, IGSNs, some other format selected for  [handle-based](https://www.dona.net/handle-system) use.

**Comment by timrobertson100** [comment]
While we maintain backwards compatibility with v1 we decided to add the GBIF running integer IDs.
