### ISSUE TITLE
Images not showing in www-es

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#164]
In testing we tried dataset `76dd8f0d-2daa-4a69-9fcd-55e04230334a` and www-solr got images, but not www-es.

**Comment by timrobertson100** [comment]
The ES records have (e.g.):

````
"multimediaItems": [
{
"format": "image/jpeg",
"identifier": "https://api.idigbio.org/v2/media/323e4ef320cd92b7e1ac608f7d8222f2",
"creator": "Jose Padial",
"description": "Photo taken in 2013",
"rightsHolder": "CC0",
"title": "AMBYSTOMA MACULATUM"
},
```

**Comment by muttcg** [comment]
Fixed -> https://github.com/gbif/pipelines/commit/00b6bd60f062285350eddee522317ec6c09f33db

**Comment by muttcg** [comment]
Occurrence has images:
https://www-es.gbif-dev.org/occurrence/64449
https://www-solr.gbif-dev.org/occurrence/64449

multimedia Items look ok
http://c3n1.gbif.org:9200/occurrence/_search?q=gbifId:64449

But for gallery tab is empty -> https://www-es.gbif-dev.org/occurrence/gallery

**Comment by fmendezh** [comment]
Fixed here https://github.com/gbif/occurrence/commit/0e09565c1dbda67d2d5783004d5d0ccba61d2ca4
Some enum parameters were being parsed in the wrong way
