### ISSUE TITLE
spark.default.parallelism should never be 1 on a cluster

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#167]
In `dev` testing I notice distributed jobs such as `VerbatimToInterpretedPipeline` launching on YARN with `spark.default.parallelism=1` which makes little sense to launch on the cluster.

I suggest clamping at a minimum of 10 and maximum of 1000.

**Comment by muttcg** [comment]
Fixed -> https://github.com/gbif/crawler/commit/fdd7aa5ed50372bdb54d9e86196e7fd95572c3d8
