### ISSUE TITLE
Date in multimedia object is not being interpreted

### ISSUE THREAD

**Issue by fmendezh** [gbif/pipelines#168]
Comparing Solr vs ElasticSearch APIs, the multimedia date is not interpreteded:
Solr:
"media": [
    {
      "type": "StillImage",
      "format": "image/jpeg",
      "identifier": "https://static.inaturalist.org/photos/30441820/original.jpeg?1547996524",
      "references": "https://www.inaturalist.org/photos/30441820",
      "created": "2020-01-12T18:33:58.000+0000",
      "creator": "big-simonchan",
      "publisher": "iNaturalist",
      "license": "http://creativecommons.org/licenses/by-nc/4.0/",
      "rightsHolder": "big-simonchan"
    },
"issues": [
    "COORDINATE_ROUNDED",
    "GEODETIC_DATUM_ASSUMED_WGS84",
    "TAXON_MATCH_HIGHERRANK",
    "MULTIMEDIA_DATE_INVALID"
  ]

ES: 
"media": [
    {
      "type": "StillImage",
      "format": "image/jpeg",
      "identifier": "https://static.inaturalist.org/photos/30441820/original.jpeg?1547996524",
      "references": "https://www.inaturalist.org/photos/30441820",
      "creator": "big-simonchan",
      "publisher": "iNaturalist",
      "license": "http://creativecommons.org/licenses/by-nc/4.0/",
      "rightsHolder": "big-simonchan"
    },
  "issues": [
    "COORDINATE_ROUNDED",
    "GEODETIC_DATUM_ASSUMED_WGS84",
    "TAXON_MATCH_HIGHERRANK"
  ]

**Comment by muttcg** [comment]
The issue is added, but the date will be empty, cause it is the future date -> 2020-01-12T18:33:58.000+0000
