### ISSUE TITLE
Missing issue/validation RECORDED_DATE_MISMATCH and invalid interpreted eventDate

### ISSUE THREAD

**Issue by fmendezh** [gbif/pipelines#170]
In the old/current pipelin, a record containing the value "http://rs.tdwg.org/dwc/terms/eventDate": "2000" is interpreted into 
"year": 2000,
  "eventDate": "2000-01-01T00:00:00",
  "issues": [
    "RECORDED_DATE_MISMATCH"
  ],

In pipelines, the same record is interpreted into:
"year": 2000,
  "eventDate": "2000-05-28T12:39:19",
which seems wrong (No issues identified, which can be fine)

Record example in dev: http://api-solr.gbif-dev.org/v1/occurrence/66420/verbatim

**Comment by muttcg** [comment]
API appends all dates in response, in ES is OK
RECORDED_DATE_MISMATCH -> should not be in issues, because, year == eventDate, we compare temporal dates

**Comment by fmendezh** [comment]
https://github.com/gbif/occurrence/commit/0e09565c1dbda67d2d5783004d5d0ccba61d2ca4 fixed the wrong interpretation of date with only years
