### ISSUE TITLE
Multimedia license is not interpreted

### ISSUE THREAD

**Issue by fmendezh** [gbif/pipelines#173]
The MultimediaInterpreter does not seem to be interpreting the media license, in the Solr/current APi we get:
{
      "type": "StillImage",
      "format": "image/jpeg",
      "identifier": "https://api.idigbio.org/v2/media/7f0f98ce855bfa47732497408532c48e",
      "title": "EURYCEA LONGICAUDA LONGICAUDA",
      "description": "Photo taken in 2013",
      "creator": "Jose Padial",
      "license": "http://creativecommons.org/publicdomain/zero/1.0/"
    }

vs in Elasticsearch:

{
      "type": "StillImage",
      "format": "image/jpeg",
      "identifier": "https://api.idigbio.org/v2/media/088d7feab85194bec8b4725ae1362468",
      "title": "EURYCEA LONGICAUDA LONGICAUDA",
      "description": "Photo taken in 2013",
      "creator": "Jose Padial",
      "rightsHolder": "CC0"
    },

Occurrence record example: https://api-es.gbif-dev.org/v1/occurrence/64449

**Comment by muttcg** [comment]
https://api-es.gbif-dev.org/v1/occurrence/64449 -> "license": "CC0_1_0"
For root license, we provide ENUM and API resolves ENUM -> http://c3n1.gbif.org:9200/occurrence/_search?q=gbifId:64449
API doesn't resolve multimedia ENUM

**Comment by fmendezh** [comment]
The enum value stored in Es is now transformed building the response
https://github.com/gbif/occurrence/commit/b758d6b8920b1adb28cfcad7e886dd1ab9db5b8b

**Comment by muttcg** [comment]
http://api-es.gbif-dev.org/v1/occurrence/5302801 -> http://creativecommons.org/licenses/by-nc/4.0/legalcode
http://api-solr.gbif-dev.org/v1/occurrence/5302801 -> http://creativecommons.org/licenses/by-nc/4.0/
Multimedia records have the same license, but API a bit different links (path level)
