### ISSUE TITLE
regarding process endpoint

### ISSUE THREAD

**Issue by MortenHofft** [gbif/pipelines#176]
A few comments on the new endpoint
https://api.gbif-dev.org/v1/pipelines/process/running

example response below.

* **typo** this looks like a typo: ` "name": "dwcaToVerbatm",` should say `verbatim`?
* **missing** The only way to get datasetKey and attempt is to parse crawlId. Doesn't it seem reasonable to include datasetKey and attempt in the response since it is considered essential in the monitoring? (we can of course parse it, but it seems a bit silly?
* **missing** it would be nice to include datasetTitle. Else the client have to do it and then is performance wise a bad idea.
* **naming** `"step": {"present": true}` - wouldn't `running` be more informative than `present` (@muttcg informed me that was what it meant). I at least wasn't sure what it meant.
* **Structure and naming** `error` and `successful`. I'm not sure how to read them. Does `"availability": false` mean that there wasn't an error? Can there be an error message when availability is false? Since the 2 objects are identical would it make sense to have a `status: {message: 'whatever', error: false}` instead?
* **format** We normally just have a single string in iso8601, why is this atomised. Is this something we imagine doing in the future for all dates? Also `startDateTime.chronology.calendarType:iso8601` if I read it correctly it states that the format is iso8601, but it is not is it? I thought iso8601 was `yyyy-mm-ddThh:mm:ss` like we normally represent dateTimes.
* **unnecessary nesting?** Why is `"present": true` nested in a `step` object? It is all a step. Can there be more in there? 
* **naming** Silly little thing and probably just preference: why `metricInfos` and not just `metrics`?
* **naming** Again this might well be my english: `chronology` and iso date formats. Is that a standard way to refer to that?

UPDATE: thinking about I realise I don't understand `availability: true` - how can it be succesful and still running (`present: true`)

```
[
  {
    "crawlId": "76dd8f0d-2daa-4a69-9fcd-55e04230334a_99",
    "pipelinesSteps": [
      {
        "name": "dwcaToVerbatm",
        "startDateTime": {
          "hour": 7,
          "minute": 24,
          "second": 34,
          "nano": 37000000,
          "dayOfYear": 99,
          "dayOfWeek": "TUESDAY",
          "month": "APRIL",
          "dayOfMonth": 9,
          "year": 2019,
          "monthValue": 4,
          "chronology": {
            "id": "ISO",
            "calendarType": "iso8601"
          }
        },
        "error": {
          "availability": false,
          "message": ""
        },
        "successful": {
          "availability": true,
          "message": "Next message has been sent - {\"datasetUuid\":\"76dd8f0d-2daa-4a69-9fcd-55e04230334a\",\"attempt\":99,\"interpretTypes\":[\"ALL\"],\"pipelineSteps\":[\"ALL\"],\"runner\":null}"
        },
        "step": {
          "present": true
        }
      }
    ],
    "metricInfos": [
      {
        "name": "extension.AudubonTransform.audubonRecordsCount",
        "value": "14"
      },
      {
        "name": "extension.MultimediaTransform.multimediaRecordsCount",
        "value": "14"
      },
      {
        "name": "core.TaxonomyTransform.taxonRecordsCount",
        "value": "14"
      },
      {
        "name": "specific.AustraliaSpatialTransform.australiaSpatialRecordsCount",
        "value": "14"
      },
      {
        "name": "core.LocationTransform.locationRecordsCount",
        "value": "14"
      },
      {
        "name": "core.MetadataTransform.metadataRecordsCount",
        "value": "1"
      },
      {
        "name": "core.BasicTransform.basicRecordsCount",
        "value": "14"
      },
      {
        "name": "extension.MeasurementOrFactTransform.measurementOrFactRecordsCount",
        "value": "14"
      },
      {
        "name": "UniqueIdTransform.uniqueIdsCount",
        "value": "14"
      },
      {
        "name": "extension.ImageTransform.imageRecordsCount",
        "value": "14"
      }
    ]
  }
]
```

**Comment by MortenHofft** [comment]
Based on my understanding (which might be misguided) I guess I imagine something more like
```
[
  {
    "crawlId": "76dd8f0d-2daa-4a69-9fcd-55e04230334a_99",
    "datasetKey": "76dd8f0d-2daa-4a69-9fcd-55e04230334a",
    "attempt": "99",
    "steps": [
      {
        "name": "dwcaToVerbatm",
        "started": "2019-06-07T21:31:56.485+0000"
        "finished": "2019-06-07T21:31:56.691+0000",
        "state": "RUNNING | FAILED | COMPLETED",
        "message": "Next message has been sent etc"
      }
    ],
    "metrics": [
      {
        "name": "extension.AudubonTransform.audubonRecordsCount",
        "value": "14"
      },
      ...
    ]
  }
]
```

**Comment by muttcg** [comment]
I have updated API for dev -> https://api.gbif-dev.org/v1/pipelines/process/running?_=1560775608
Changed response structure:
1) **datasetTitle** will be added soon
2) Please igonre - **"step": { "present": true }** , some serialization "feature"
3) Added filed **runner** (can be STANDALONE or DISTRIBUTED)

**Comment by muttcg** [comment]
Updates:
1. Added **datasetTitle** 
2. Changed name from metricInfos -> **metrics**
2. Changed name from pipelineSteps -> **steps**
