### ISSUE TITLE
endointType sometime is null

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#201]
Log from dwca-to-avro:

`INFO  [07-10 21:48:46,248+0000] [pipelines_to_avro_from_dwca-4] f0d00d00-aa57-4209-abaf-be2aed9a71dd_261 org.gbif.crawler.pipelines.dwca.DwcaToAvroCallback: Message handler began - {"datasetUuid":"ca0d1f8f-4ba5-4187-82ec-ed8a66745b67","datasetType":"OCCURRENCE","source":"http://ipt.miza-ucv.org.ve:8080/ipt/archive.do?r=miza-iod","attempt":121,"validationReport":{"datasetKey":"ca0d1f8f-4ba5-4187-82ec-ed8a66745b67","occurrenceReport":{"checkedRecords":74699,"uniqueTriplets":74699,"allRecordsChecked":true,"recordsWithInvalidTriplets":0,"uniqueOccurrenceIds":74699,"recordsMissingOccurrenceId":0,"invalidationReason":null,"valid":true},"genericReport":null,"invalidationReason":null,"valid":true},"pipelineSteps":[],"endpointType":null}`

where -> **"endpointType":null**

**Comment by asturcon** [comment]
when this happened the latest version of the crawler.cli wasn't deployed
