### ISSUE TITLE
 delete_by_query deletes documents after indexing

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#202]
When dataset goes to a default index and the dataset size is big enough, the presented dataset has to be deleted before, we do delete_by_query, sometimes we got conflicts to avoid them we use conflicts=proceed, because indexing is faster than deletion, I found several workflows:
1) document.v1 -> document.v2 (marked as deleted) -> document.v3 (new version)
2) document.v1 -> document.v2 (new version) -> document.v3 (marked as deleted)

In the second case, we will get fewer records in the index, cause some will be deleted at the end.

To avoid the second case, I suggest to use the following schema:

**1)** Use **wait_for_completion=false** which returns taskId
Request:
```
POST occurrence/_delete_by_query?conflicts=proceed&scroll_size=5000&wait_for_completion=false
{"query":{"match":{"datasetKey":"85b1cfb6-f762-11e1-a439-00145eb45e9a"}}}
```
Response:
{ "task" : "DcNgkJn8SYmu9vN-jxEsfg:85198846" }

**2)** Query the task in the loop (every 1-3 sec) and check when it will be completed:

Request:
`GET _tasks/DcNgkJn8SYmu9vN-jxEsfg:85198846`

Response:
```
{
  "completed" : true,
  "task" : {
    "node" : "DcNgkJn8SYmu9vN-jxEsfg",
    "id" : 85198846,
    "type" : "transport",
    "action" : "indices:data/write/delete/byquery",
    "status" : {
      "total" : 621406,
      "updated" : 0,
      "created" : 0,
      "deleted" : 621406,
      "batches" : 125,
      "version_conflicts" : 0,
      "noops" : 0,
      "retries" : {
        "bulk" : 0,
        "search" : 0
      },
      "throttled_millis" : 0,
      "requests_per_second" : -1.0,
      "throttled_until_millis" : 0
    },
    "description" : "delete-by-query [occurrence]",
    "start_time_in_millis" : 1563543034986,
    "running_time_in_nanos" : 29765144360,
    "cancellable" : true,
    "headers" : { }
  },
  "response" : {
    "took" : 29764,
    "timed_out" : false,
    "total" : 621406,
    "updated" : 0,
    "created" : 0,
    "deleted" : 621406,
    "batches" : 125,
    "version_conflicts" : 0,
    "noops" : 0,
    "retries" : {
      "bulk" : 0,
      "search" : 0
    },
    "throttled" : "0s",
    "throttled_millis" : 0,
    "requests_per_second" : -1.0,
    "throttled_until" : "0s",
    "throttled_until_millis" : 0,
    "failures" : [ ]
  }
}
```
**3)** Start pipeline indexing process

**Comment by asturcon** [comment]
done in commit https://github.com/gbif/pipelines/commit/6e77e9a8ccd09c6653439a9dca453dfc9c6a2416
