### ISSUE TITLE
Mismatch in the datasetId between the logs and the message

### ISSUE THREAD

**Issue by asturcon** [gbif/pipelines#204]
The logs are showing `d34ed8a4-d3cb-473c-a11c-79c5fec4d649_230` but the message received is for `a2807e3c-9296-4ede-9ac2-b9a361a46116` and attempt `104`:

`
INFO  [07-25 07:57:17,762+0000] [pipelines_indexing_distributed-7] d34ed8a4-d3cb-473c-a11c-79c5fec4d649_230 org.gbif.crawler.pipelines.indexing.IndexingCallback: Message handler began - {"datasetUuid":"a2807e3c-9296-4ede-9ac2-b9a361a46116","attempt":104,"pipelineSteps":["INTERPRETED_TO_INDEX","DWCA_TO_VERBATIM","VERBATIM_TO_INTERPRETED"],"numberOfRecords":4563,"runner":"DISTRIBUTED","repeatAttempt":false}
`

**Comment by asturcon** [comment]
Another case

`
INFO  [07-18 09:48:22,532+0000] [pipelines_to_avro_from_dwca-3] 97ce9818-7028-42a0-9743-ccb5897dec1f_16 org.gbif.crawler.pipelines.dwca.DwcaToAvroCallback: Message handler began - {"datasetUuid":"01792e96-4711-4c33-936b-4a1e7b94e6bb","datasetType":"OCCURRENCE","source":"http://bim-mirror.aseanbiodiversity.org:8080/ipt/archive.do?r=asean_fish_occurrences_literature","attempt":3,"validationReport":{"datasetKey":"01792e96-4711-4c33-936b-4a1e7b94e6bb","occurrenceReport":{"checkedRecords":2029,"uniqueTriplets":0,"allRecordsChecked":true,"recordsWithInvalidTriplets":2029,"uniqueOccurrenceIds":2029,"recordsMissingOccurrenceId":0,"invalidationReason":null,"valid":true},"genericReport":null,"invalidationReason":null,"valid":true},"pipelineSteps":[],"endpointType":"DWC_ARCHIVE"}
`

**Comment by muttcg** [comment]
Fixed in -> https://github.com/gbif/crawler/commit/188079704d11e67ad76b2e44148761ce1954ed4b
