### ISSUE TITLE
Improve classification matching

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#215]
In some cases, the classification matching is applying incorrect logic to clean names before sending them to the lookup service. 

Ideally, all logic regarding cleaning should happen server-side (CC @mdoering). In the absence of that, we should improve the code that exists in pipelines.

The following illustrates the issue:
```
    // Acacia acinacea s.l. sensu Maslin (1996)
    System.out.println(TaxonParsers.interpretScientificName(
        SpeciesMatchRequest.builder()
            .withScientificName("Acacia acinacea s.l.")
            .withScientificNameAuthorship("sensu Maslin (1996)")
            .build()));
```

This results in `Acacia acinacea s.l. sensu Maslin (1996)` which is a badly formatted name that the [lookup service will return as _Acacia_](http://api.gbif.org/v1/species/match2?name=Acacia%20acinacea%20s.l.%20sensu%20Maslin%20(1996)).

The root cause of this is the method in `TaxonParsers` which applies this logic:
```
  private static String fromScientificName(String scientificName, String authorship) {
    boolean containsAuthorship =
      scientificName != null
            && !Strings.isNullOrEmpty(authorship)
            && !scientificName.toLowerCase().contains(authorship.toLowerCase());

    return containsAuthorship ? scientificName + " " + authorship : scientificName;
  }
```

I see similar cases with scientific names ending in s. s. 

If the scientific name is sent without authorship (i.e. `Acacia acinacea s.l.`) the lookup service [correctly returns `Acacia acinacea Lindl.`](http://api.gbif.org/v1/species/match2?name=Acacia%20acinacea%20s.l.)

@mdoering - [in the absence of the service taking authorship as a parameter](https://github.com/gbif/checklistbank/blob/master/checklistbank-nub-ws/src/main/java/org/gbif/checklistbank/ws/nub/NubResource.java#L48), can you suggest better logic for determining when to append the authorship and how it should be appended?

**Comment by timrobertson100** [comment]
I suspect simply removing [SS, s.s., senus stricto, s.l. etc] would be enough to improve the majority of cases.

**Comment by mdoering** [comment]
well, it should ideally be handled by the name parser gracefully. The name isn't really badly formatted. Just that I would regard sensu latu (s.l.) and sensu Maslin to be two concept references that not commonly appear both at the same time. I suspect that is irritating the name parser. Otherwise the logic to combine the authorship isnt that bad really. 

Removing `(s.|sensu)(l.|lat[.o]|s.|str.|stricto)$` from the name is an immediate remedy though that should not cause any trouble otherwise.

**Comment by marcos-lg** [comment]
Deployed to prod.
