### ISSUE TITLE
"null" as a string should be treated the same as a null value

### ISSUE THREAD

**Issue by MattBlissett** [gbif/pipelines#224]
I think it's a bit too pedantic of us to add issues where there are "null" strings, as in here:

https://www-es.gbif.org/occurrence/1121157704

**Comment by MattBlissett** [comment]
I'm willing to be persuaded, although I'd rather reserve the issues (especially ones we show as yellow) for things neither human nor machine could fix.

Similar `--` value: https://www-es.gbif.org/occurrence/92863842

**Comment by MattBlissett** [comment]
We go from about 350,000 issues with depth_not_numeric to over 23 million.

My concern is with giving too much useful feedback, since when it "looks stupid" ("but it says 'null'!") it leads to frustration and ignoring more serious problems.

**Comment by timrobertson100** [comment]
Fair point.  Where should we strip the "null" though? 

Should we strip it even at the DwC-A fragmentation step?

**Comment by MattBlissett** [comment]
I think production might not be adding issues in more cases than when it's null.

https://github.com/gbif/parsers/blob/master/src/test/java/org/gbif/common/parsers/geospatial/MeterRangeParserTest.java#L46 gives `success: false` for text (also for `null`).

https://github.com/gbif/occurrence/blob/master/occurrence-processor/src/main/java/org/gbif/occurrence/processor/interpreting/LocationInterpreter.java#L230 the current interpreter doesn't add issues if `not success`, so we're only adding the successful issues (depth in feet etc).

**Comment by MattBlissett** [comment]
Production is only keeping `null` in some cases (generally it's losing it for numeric and date fields).

I don't like us adding 50 million + issues like this. It dilutes the meaning of the current `WARNING` issue.

We should keep the current behaviour, and (later) add additional issues where the meaning is fairly unambiguous but the presentation isn't perfect.

**Comment by fmendezh** [comment]
I've added a method to get values that can contain "null" values https://github.com/gbif/pipelines/commit/5b7a9a4b2a3c6c37e7dbfcf6dc1cfcd5f1697a9c
