### ISSUE TITLE
Multimedia should only be parsed with the LicenseUriParser

### ISSUE THREAD

**Issue by MattBlissett** [gbif/pipelines#227]
https://github.com/gbif/pipelines/blob/72a2a8a6815b7bdb9c51d0708e34a8d6ab40fafe/sdks/core/src/main/java/org/gbif/pipelines/core/interpreters/extension/MultimediaInterpreter.java#L192-L195

I think just removing the LicenseParser (which is for the GBIF dataset licenses), leaving only the LicenseUriParser, will make the results consistent.

At the moment, we have `CC_BY_4_0` and `http://creativecommons.org/licenses/by-nc-sa/4.0/` in the same field, which is leading to an extra `/legalcode` when it's output.

(Multimedia intentionally parses a much wider range of licenses.)

This is low priority, it's so far only used for custom mediated-mv exports.

**Comment by fmendezh** [comment]
Dataset license parser removed, only LicenseUriParser is used in all multimedia extensions interpretations https://github.com/gbif/pipelines/commit/e5be8e8e66b8e69e2c761a0eddc0278427d20857
