### ISSUE TITLE
Coordinate reprojection incorrect

### ISSUE THREAD

**Issue by MattBlissett** [gbif/pipelines#229]
https://www.gbif.org/occurrence/657498948

The existing conversion is correct, according to https://epsg.io/transform#s_srs=5451&t_srs=4326&x=-83.7998200&y=9.7355000 (9.7340963°, -83.79788°) but Pipelines is giving something slightly different.

**Comment by asturcon** [comment]
Fixed in DEV after resetting the environment

**Comment by asturcon** [comment]
Occurrences reprocessed in PROD
