### ISSUE TITLE
Interpret a verbatim date field that is able to derive timestamps, partial dates and ranges, as specified here https://terms.tdwg.org/wiki/dwc:eventDate

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#23]
Please check how ES indexes date ranges: https://www.elastic.co/blog/numeric-and-date-ranges-in-elasticsearch-just-another-brick-in-the-wall

Current interpreter: https://github.com/gbif/occurrence/blob/master/occurrence-processor/src/main/java/org/gbif/occurrence/processor/interpreting/TemporalInterpreter.java

**Comment by cgendreau** [comment]
Background discussion about the handling of the timezone: https://github.com/gbif/gbif-api/issues/3
