### ISSUE TITLE
eBird publishingCountry not correct in HDFS table

### ISSUE THREAD

**Issue by MattBlissett** [gbif/pipelines#237]
```
SELECT count(*), publishingcountry
FROM prod_h.occurrence_pipeline_hdfs
WHERE datasetkey = '4fa7b334-ce0d-4e88-aaae-2e0c138d049e'
GROUP BY publishingcountry
ORDER BY publishingcountry;

561852542 | US
```

This is correct in ES https://www.gbif.org/occurrence/search?country=WF&dataset_key=4fa7b334-ce0d-4e88-aaae-2e0c138d049e&publishing_country=WF&advanced=1

It's required for correct annual analytics reports. Presumably, it's currently also incorrect in large downloads.

**Comment by muttcg** [comment]
Fixed in PROD table
