### ISSUE TITLE
Partial ingestion from orphan DIGIR XML archive

### ISSUE THREAD

**Issue by MattBlissett** [gbif/pipelines#238]
https://www.gbif.org/dataset/965169e4-f762-11e1-a439-00145eb45e9a

This archive appears to contain 32561 distinct catalog numbers, but we only see 13875 with pipelines.  

Pretending an archive of DiGIR responses is a BIOCASE_XML_ARCHIVE was a convenient hack, but if it's too difficult to handle it like that it could be reformed as a DWCA.  It's odd that we do get a third of the records.

**Comment by MattBlissett** [comment]
https://registry.gbif.org/dataset/82d9ff5c-f762-11e1-a439-00145eb45e9a

These are Antarctic datasets, so the difference is noticeable in the analytics (species counts) for FK and GS.

**Comment by muttcg** [comment]
We have bug in crawler, we are getting wrong finish message for ABCD crawler
Fixed by restarting to-avro step, 32,561 now -> 965169e4-f762-11e1-a439-00145eb45e9a 
Fixed by restarting to-avro step, 48437 now -> 82d9ff5c-f762-11e1-a439-00145eb45e9a

**Comment by ManonGros** [comment]
The same issues happened with these two datasets:
https://www.gbif.org/dataset/54f946aa-2ca9-4a51-9ee5-011219e0381e
https://www.gbif.org/dataset/85714c48-f762-11e1-a439-00145eb45e9a

**Comment by muttcg** [comment]
Should be fixed (Matt changed FS settings)
