### ISSUE TITLE
Cleaning up old crawls

### ISSUE THREAD

**Issue by MattBlissett** [gbif/pipelines#240]
```
/data/ingest/38b4c89f-584c-41bb-bd8f-cd1def33e92f/201
/data/ingest/38b4c89f-584c-41bb-bd8f-cd1def33e92f/202
/data/ingest/38b4c89f-584c-41bb-bd8f-cd1def33e92f/203
/data/ingest/38b4c89f-584c-41bb-bd8f-cd1def33e92f/204
/data/ingest/38b4c89f-584c-41bb-bd8f-cd1def33e92f/205
/data/ingest/38b4c89f-584c-41bb-bd8f-cd1def33e92f/206
/data/ingest/38b4c89f-584c-41bb-bd8f-cd1def33e92f/207
/data/ingest/38b4c89f-584c-41bb-bd8f-cd1def33e92f/208
/data/ingest/38b4c89f-584c-41bb-bd8f-cd1def33e92f/209
```

Old crawls remain, but this isn't sustainable -- the largest dataset's crawls are 2TB (as replicated) and 25,000 files.

Perhaps just keep the previous crawl? We can recreate from the DWCA if necessary, unless interpretation has changed.

**Comment by muttcg** [comment]
Added the method to delete attempts older than N-days (7 by default) in https://github.com/gbif/crawler/commit/2fcf902373d0d501749967cf3fcc9f81d84f5df4

**Comment by muttcg** [comment]
deployed to prod
