### ISSUE TITLE
According to GrSciColl

### ISSUE THREAD

**Issue by MortenHofft** [gbif/pipelines#242]
It would be nice to start linking GrSciColl to occurrences.

A first step could be to add `institutionId` and `collectionId` to the index as keywords.

A next step could be to add "According to GrSciColl" information. How to best model it in the index is not clear to me. I guess it is a matter of performance as well as how we see it scale to other reference catalogues - e.g. according to this taxonomy, this gazetteer, this person-identifier-scheme etc.
```
{
  "scientificName": "Puma Conclor",
  ...
  "grSciColl": {
    "institutionId": "1234-1234-1234-1234", // Or whatever id we choose to use as the primary
    "issues": ["CODE_ID_MISMATCH"] // Adding a grscicoll interpretation introduce new potential issues. Where do they belong. On the record as a whole or in the "accordingTo" block? For backbone we flag the occurrence as a whole
  }
}

// OR SIMPLY
{
  "scientificName": "Puma Conclor",
  ...
  "institutionId": "lsid:biocol.org/a123b", // as provided
  "institutionCode": "KM", // as provided
  "grSciCollId": "1234-1234-1234-1234", // e.g. linked based on the institution id
  "issues": ["COUNTRY_COORDINATE_MISMATCH", "GRSCICOLL_CODE_ID_MISMATCH"]
  }
}

// OR WITH OUR CURRENT PRACTICE OF CHANGING FIELDS
{
  "scientificName": "Puma Conclor",
  ...
  "institutionId": "1234-1234-1234-1234", // verbatim being say lsid:biocol.org/a123b
  "institutionCode": "CO", // verbatim being KM
  "issues": ["COUNTRY_COORDINATE_MISMATCH", "GRSCICOLL_CODE_ID_MISMATCH"]
  }
}
```

**Comment by MortenHofft** [comment]
**The cautious approach**
If we proceed with this we could start out with a cautious approach like described below:

If an identifier known to GrSciColl is provided, then use that to add `grSciColl.institutionId` and/or `grSciColl.collectionId`.

Else check the dataset machineTags to see if an explicit `code => GrSciColl_identifier` mapping has been added. (We will add machineTags with this information to datasets).

**Next**
Once we have done that, we know how much is left and we have the data in ES (which helps when building tools). We can then choose to
* Build tools to detect datasets without resolvable IDs
  * tag more datasets with their appropriate mapping
  * Contact the publishers to get IDs
* Evaluate if we can start matching based on codes alone.
* Add GrSciColl entities or codes when we see occurrences for which we have no appropriate mapping.

**Comment by qgroom** [comment]
Our InstitutionID is currently http://biocol.org/urn:lsid:biocol.org:col:15605 in our main GBIF dataset.
Can this just stay as it is under your suggestion?

**Comment by MortenHofft** [comment]
> Our InstitutionID is currently http://biocol.org/urn:lsid:biocol.org:col:15605 in our main GBIF dataset.
Can this just stay as it is under your suggestion?

Yes that is one of the dream identifier I wish everyone used.

**Comment by MortenHofft** [comment]
@qgroom but https://www.gbif.org/occurrence/1835991458 would not be linked, despite the institutionCode. At least in this suggested first version. Unless we add a MachineTag to [the dataset](https://www.gbif.org/dataset/c0cc29de-f49f-4b66-b4ec-c83afbb7101d) stating that in this dataset if you see `institutionCode:BR` then interpret it as [GrSciColl:Botanic Garden Meise](https://www.gbif.org/grscicoll/institution/3b896e03-901d-4cc7-ac2b-61e0469521b0)

BR is also used by [Embrapa Agrobiology Diazothrophic Microbial Culture Collection](https://www.gbif.org/grscicoll/institution/c6b9b27a-84f3-4159-a490-c24895d06799) - but even if it was unique to Meise I suggest we start out being cautious.

**Comment by qgroom** [comment]
OK, that's easy to fix. Although this particular dataset is of observations, rather than specimens. The institutionID doesn't seem so relevant in the case of observations. Observations are linked to the observer and it is the observer who is then affiliated to the institution. The institution has no direct link to the observation, like it does to a specimen that is stored there.

**Comment by MortenHofft** [comment]
> The institutionID doesn't seem so relevant in the case of observations.

You are right - i just needed an example, but I see it wasn't the best one.

**Comment by MortenHofft** [comment]
@fmendezh so summarrizing our conversation the initial dataset tagging will be:

in dataset Naturalis Biodiversity Center (NL) - Botany add a machinetag with
```
namespace: grscicoll.transient.gbif.org
name: institutionid:institution
value: 75b6d3c8-99f3-405e-a3aa-61c6b4b66fd0:Naturalis Biodiversity Center
```

meaning that if you see `institutionId: Naturalis Biodiversity Center` in in that dataset, then add `grsciColl.institutionKey: 75b6d3c8-99f3-405e-a3aa-61c6b4b66fd0` (or such) to the index.

the name will be one of 8 combinations in the form `fieldInTheOccurrence:typeOfGrSciCollEntity`
* institutionid:institution
* institutionid:collection
* institutioncode:institution
* institutioncode:collection
* collectionid:institution
* collectionid:collection
* collectioncode:institution
* collectioncode:collection

Hmm - it feels like some more generic logic for tagging and processing occurrences could be extrapolated from this

**Comment by marcos-lg** [comment]
Closing since this was already implemented in https://github.com/gbif/pipelines/issues/369 and https://github.com/gbif/registry/issues/204
