### ISSUE TITLE
Dates with year 0000

### ISSUE THREAD

**Issue by asturcon** [gbif/pipelines#243]
In the es-occurrence-ws we have a lot of errors in the logs for dates with year 0000 that can be parsed. They are usually in the dateIdentified field.

Examples:
http://c6n1.gbif.org:9200/occurrence/_search?q=occurrenceId:%22SIVIM:INV:S-P14075:Bromus_rubens:2%22
http://c6n1.gbif.org:9200/occurrence/_search?q=occurrenceId:%22urn:uuid:63413C0C-0B88-4F74-9B8D-F55E7784EFC3%22
http://c6n1.gbif.org:9200/occurrence/_search?q=occurrenceId:%22URI:catalog:ROM:Ichthyology:93212%22

**Comment by asturcon** [comment]
Fixed in the es-occurrence here https://github.com/gbif/occurrence/commit/7f0de5d67254d7e9da6b158516d6de89c9c8cec7

Still pending to release and deploy it and to apply it to the HDFS view in pipelines.

**Comment by muttcg** [comment]
The fix deployed in PROD

**Comment by asturcon** [comment]
WS deployed to PROD
