### ISSUE TITLE
recordCount in dataset search API doesn't show the true count -  registry API

### ISSUE THREAD

**Issue by ManonGros** [gbif/pipelines#245]
See this example: https://www.gbif.org/dataset/ffac22e7-fa1f-457f-a14a-a80ba967f4e1

When looking up the dates with the dataset search API:
http://api.gbif.org/v1/dataset/search?publishing_org=1928bdf0-f5d2-11dc-8c12-b8a03c50a862&limit=1&offset=2416
No `recordCount`.

For other datasets:
http://api.gbif.org/v1/dataset/search?publishing_org=1928bdf0-f5d2-11dc-8c12-b8a03c50a862&limit=1&offset=1
`"recordCount":2861028`

It would be great if the recordCount had the true count.

**Comment by muttcg** [comment]
API returns count number
