### ISSUE TITLE
Add bitmap cache to geocode client

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#250]
The previous generation of the geocode client used a bitmap image cache to lookup countries before call the web service. This provided *considerable* performance improvements and would benefit others, such as the ALA pipelines.  Effectively it means the client can determine all terrestrial and international water locations not near a border without needing to call a service.

I recommend porting this implementation into the pipelines to achieve the same. This would be far preferable to passing around large lookup cache dumps as it will accommodate new terrestrial coordinates as well.

Relevant older code:
https://github.com/gbif/geocode/blob/master/geocode-api/src/main/java/org/gbif/geocode/api/cache/GeocodeBitmapCache.java

https://github.com/gbif/occurrence/blob/master/occurrence-processor/src/main/java/org/gbif/occurrence/processor/interpreting/CoordinateInterpreter.java#L83

The bitmap looks like this and only areas in black invoke a service call:
![image](https://user-images.githubusercontent.com/237221/73168222-b707d680-40f9-11ea-971a-04d0751a715f.png)

The 7200x3600 image is on https://api.gbif.org/v1/geocode/bitmap

CC @djtfmartin @MattBlissett @muttcg

**Comment by MattBlissett** [comment]
Something the current service doesn't do is use the coordinate uncertainty. That's relevant for the thickness of the black lines, and worth thinking about for a new implementation.

Possibly we could have multiple images, for low + high uncertainties.

(Also, I don't know how much difference it would make to interpretation. Presumably the HBase lookup cache isn't using uncertainties either.)

**Comment by muttcg** [comment]
In PROD
