### ISSUE TITLE
Improve recordedBy tokenization

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#253]
Submitting by proxy (CC @emhaston @qgroom)

Searching by `recordedBy` causes frustration. It currently seems to operate as a strict prefix-only filter so a search for "Robertson" does not catch "Tim Robertson"

If we can tokenize that so that a search for `Robertson` could catch-all of `Tim Robertson`, `John Robertson` etc and `Robertson Tim` would boost the `Robertson, Tim`, `Tim Robertson`, `Timothy Robertson` in the results it would be greatly appreciated.

**Comment by MattBlissett** [comment]
Searching for `T Robertson` could also bring back `Tim Robertson`, and `T X Robertson` might also be a useful partial match.
