### ISSUE TITLE
Enable occurrence search by IUCN redlist category

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#257]
Use the IUCN Red List API to add an IUCN Red List category field to every record.
Enable this as a search filter and include this in both simple and DwC-A download files.

**Comment by fmendezh** [comment]
@timrobertson100 I assume that this is the ws we should use (match by name)[https://apiv3.iucnredlist.org/api/v3/docs#species-individual-name](https://apiv3.iucnredlist.org/api/v3/docs#species-individual-name)
@muttcg maybe this is another candidate for a kv-store cache?

**Comment by timrobertson100** [comment]
@andrewrodrigues will confirm. He is our IUCN liaison and requested this (and the other IUCN ones I just logged while we were on a call)

**Comment by timrobertson100** [comment]
When establishing the IUCN API Token please use informatics@gbif.org or similar (@MattBlissett - your preference?) and not a personal email address.

**Comment by andrewrodrigues** [comment]
Yes, that would the ws.  There may be some taxonomical issues as we do not have an up to date red list published but I am working on that

**Comment by andrewrodrigues** [comment]
Is there a reason why the threat status is coming from Wikidata and but the source link takes you through to the red list page?  Can you confirm that we will be getting the threat statuses through their API?    There was a suggestion from IUCN to automate the process of IUCN checklist update from our side through their - Marie had said this was possible - and at the same time retrieve the threat statuses of the species

**Comment by andrewrodrigues** [comment]
The scale we use for the showing the red list is from Wikidata and is not the correct branding that IUCN uses.  This will need to be updated.

**Comment by MattBlissett** [comment]
(@andrewrodrigues, please try and keep the discussion on this issue, and open new issues as required -- it's very confusing tracing a topic through 3-4 different issues! https://github.com/search?type=Issues&state=open&q=org%3Agbif+IUCN is all GBIF issues with "IUCN" mentioned, and https://github.com/issues/mentioned those where you are mentioned, and https://github.com/issues/assigned those where you have been assigned. The latter two come via "Issues" at the top of the page.)

> Yes, that would the ws. There may be some taxonomical issues as we do not have an up to date red list published but I am working on that

I have made an issue for this, https://github.com/gbif/data-mobilization/issues/175.

> Is there a reason why the threat status is coming from Wikidata and but the source link takes you through to the red list page?

Their API wasn't fast / reliable enough. See https://github.com/gbif/portal16/issues/1322#issuecomment-601254760

> Can you confirm that we will be getting the threat statuses through their API?

Receiving it as a published dataset is preferable, based on our past experience with their API. Building it from their API, and "publishing" it ourselves, is probably still better than using an unreliable API -- it's fast, and the origin of the data is easier to trace.

**Comment by MattBlissett** [comment]
The IUCN Red List data is now available on GBIF: https://doi.org/10.15468/0qnb58

We can now use GBIF APIs to interpret the Red List status of occurrences in GBIF. (However, I think there was another discussion on whether we should enable a filter for (e.g.) all endangered species seen within the last week, and I do not remember the conclusion.)

**Comment by timrobertson100** [comment]
With this now in pace, I think we can proceed as follows:

1. Add a service in the checklistbank API that allows retrieval of the IUCN Red List category (note it is a global not a local RL) for a species.
2. Add the category to all occurrence records which may be `null` (suggest name it `occurrence.iucnRedListCategory`) by looking up using the service (presume a cache will be used)
3. Add capability to search and download occurrences using the IUCN category, and include the field in the DwC-A downloads

This does have the caveat that this is an assignment of the category based on global and not local red lists i.e. all occurrence records will carry the global red list category regardless of any local red list process. 

@andrewrodrigues - can you please confirm this is as agreed?

**Comment by andrewrodrigues** [comment]
Yes, this is correct.  Would be good to set this up in UAT first before gbif.org to test the functionality and capture any concerns before it is rolled out.

**Comment by MattBlissett** [comment]
@mdoering, @fmendezh, @andrewrodrigues, @ahahn-gbif

I had a quick look at the suggested change to Checklistbank, but I think we need a bit more logic around synonymy -- or at least, to discuss whether we need to handle it, and work out where we explain any differences between the Red List and the GBIF Backbone.

For example, our occurrences of [_Loxodonta cyclotis_](https://www.gbif.org/species/2435349) (African elephant) should be marked as vulnerable, but the [IUCN name](https://www.gbif.org/species/176661685) is a synonym (without a threat status). It's [IUCN _Loxodonta africana_](https://www.gbif.org/species/176661683) (African elephant) that is accepted in the IUCN Red List, and has the threat status.

There's also the situation where the occurrence matches to a synonym backbone name but accepted backbone name has an IUCN name with a RL status.

**Comment by mdoering** [comment]
Solving the synonym issues properly is difficult as this is exactly the reason why we need to work with taxon concepts, not just names as we do now. It makes a real difference which threat status a species has if the name was split and there is a broader and a narrower concept, i.e. more or less included individual.

Nevertheless, knowing we don't show the right status in some cases, how about:
 - we always resolve any IUCN synonym to its accepted name in the CLB service and take the threat status from there
 - we pass in the accepted GBIF name if the occurrence is linked to a synonym?

**Comment by timrobertson100** [comment]
Aside:

@andrewrodrigues verified with the IUCN that the name of this field internally, in downloads, in the API, and on the web should be `IUCN Red List Category`.

**Comment by timrobertson100** [comment]
> For example, our occurrences of [_Loxodonta cyclotis_](https://www.gbif.org/species/2435349) (African elephant) should be marked as vulnerable, but the [IUCN name](https://www.gbif.org/species/176661685) is a synonym (without a threat status). It's [IUCN _Loxodonta africana_](https://www.gbif.org/species/176661683) (African elephant) that is accepted in the IUCN Red List, and has the threat status.

I discussed this with @andrewrodrigues and we propose that we should mark the _Loxodonta cyclotis_ records with:

_Loxodonta cyclotis_ Vulnerable, assessed as _Loxodonta africana_

The current [API call](http://api.gbif-dev.org/v1/species/2435350/iucnRedListCategory) for _Loxodonta cyclotis_ returns:

```
{
  "category": "VULNERABLE",
  "code": "VU"
}
```

I suggest we extend that to include the name of the accepted species that was assessed, and the ID in the RedList checklist:

```
{
  "category": "VULNERABLE",
  "code": "VU",
  "iucnRedListName: "Loxodonta africana (Blumenbach, 1797)",
  "iucnRedListSpeciesKey: 176661683
}
```

We'd then be able to link to the "concept" that was used to base the assessment on, and include the name in the occurrence downloads.

**Comment by mdoering** [comment]
Makes sense in those cases when our accepted name is a synonym in IUCN.
But what about the reverse? Would you consider to flag GBIF synonym occurrences with a different status than their GBIF accepted occurrences in case they differ in IUCN? That would be a name link to IUCN and follow their taxonomy then. Sounds good, but we do display and organize occurrences with a different taxonomy. That might be rather misleading then.

**Comment by mdoering** [comment]
should we then not also get back a link to the IUCN page?

**Comment by MattBlissett** [comment]
The link back to the IUCN page is the "Source" on the species page, i.e. https://apiv3.iucnredlist.org/api/v3/taxonredirect/12392

This is what Markus describes: what do we do with occurrences of _Aus cus_?

```
GBIF Backbone      IUCN

Aus bus (acc)      Aus bus (acc) CR
         ↑  
Aus cus (syn)      Aus cus (acc) LC
```

**Comment by timrobertson100** [comment]
What Markus said seems reasonable.

The lookup service can find `Aus cus L. 1771` in the backbone and since it is a synonym go into different logic. 
We find the `name_usage` within the RL that shares the same canonical name (`Aus cus` ignoring authorship), but then verify that it is in the same family (another canonical name check) to exclude homonyms, and then return the category for the `Aus cus` in the RL.

?

**Comment by mdoering** [comment]
> We find the name_usage within the RL that shares the same canonical name (Aus cus ignoring authorship), but then verify that it is in the same family (another canonical name check) to exclude homonyms

That would create a new mapping service between Aus cus (backbone) and Aus cus (IUCN) within the pipelines project? That seems rather dangerous to me. We then have 3 different matching services in play here, occurrence->backbone matching, RL->backbone checklist matching, pipeline backbone->RL matching. 

Also showing Aus cus as LC on the GBIF Species page while saying it is a synonym of Aus bus which is shown as CR seems dubious. Should we not better (and simpler) show always the GBIF accepted names IUCN status for all its synonyms?

**Comment by mdoering** [comment]
> The link back to the IUCN page is the "Source" on the species page, i.e. https://apiv3.iucnredlist.org/api/v3/taxonredirect/12392

Yes. And that comes from the IUCN checklist data so we could include this in the response to reduce the number of calls

**Comment by timrobertson100** [comment]
> That would create a new mapping service between Aus cus (backbone) and Aus cus (IUCN) within the pipelines project?

No, it'd be within service in checklistbank

**Comment by mdoering** [comment]
Yes, I think it makes most sense to follow the IUCN taxonomy and use a pure name mapping to bridge across from occurrence or GBIF names. But it is  slightly weird when we mix the IUCN & GBIF taxonomy on species pages. I guess we do this already today. And if we make clear we apply the IUCN taxonomy, not the GBIF one, to evaluate the redlist status, then this is probably the best thing we can do.

That means for the pipelines it is always the nubKey to pass into the redlist service, never the accepted name usage key.
So when we see [an occurrence](https://www.gbif.org/occurrence/1919784943) for [Elephas africanus subsp. albertensis](https://www.gbif.org/species/8523756) [usageKey=8523756] which we treat as a synonym for [Loxodonta cyclotis](https://www.gbif.org/species/2435349) [usageKey=2435349], pipelines should call http://api.gbif.org/v1/species/8523756/iucnRedListCategory which will try to lookup a matching name for Elephas africanus subsp. albertensis in IUCN but fail as this name is not in IUCN. The accepted name Loxodonta cyclotis though would be found, but we would then mix taxonomies.

**Comment by MattBlissett** [comment]
Here's a real example:

_Goniastrea deformis_ is a synonym in GBIF's backbone: https://www.gbif.org/species/2260144 (and has occurrences)

But in the IUCN Red List, it is an accepted name with Vulnerable status: https://www.gbif.org/species/176597529

**Comment by fmendezh** [comment]
I agree with @mdoering that the best approach is to use the nubKey to assess the threat status and not use the accepted name.  If we follow this approach the JSON response can stay as it is with only the threat status name and code.

**Comment by mdoering** [comment]
> If we follow this approach the JSON response can stay as it is with only the threat status name and code.

We could return the accepted name according to IUCN - that might be informative to users.

**Comment by andrewrodrigues** [comment]
Thinking through what information you would want to to retrieve from a search.  if you searched a country for all globally critically endangered species, would you 

1. Retrieve all occurrences where the taxon assessed by IUCN matches the accepted name in GBIF?
2. Retrieve occurrences where the taxon assessed by IUCN is considered a synonym by GBIF?  In this case, the assessment associated to the GBIF accepted names should be flagged as assessed as the IUCN taxonomic concept.
3. Retrieve occurrences where GBIF accepted names are considered synonyms of the taxon assessed by IUCN.  In this case, the threat category for GBIF synonyms should be flagged as being assessed as the IUCN taxonomic concept. 

Would this be the case with the approach above?

One problem I can see with this approach is where species have been lumped and there have been assessments of all the previous species but not of the new species.  In this instance we might have several assessments associated to one accepted taxon in GBIF.  Not sure how to get around that.

**Comment by mdoering** [comment]
I think I would try to ignore the GBIF taxonomy and try to lookup the GBIF name in IUCN and evaluate the redlist category according to IUCNs taxonomy as this is what the assessment is based on. In order to show that the assessed IUCN name was a different one we should return the accepted IUCN name from the API - as well as the exact scientific name spelling used in IUCN and possibly the taxonomic status & rank, as we are not only dealing with species. 

```
/species/2435349/iucnRedList
{
  "category": "VULNERABLE",
  "code": "VU",
  "scientificName: "Loxodonta cyclotis Matschie, 1900",
  "usageKey: 176661685,
  "taxonomicStatus: "synonym",
  "acceptedName: "Loxodonta africana (Blumenbach, 1797)",
  "acceptedUsageKey: 176661683
}
```

**Comment by andrewrodrigues** [comment]
This sounds like a good approach, and I am assuming that with the red list in backbone it would then also be able to pick up examples like this ?
Paragoniastrea deformis is an accepted name in GBIF's backbone with no matching name in IUCN : https://www.gbif.org/species/7813935 (and has occurrences). However, there is an assessment for it´s synonym goniastrea deformis assessed as Vulnerable : https://www.gbif.org/species/176597529

**Comment by timrobertson100** [comment]
In this case, all 14 [records](https://www.gbif.org/occurrence/search?taxon_key=7813935) for _P. deformis_ are provided with a scientific name of _G. deformis_ and so yes they would pick up vulnerable. If they had been supplied with _P. deformis_ as the scientific name, then no, they would not get a category.

**Comment by andrewrodrigues** [comment]
Thanks Tim for explaining.  This definitely seems like the best approach.

**Comment by andrewrodrigues** [comment]
Not sure why the filter was taken off the UAT environment. Can this filter be introduced again with a view to making it available outside of the UAT environment?

**Comment by MortenHofft** [comment]
It was removed from the UAT website because UAT is used for many other tests than IUCN. Do you need it to be public or would a private test environment be sufficient?

**Comment by andrewrodrigues** [comment]
It would be good to make the filter public.

**Comment by MattBlissett** [comment]
Note also the related issue here: #495.

There's also a more recent version of the IUCN Red List.  I will update our imported version.

**Comment by mdoering** [comment]
Is it possible to automate the redlist dwca generation and build it regularly?

**Comment by andrewrodrigues** [comment]
There are limitations on the size of the calls we can make on the API which may limit the automation of red list updates, will leave it with Matt for more details.  Regarding the periodicity of updates, there is no fixed schedule of red lists updates with the list updated regularly on continual basis.  I would suggest updates every 6 months unless of course there are large updates that we know are coming up such as for the Congress where we might want additional updates

**Comment by MattBlissett** [comment]
We weren't able to use the API, as the bulk download we need to use isn't available that way, and downloading the whole list through the API isn't practical.

I think they mark a release every 6 months or so as a new version.  The current version is 2021-2, which is shown in the API: https://apiv3.iucnredlist.org/api/v3/version .  I can set up a monitor to detect what that number increases, and prompt someone (me) to download the new data.

**Comment by mdoering** [comment]
How do you download the data, can that be scripted? For ITIS or NCBI we also check for newly available db dumps and then process them into a DwCA. Maybe we can integrate IUCN also into https://github.com/mdoering/checklist_builder?

**Comment by MattBlissett** [comment]
It is already there: https://github.com/mdoering/checklist_builder/blob/master/src/main/java/de/doering/dwca/iucn/ArchiveBuilder.java#L82-L104 (and I just requested new downloads).

Requesting a download from the IUCN site requires several steps in the browser, agreeing to various terms and conditions etc.

**Comment by MattBlissett** [comment]
I've added the 2021-2 version to https://hosted-datasets.gbif.org/datasets/iucn/ and updated the endpoint in the registry.

We'll need to reinterpret all occurrences before we launch the feature, but it probably doesn't make much difference while we have the other issues around synonymy and data security.

**Comment by MattBlissett** [comment]
The other pending issue is the https://github.com/gbif/pipelines/issues/496 interpretation of aff. species.

**Comment by andrewrodrigues** [comment]
The IUCN filter should show apply a NE - Not Evaluated - category to those species that have not been assessed by IUCN.  This category is not applied systematically by IUCN and thus not available through their API, we will need to apply this category to all species with no IUCN assessment

**Comment by andrewrodrigues** [comment]
The Red List has juts been updated and we will have to update the categories via the IUCN API

**Comment by andrewrodrigues** [comment]
The categories within the filter should be ordered as per the following diagram https://www.iucnredlist.org/about/faqs#What%20are%20the%20Red%20List%20Categories%20and%20Criteria

**Comment by MattBlissett** [comment]
I've moved the NE change to a new issue, so we can close this one.

The ordering is already as on that diagram, and the capitalization is consistent with the other filters (GBIF style) ­-- but that's up to @kcopas / @dnoesgaard anyway.

**Comment by kcopas** [comment]
I'm looking for those categories' strings in CrowdIn without success. Can someone direct my attention to their whereabouts?

**Comment by MattBlissett** [comment]
https://crowdin.com/translate/gbif-portal-en/787/endk-en?filter=basic&value=3 I think.

**Comment by kcopas** [comment]
wow, just couldn't see the tree for the forest—thanks!
