### ISSUE TITLE
Invalidate API cache after indexing

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#264]
After indexing, API shows less data and appears after several minutes, it is connected to API cache, we need to clean by datasetKey cache after indexing

**Comment by MattBlissett** [comment]
Something as simple as

```
curl -i -X BAN http://api.gbif.org/ -H 'X-Ban-URL: .*datasetKey.*'
curl -i -X BAN http://www.gbif.org/ -H 'X-Ban-URL: .*datasetKey.*'
```

would be sufficient to drop the appropriate Varnish caches.
