### ISSUE TITLE
ELK ingestion logs are not indexed by dataset key and attempt

### ISSUE THREAD

**Issue by MattBlissett** [gbif/pipelines#270]
Pipelines entries in the registry console link to predefined searches in ELK, e.g. https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),index:AWyKwQsdHCKcR6PFVqgv,interval:auto,query:(query_string:(query:'datasetKey:%223c6e7390-3b56-11dc-8c19-b8a03c50a862%22%20AND%20attempt:%22352%22')),sort:!('@timestamp',desc)) .

1. There's no index for UAT.

2. It is using `datasetId`, but ought to use `datasetKey` (the GBIF key), which is also used by the older crawler processes.  (`datasetId` is a different DWC term.) The registry-console will need to be updated.

**Comment by muttcg** [comment]
Added UAT indices and changed MDC to datasetKey
