### ISSUE TITLE
Set and clear occurrence crawl status for a dataset

### ISSUE THREAD

**Issue by MattBlissett** [gbif/pipelines#271]
When an ingestion attempt is in progress for a dataset, the ZK path `/prod_crawler/crawls/datasetKey/processState/occurrence` should be set to `RUNNING`.  (The Crawler does this, once validation of the dataset is completed.)

When all pipelines steps have completed, it should be set to `FINISHED`.

For sample-based datasets there is an additional key (`sample`), which should be set in addition to `occurrence`.

This will prevent overlapping ingestions of the same dataset, which has caused deadlocks. See https://github.com/gbif/crawler/issues/37

**Comment by MattBlissett** [comment]
This is probably the cause for [this dataset](https://www.gbif.org/occurrence/search?dataset_key=d962a7dc-2183-4824-bb88-5e0ba14ec62d) to say it has 1,172,209 occurrences in ES, when it only has 729,142 in the Hive table.

```
curl -Ss 'https://api.gbif.org/v1/occurrence/search?dataset_key=d962a7dc-2183-4824-bb88-5e0ba14ec62d' | jq '.results[].key'
2444610107
2444610107
2603263579
2603254570
2603255569
2603256566
2603257569
2603259569
2603262573
2603263566
2603264567
2603264567
2603265567
2603265567
2603266565
2603266565
2603267564
2603267564
2603268567
2603268567
```

@fmendezh, @muttcg, this is an important bug which must be the next priority.

**Comment by muttcg** [comment]
In PROD

**Comment by muttcg** [comment]
Must be fixed, reopen in case of an issue
