### ISSUE TITLE
Add identifiedBy search

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#273]
As the title states. We have recordedBy, recordedByID and identifiedByID but not identifiedBy.

This should be added for search and to the appropriate download formats.

**Comment by MattBlissett** [comment]
It is already in the Simple and DWCA downloads.

**Comment by MattBlissett** [comment]
Relates to https://github.com/gbif/occurrence/issues/127

**Comment by muttcg** [comment]
API is ready:

https://www.gbif.org/occurrence/download/0010796-200613084148143
https://www.gbif.org/api/occurrence/search?advanced=true&locale=en&identified_by=Carmelino+S%C3%A1ntiz+Ru%C3%ADz

"total" : 237101310 with identifiedBy
