### ISSUE TITLE
ALA Q15 - georeferencedDate is missing in LocationRecord

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#290]
[georeferencedDate](https://dwc.tdwg.org/terms/#dwc:georeferencedDate) is missing in LocationRecord meaning ALA need to fork GBIF pipelines. We should add that into the LocationRecord to avoid this.

**Comment by djtfmartin** [comment]
I think this should be `georeferencedDate`

https://dwc.tdwg.org/terms/#dwc:georeferencedDate

**Comment by muttcg** [comment]
Thank you @djtfmartin I labeled as a bug

**Comment by qifeng-bai** [comment]
geoReferencedDate has been added into LocationRecord in ALA fork.  However, the corresponding interpreter is still in ALA-pipeline project, I am thinking if it should be moved into Gbif

**Comment by muttcg** [comment]
@qifeng-bai Could you add the reference to the codebase?

**Comment by muttcg** [comment]
Close all ALA Q*
