### ISSUE TITLE
Review dependencies to reduce shaded jar size

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#293]
The `ingest-gbif-2.4.3-shaded.jar` is 167MB and can be trimmed down. For example it has the Hadoop webapps, Google Cloud client libraries and config etc. 

Trimming this down to include only what is needed will help in both diagnostics (e.g. addressing CP issues over time) and startup performance.

**Comment by muttcg** [comment]
Dropped to 125MB, can't be reduce less
