### ISSUE TITLE
Allow HDFS location to be configurable in FileSystemFactory

### ISSUE THREAD

**Issue by djtfmartin** [gbif/pipelines#294]
FileSystemFactory is currently hardcoded to the address hdfs://ha-nn

https://github.com/gbif/pipelines/blob/master/pipelines/ingest-gbif/src/main/java/org/gbif/pipelines/ingest/utils/FileSystemFactory.java#L16

This value is used to decide if a file system path is HDFS or not. Anything not starting with this path is deemed to local storage.

**Comment by timrobertson100** [comment]
Would it perhaps make sense to make better use of the Beam `FileSystems` here? This is always returning an instance of the Hadoop `FileSystem` while the Beam `FileSystem` would allow for GCS, S3, Azure objects as well (which are all now used in ALA and GBIF)

**Comment by muttcg** [comment]
It can be as an enhancement, it is mostly used for reading configs, I am planning to redesign this part soon for #276 #277 #278

**Comment by djtfmartin** [comment]
This is still an issue for us as main places in the code go with the default `HDFS_PREFIX` value. Ive changes to get HDFS working for ALA on a branch here:

https://github.com/AtlasOfLivingAustralia/la-pipelines/blob/feature/spark-uuid-migration/pipelines/src/main/java/org/gbif/pipelines/ingest/utils/FileSystemFactory.java

Essentially, the precedence is given to the `default.FS` value configured in `hdfs-site.xml` over the values passed to the `FileSystemFactory`. 

I think this class would be cleaner if we just remove the hdfsPrefix arguments and rely on the hdfs-site.xml but maybe there are reasons this is undesirable.

**Comment by muttcg** [comment]
Thanks @djtfmartin, I reopen the issue
