### ISSUE TITLE
interpretTemporal cannot recognise date like:  11/12/2012

### ISSUE THREAD

**Issue by qifeng-bai** [gbif/pipelines#315]
When TemporalInteperter. interpretTemporal() is parsing DwcTerm.dateIdentified
It can parse
12/12/2012 , 12/13/2012, 11/DEC/2012.,

but failed without any assertion on
11/12/2012 

Wondering if we should raise an unrecognised date assertion if parsing failed.

**Comment by muttcg** [comment]
Because it is fuzzy, unfortunately not all users use ISO dates and can use local standards, so 11/12/2012 can be as 11/December/2012 or November/12/2012

**Comment by djtfmartin** [comment]
Thanks @muttcg i need to check the numbers but from memory `dd/MM/yyyy` is the one of the most common formats in the use for Australia.

**Comment by timrobertson100** [comment]
If we are to flag, I suggest we don't use the existing `RECORDED_DATE_INVALID` which would be unfair, especially if the publisher declared the date format in the DwC-A meta.xml file - see `dateFormat` in the [DwC Text Guide](https://dwc.tdwg.org/text/). I'd recommend adding a `RECORDED_DATE_AMBIGUOUS` flag for this scenario. 

It would be good if the pipeline could take a format. Australia could probably supply that in config as it will almost certainly apply to everyone, while GBIF would ideally add a machine tag to the dataset and use that in the pipeline. The machine tag would be set when opening the DwC-A capturing the date format if supplied or be set by a data manager. GBIF cannot assume a format as that can make ambiguous data wrong.

**Comment by MattBlissett** [comment]
It's also by far the most common in general use in Europe, Africa and South America, but `MM/dd/yyyy` is used in the USA, and the two formats are ambiguous.  Sometimes it can be resolved using the dwc:month and dwc:day fields.

DWC Archive has [an attribute](https://dwc.tdwg.org/text/#221-attributes) to say if a non-ISO format is used, but we don't support it. The DWC recommendation is to use ISO `yyyy/MM/dd` dates.

It could be possible to work out which format is used by looking at the whole dataset, but in general we've instead asked publishers to publish in an unambiguous format.

**Comment by djtfmartin** [comment]
I'll transfer this issue across to la-pipelines issue tracker as this something ALA need to action due to common place use of this date format. Thanks for suggestions @timrobertson100  - externally configurable lists of supported formats specific to a deployment sounds like the way to go for now....

**Comment by djtfmartin** [comment]
Tracking here: https://github.com/gbif/pipelines/issues/315
