### ISSUE TITLE
Change definition of org.gbif.rest.client.geocode.Location to accomodate other region types

### ISSUE THREAD

**Issue by djtfmartin** [gbif/pipelines#322]
The interface `GeocodeService` returns collections of `org.gbif.rest.client.geocode.Location` objects.
This class definition has the following fields:

```java
    private String id;
    private String type;
    private String source;
    @JsonProperty("title")
    private String countryName;
    private String isoCountryCode2Digit;
```

We would like to add a `name` field (or something else) to distinguish for results returning non-country lookups such as `stateProvince` and sensitive region lookups. Or perhaps we rename `countryName` to name.....

**Comment by MattBlissett** [comment]
As far as I can see, we don't use `countryName` anywhere in pipelines. It was just a convenience field provided by the lookup service.

I've renamed it to `name`, which I think makes more sense than `title`.

**Comment by MattBlissett** [comment]
@fmendezh, there are some other changes to the key-value-store, do you need to review these before releasing?

**Comment by djtfmartin** [comment]
Is there any progress on this ?
the `ala-dev` branch has a copy of this class in the `livingatlas` module as workaround. 

https://github.com/gbif/pipelines/blob/ala-dev/livingatlas/pipelines/src/main/java/org/gbif/rest/client/geocode/Location.java

Im keen to remove it before the merge of `ala-dev`.

**Comment by MattBlissett** [comment]
@fmendezh, I was just waiting for you to say if you were working on something else in the key-value-store. Presumably not, so it can be released today?

Dave, I renamed `countryName` → `name`, whereas your class adds an additional `name` field.  Do you need the `countryName` field for other region types? Our geocode server isn't supplying one, though it could be changed.  It does provide an `isoCountryCode2Digit` where the region is within a country.

**Comment by djtfmartin** [comment]
Thanks Matt. I'll change the copy of this class to reflect your changes in the `ala-dev`. I agree we dont need the `countryName` if we have `isoCountryCode2Digit`.

**Comment by fmendezh** [comment]
@MattBlissett the change seems fine by now, I'm not sure if different semantics for fields can make the API a bit confusing, i.e.:
name: can be the name of the country or area
isoCountryCodes: country code in which the area is located, or else the country code of the location returned

Once we integrate this with GADM we should change this class to something less ambiguous, keep in mind that we must truncate all cache tables.

**Comment by MattBlissett** [comment]
Then, @djtfmartin, just change the version of key-value-store to 1.7 to bring in the change.
