### ISSUE TITLE
Integration of the LifeStage vocabulary in the interpretation pipelines

### ISSUE THREAD

**Issue by marcos-lg** [gbif/pipelines#329]
This integrates the newly create `LifeStage` vocabulary using the vocabulary server (https://github.com/gbif/vocabulary).

This removes the use of the former `LifeStage` parser and [enumeration](https://github.com/gbif/gbif-api/blob/master/src/main/java/org/gbif/api/vocabulary/LifeStage.java).

**Comment by muttcg** [comment]
in prod
