### ISSUE TITLE
Parameterize ports for the LivingAtlas docker-based tests

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#337]
I think the LivingAtlas module tests use docker based services for integration tests. These _appear_ to be using hard-coded ports [in the pom](https://github.com/gbif/pipelines/blob/ala-dev/livingatlas/pipelines/pom.xml#L200).

If this is correct I think this will cause collisions in Jenkins and may e.g. make release processes fragile. I suggest we investigate this and the implications.

**Comment by timrobertson100** [comment]
An alternative here could be to explore using travis (which I gather isolates builds) and could be used to perform the maven releases
https://travis-ci.org/github/gbif/pipelines/builds/709442890

**Comment by timrobertson100** [comment]
_Perhaps_ another alternative could be to isolate builds in Jenkins using something like the [docker plugin](https://plugins.jenkins.io/docker-plugin/)

**Comment by MattBlissett** [comment]
(What do the GBIF-based integration tests use -- mocked responses?)

Another alternative is to add another HTTP port.

9179 is mentioned here:

```grep
livingatlas/pipelines/pom.xml:                    <url>http://localhost:9179/api/search?q=Acacia</url>
livingatlas/pipelines/src/main/docker/ala-nameservice.yml:      - "9179:9179"
livingatlas/pipelines/src/test/resources/pipelines.yaml:  wsUrl: http://localhost:9179
livingatlas/scripts/pipelines.yaml:  wsUrl: http://localhost:9179
```

The POM one is very easy to replace (just a variable), the others would probably require a Maven resource processing step, or being defined elsewhere, e.g. in the POM / on the command line.

**Comment by fmendezh** [comment]
It seems that there's a way to use environment variables and an external file with port mappings https://dmp.fabric8.io/#misc-env

**Comment by MattBlissett** [comment]
See https://github.com/gbif/pipelines/compare/337-la-docker-ports (demo-quality commit). It would need another property for the other port on the ala-namematcher, and two for the SOLR container.

I won't do any more on this today.

**Comment by MattBlissett** [comment]
The PR didn't quite work, and my local test before merging didn't catch it, since I tried with ports 8000, 7000, 6000, 5000.

The first Jenkins build after the merge used actual random ports, and failed.  This is because SOLR includes an embedded ZooKeeper, and the ZooKeeper port is fixed at ($SOLR_PORT + 1000). I don't see a way to override that, and I don't think there's a way to reserve two ports 1000 apart in Jenkins.

For the moment, I've reserved two specific ports.  Builds (across Jenkins) will block until these two ports are available.

`-Dalanm.port=$ALANM_PORT -Dalanm.admin.port=$ALANM_ADMIN_PORT -Dsolr8.zk.port=4474 -Dsolr8.http.port=3474`

**Comment by djtfmartin** [comment]
Thanks @MattBlissett 

im wondering if further work is required or whether the current solution - limited by fixed ports which can be set outside the build is acceptable for the merge of #326  - any thoughts @timrobertson100 ?

**Comment by timrobertson100** [comment]
>  is acceptable for the merge of #326 - any thoughts @timrobertson100 ?

As long as we are able to release without risk of port collisions, or have constantly failed builds from the 3 branches it shouldn't block a merge.

> Builds (across Jenkins) will block until these two ports are available.

Is it possible to define different ports for each of the 3 builds perhaps?

**Comment by MattBlissett** [comment]
> Is it possible to define different ports for each of the 3 builds perhaps?

Yes, it would be.  These ports need defining before the branch is merged, I've only done it for the pipelines-la-dev build so far.

**Comment by MattBlissett** [comment]
I've added the port definitions to the other two jobs.
