### ISSUE TITLE
Integrate the collections lookup service to link occurrences with GrSciColl data

### ISSUE THREAD

**Issue by marcos-lg** [gbif/pipelines#369]
A [collections lookup service](https://github.com/gbif/registry/issues/204) was recently implemented to help us matching occurrence data with GrSciColl institutions and collections. 

Now we need to integrate it into pipelines. The integration can be done in the following way:

- The call to the WS will be integrated as a KV-Store. Still to be determined if we'll use HBase cache or any other cache.
- The interpreted data will be stored in a separate avro file so in the future we can reinterpret only this data.
- We index to ES the keys, codes and names of the institutions and collections matched so we can perform searches on these fields. @MortenHofft do you have any other field in mind?

**Comment by MortenHofft** [comment]
> do you have any other field in mind?

No I think that is fine for the occurrence index. As of now I wouldn't know what to do with the `name` actually. `Code` and `key` is the only essential at this point I would think.

**Comment by muttcg** [comment]
in prod
