### ISSUE TITLE
Restructuring suggestions for common code

### ISSUE THREAD

**Issue by djtfmartin** [gbif/pipelines#381]
The following classes should probably be considered as "core" classes, and ideally moved out of the `gbif` module to avoid dependencies between `livingatlas` and `gbif` module.

From https://github.com/gbif/pipelines/tree/gbif-dev/gbif/pipelines/ingest-gbif-beam/src/main/java/org/gbif/pipelines/ingest/utils:

 * FileSystemFactory.java
* FsUtils.java
* MetricsHandler.java

From https://github.com/gbif/pipelines/tree/gbif-dev/gbif/pipelines/ingest-gbif-beam/src/main/java/org/gbif/pipelines/ingest/options

* BasePipelineOptions.java
* DwcaPipelineOptions.java
* InterpretationPipelineOptions.java
* PipelinesOptionsFactory.java

From https://github.com/gbif/pipelines/tree/gbif-dev/gbif/pipelines/ingest-gbif-java/src/main/java/org/gbif/pipelines/ingest/java/

* AvroReader.java
* OccurrenceExtensionTransform.java
* ConfigFactory.java 

While not in direct use, these classes look generic enough to be considered core:

https://github.com/gbif/pipelines/tree/gbif-dev/gbif/pipelines/ingest-gbif-java/src/main/java/org/gbif/pipelines/ingest/java/metrics

* IngestMetrics
* ElasticsearchWriter.java

**Comment by muttcg** [comment]
Merged to gbif-dev
