### ISSUE TITLE
Index hosting organization key

### ISSUE THREAD

**Issue by fmendezh** [gbif/pipelines#386]
Adding the hosting organization key to the search index will help GBIF nodes and associates to filter occurrence records for further reporting.

This requires changes to the [MetadataInterpreter](https://github.com/gbif/pipelines/blob/b53a49c5dbf233655407a18aa30a54be53555f14/sdks/core/src/main/java/org/gbif/pipelines/core/interpreters/metadata/MetadataInterpreter.java), [Occurrence HDFS Record](https://github.com/gbif/pipelines/blob/0a18eb3d39ec986a55f7affd4bb623c90a8ad647/sdks/models/src/main/avro/occurrence-hdfs-record.avsc), and tables and more importantly to the ElasticSearch [schema](https://github.com/gbif/pipelines/blob/b53a49c5dbf233655407a18aa30a54be53555f14/gbif/pipelines/ingest-gbif-beam/src/main/resources/elasticsearch/es-occurrence-schema.json).

**Comment by muttcg** [comment]
in prod
