### ISSUE TITLE
Separate date parser from the data display format

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#388]
Depends on date type, we can add an extra month or/and day:
1999 -> 01/01/1999
02/1999 - > 01/02/1999

It would be nice to have a parser which returns one of the java temporal date type and converter to display type as separated classes

**Comment by MattBlissett** [comment]
The parser does already return a Java TemporalAccessor: https://github.com/gbif/parsers/blob/master/src/main/java/org/gbif/common/parsers/date/TextDateParser.java#L42

What might be needed is a few more utility methods in https://github.com/gbif/parsers/blob/master/src/main/java/org/gbif/common/parsers/date/TemporalAccessorUtils.java to convert these into what we need.

And something to store the dates with their resolution in ES, Avro etc.

**Comment by muttcg** [comment]
in prod
