### ISSUE TITLE
Supporting date range in parsing EventDate

### ISSUE THREAD

**Issue by qifeng-bai** [gbif/pipelines#389]
At the current stage, TemporalIntepreter only take the first period of a date rage (parse a date range as a single date) to set eventDate.GTE.

Developing plan:
**apply on EventDate, **
 Fix  _dateIdentified_ and _modifed_

**_1979_**

 | Current | Expected |Sep 24|
 | --- | --- |--|
 | Year:  1979 | Year: 1979 |1979|
 | Month:               null   | Month:               null   ||
 | day:                    null | day:                    null ||
  | eventDate.GTE:    1979-01-01 | eventDate.GTE:    1979-01-01 |1979|
 | eventDate.LTE:   null | eventDate.LTE:    1979-12-31 |null|

**_1979/1980_**

 | Current | Expected | version on 24 Sep|
 | --- | --- | --|
 | Year:  1979 | Year: 1979 |Year: 1979 |
 | Month:               null   | Month:               null   | |
 | day:                    null | day:                    null ||
  | eventDate.GTE:    1979-01-01 | eventDate.GTE:    1979-01-01 |1979|
 | eventDate.LTE:   null | eventDate.LTE:    1980-12-31 |1980|

**_ 1979-01-15/30 **

| Current | Expected  |
| --- | --- |
 | Year:  1979 | Year: 1979 |
 | Month:               1   | Month:               1   |
| day:                    15 | day:                    15 |
  | eventDate.GTE:    1979-01-15 | eventDate.GTE:    1979-01-15 |
 | eventDate.LTE:   null | eventDate.LTE:    1979-01-30 |

  **_dateIdentified_ and _modifed_**
| GBIF | Expected | 
| --- | -- |
 | dateIdentified = 1979-01-01 | dateIdentified: 1979 | 
| modified = 1979-01-01 | modified: 1979 |

**Comment by muttcg** [comment]
Hi! @qifeng-bai 
I am changing TemporalInterpreter for #388 and I can implement ranges using your gbif-parser changes.
Is it OK if I assign this issue to myself?

**Comment by qifeng-bai** [comment]
@muttcg  I have pushed a working version to this branch. Feel free to change it

**Comment by muttcg** [comment]
in prod

**Comment by ahahn-gbif** [comment]
@muttcg, I realize this issue is closed, assuming that means we are now interpreting date ranges from event dates. Would you be able to comment on the discussion at https://discourse.gbif.org/t/how-to-handle-the-event-dwc-fields-for-trap-base-occurrence/3162? It also concerns recommendations we would want to give publishers of sampling event data, so that they can model their collection periods correctly, rather than using work-arounds as documented in earlier comments in that thread. Many thanks!

**Comment by muttcg** [comment]
@ahahn-gbif It is been supported by ingestion for a while, if look at the record:

https://api.gbif.org/v1/occurrence/2513081858/fragment

in our index we have interpreted fields:

```
"eventDateSingle": "1915-10-01T00:00",
"eventDate": {
    "gte": "1915-10-01",
    "lte": "1915-10-31"
},
```

But unfortunately is not supported by our API, at least yet

**Comment by Mesibov** [comment]
@muttcg, can you explain what you mean by "supported"? If I look at [https://www.gbif.org/occurrence/2513081858](https://www.gbif.org/occurrence/2513081858), I see an original 1915-10-01/1915-10-31 eventDate, and a processed eventDate of 1915-10-01T00:00:00, with year, month and day entries of 1915, 10 and 1.

So "supported" means that interval dates are no longer flagged as invalid, but are still converted to single dates in processing? Please also see John Wieczorek's comment in GBIF discourse thread: the Darwin Core Maintenance Group advises _not_ to fill in year, month and day if the event covers more than one.

**Comment by Mesibov** [comment]
This particular record raises another question about GBIF date processing. Although Naturalis has provided an interval date, the [specimen label](https://bioportal.naturalis.nl/multimedia/L++0006048_687341284/associatedSpecimenReference=L++0006048%40BRAHMS&associatedSpecimenReferenceOperator=EQUALS&from=0#prettyPhoto) says "October, 1915".

eventDate could therefore have been "1915-10". In its advice to data publishers, GBIF [says](https://www.gbif.org/data-quality-requirements-occurrences#dcEventDate) "For the levels of information that are unknown, avoid padding and instead end the value, to limit ambiguity of interpretation. If, for example, only year and month are known, represent this as 2016-04, not as 2016-04-01."

Can you confirm that in processing "1915-10", GBIF would no longer alter this to "1915-10-01T00:00:00", and fill year with 1915, month with 10 and day with 1?

**Comment by muttcg** [comment]
@Mesibov we have many layers of infrastructure and if simply describe like:
`dwca -> ingestion -> storage -> api -> portal`
so `dwca -> ingestion -> storage` already support and store eventDate as date ranges where range can be of the following patterns:
```
yyyy-MM-dd'T'HH:mm:ss.SSSXXX
yyyy-MM-dd'T'HH:mm:ssXXX
yyyy-MM-dd'T'HH:mmXXX
yyyy-MM-dd'T'HH:mm:ss.SSS
yyyy-MM-dd'T'HH:mm:ss
yyyy-MM-dd'T'HH:mm
yyyy-MM-dd
yyyy-MM
yyyy
```
Means that you can provide evenDate as 2011/2012, or 2011-01/2022-01, or 2021-01-01/2022-01-01 and etc.

Our API is not ready for that, there are many question to solve, as how to present current filters, downloads, reports and etc, or maybe just present as new extra filter.

So we already parse and store eventDate correctly, but don't expose that for API/Portal/Users

**Comment by Mesibov** [comment]
@muttcg, it's excellent that you can successfully parse and store the different eventDate formats. Thank you for confirming that you still, unfortunately, are processing and republishing the date incorrectly.
