### ISSUE TITLE
Many false absences come up in new filter

### ISSUE THREAD

**Issue by gbif-portal** [gbif/pipelines#392]
**Many false absences come up in new filter**

It's great to be able to filter for presence or absence records, but currently the absence filter is picking up many records that clearly do not relate to absence, for example specimens or observations with images. It looks like this is due to inferring absence in cases where 'individual count' is wrongly set at 0 in the original record. Is there some way to avoid this, e.g. not inferring absence in such cases when the basis of record is a specimen, or where there is an image/audio  associated with an observation?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2fec7fc3b6e03b62600805c249535b0b:bd968730a130a9c8f4e3a16a4c60cb4d67a99513570e65f64601f39638f594ec3236c66e612e2a45f919ac8641cc711b8d1608e2028894f8607bff14cefec994)
System: Chrome 85.0.4183 / Mac OS X 10.15.6
Referer: https://www.gbif.org/occurrence/gallery?basis_of_record=PRESERVED_SPECIMEN&occurrence_status=absent
Window size: width 2032 - height 1306
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-11T17:07:46.555Z',mode:absolute,to:'2020-09-11T17:13:46.555Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-11T17:07:46.555Z',mode:absolute,to:'2020-09-11T17:13:46.555Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by timrobertson100** [comment]
@ahahn-gbif what do you prefer here, please?

Clicking around, the proposal to infer present for the case of `individualCount=0 AND occurrenceStatus=NULL AND basisOfRecord=PreservedSpecimen` does indicate it'd catch many false absences, and intuition is it is more likely that a specimen record having individualCount of 0 does reflect the common "0 for null numbers" mistake.

**Comment by timrobertson100** [comment]
Alternatively, most could be fixed from one provider - perhaps we could confirm they have only presence data and set a default on the occurrenceStatus

![image](https://user-images.githubusercontent.com/237221/93448417-e0b57e00-f8d3-11ea-99e1-e28b933c0b9f.png)

**Comment by ahahn-gbif** [comment]
It sounds plausible to interpret "Specimen" as present; I would not assume the same for "occurrence" or "observation", as this again may be a field default (mapping). The earlier, extensive discussion (see #268) did not consider BoR, so that we probably do want to extend the interpretation here for "Specimen", as @timrobertson100 suggests.

The best scenario is to get data sources updated at their origin,but this can be slow progress. The mail shoot in early 2020 focused on inconsistencies between occurrence status and count. @jlegind, how many of the datasets in the list above were already notified in the first round? Would it make sense to write to at least the top ten in the list displayed above, and set the default for occurrence status (where NULL) if there is no reaction in reasonable time?

**Comment by jlegind** [comment]
I will contact Vince at the NHM London and get an explanation. Hopefully this can provide a basis for an updated filter.

**Comment by timrobertson100** [comment]
Update: UK NHM requested default value added (done) so _only_ 258k specimens interpreted as absent exist.

**Comment by ahahn-gbif** [comment]
I would still be in support of the proposal to change the logic so that count=0 _and_ BoR=Specimen -> PRESENT

**Comment by MattBlissett** [comment]
Does this require another issue, `OCCURRENCE_STATUS_INFERRED_FROM_BASIS_OF_RECORD`?

**Comment by timrobertson100** [comment]
Would be the better solution, yes

**Comment by muttcg** [comment]
Should I add the same logic for FOSSIL_SPECIMEN?

**Comment by MattBlissett** [comment]
Yes, fossil, living and preserved specimens.

**Comment by ahahn-gbif** [comment]
I was wondering the same. Yes, I think, especially if there is a specimenID of some kind.

**Comment by muttcg** [comment]
Deployed to PROD
