### ISSUE TITLE
Occurrences of a dataset with unspecified license being interpreted

### ISSUE THREAD

**Issue by MattBlissett** [gbif/pipelines#401]
Occurrences in datasets without a license (i.e. where the dataset has an unsupported, unspecified or null license) must not be interpreted -- ingestion must fail.  Downloads rely on this.

https://www.gbif.org/dataset/32be30f9-0129-4508-8185-3f09c654f9ed is the current example, but I will fix whatever has broken the license and reinterpret it.

**Comment by muttcg** [comment]
Deployed to PROD
