### ISSUE TITLE
Occurrences without a dwc:country / dwc:countryCode are not given one during interpretation

### ISSUE THREAD

**Issue by MattBlissett** [gbif/pipelines#406]
https://www.gbif.org/occurrence/2545421696 and most (all?) of https://www.gbif.org/dataset/962f59bc-f762-11e1-a439-00145eb45e9a do not have a dwc:countryCode set.

It ought to be set (often to Luxembourg), and the issue `Country derived from coordinates` applied.

**Comment by muttcg** [comment]
fix in prod
