### ISSUE TITLE
Relax detection of the media format

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#420]
The current approach of detecting the image format seems particularly strict as described [here](https://github.com/sckott/pygbif/issues/74).

I suggest we relax this.

**Comment by marcos-lg** [comment]
I took a look at the occurrences and it seems that we currently interpret values like `jpeg` as `jpeg` so it seems that the interpretation was relaxed at some point. Please reopen the issue if there are still cases where the format is not detected.
