### ISSUE TITLE
Limit verbatim view to only include extension data we want to accept

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#424]
The current pipeline code puts all extension data into elastic search in a key-value bag of terms that aren't analyzed for the **verbatim** view. Some data are then interpreted into structured nodes in the ES schema.

This has the risk that records with large amounts of extensions data (e.g. accelerometer data) may unwittingly put a lot of data in Elastic and also means we may show content we don't intend to on the site.

I propose we include a configurable list of qualified names for the extension row types we support. This could be using code like the existing [Extension list](https://github.com/gbif/gbif-api/blob/bde4756373189ab87d60fe0e34596aa1ca9796f5/src/main/java/org/gbif/api/vocabulary/Extension.java) but that is missing the following:

1.  https://rs.gbif.org/extension/germplasm/   (new in 2020)
2. https://rs.gbif.org/extension/ggbn/           (new in 2020)
3. https://rs.gbif.org/extension/obis/      (even though we don't use it the same way that OBIS do)
4. https://rs.gbif.org/extension/zooarchnet/     (new in 2020)

Note this would not affect the **fragment** view in HBase which should contain everything.

**Comment by muttcg** [comment]
in PROD
