### ISSUE TITLE
Add hasExtension filter to the occurrence search and downloads API

### ISSUE THREAD

**Issue by fmendezh** [gbif/pipelines#440]
Pipelines are now producing an extensions field in Elasticsearch which contains a list of the available extensions for that record, the values in that field are the namespaces of the available extension:
`"extensions": ["http://data.ggbn.org/schemas/ggbn/terms/Amplification"]`

We have to evaluate at least two ways of resolving the **hasExtension** filter: 

1.  Accepting the qualified name as it is stored in Elasticsearch

2. A simple enumeration value that can be mapped to the qualified name see [Extensions.java](https://github.com/gbif/gbif-api/blob/master/src/main/java/org/gbif/api/vocabulary/Extension.java#L69)

**Comment by timrobertson100** [comment]
I'd suggest sticking to qualified names to avoid collisions in the future (e.g. multiple "identifier" extensions) and to better accommodate the changes where extensions are moved around namespaces, merged etc (e.g. the ongoing effort to align DNA related extensions). Using a fully qualified name that includes the version should be the safest option, at the expense of having to use longer references.
