### ISSUE TITLE
Limit COORDINATE_UNCERTAINTY_METERS_UPPER_BOUND correctly

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#449]
The `COORDINATE_UNCERTAINTY_METERS_UPPER_BOUND` should be `20037509` (metres) and not [5_000_000](https://github.com/gbif/pipelines/blob/master/sdks/core/src/main/java/org/gbif/pipelines/core/interpreters/core/LocationInterpreter.java#L44) as it is half the circumference of the earth.

**Comment by muttcg** [comment]
In PROD
