### ISSUE TITLE
Diagnostic utilities for the ID lookup service

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#455]
We find cases where publishers issue new identifiers and our attempts to track them fail, resulting in our issuing new GBIF IDs.

I propose we need some diagnostic tools on the lookup table that can summarise and fixup issues.

_As a start, perhaps something like this?_

1. list all lookup entries that point to GBIF IDs where the record no longer exists in Elasticsearch. Optionally we should let the user pass in a datasetKey to scope this.
    a. ability to remove those entries 
2. list all lookup entries that are different from those seen on the current record (e.g. an old `occurrenceID` that points to the current record). Optionally we should let the user pass in a datasetKey to scope this. 
   a. ability to remove those entries
3. list all datasetKeys in the lookup table, where no record exists in elasticsearch
  a. ability to remove those entries

We might also consider changing our behavior as follows:

1. Accommodate case changes in codes without issuing new IDs
2. Accommodate changes from http to https without issuing new IDs

**Comment by dshorthouse** [comment]
Great start, @timrobertson100! Would you like that this issue include examples found in the wild? I typically find a number of these every few weeks ranging from a few hundred to hundreds of thousands. From a data publisher's perspective, I can only assume that they believe adjustments to their `occurrenceID` are innocuous (_eg_ newly appending slashes or `/v1`, swapping dashes for colons). They do not realize that this is a linchpin to downstream re-use.

**Comment by timrobertson100** [comment]
There are two things here that I probably shouldn't have mixed. 

People are changing their triplet/occurrenceID in ways we struggle to follow and we need to get better at diagnosing this. Let's keep that on this issue.

Secondly, and people are _presumably_ changing occurrenceIDs in ways we make no attempt to follow and could improve. If you @dshorthouse have examples of occurrenceID changes that GBIF could feasible follow (http -> https etc) could you provide them in a new issue, please, and we can follow that separately?

**Comment by dshorthouse** [comment]
FWIW, here's a dataset that was deleted and three new ones created in its place: https://www.gbif.org/dataset/5733a11d-9286-469c-a9f1-9b21c1e57caa. The new ones are found at https://www.gbif.org/dataset/search?publishing_org=676782cc-e81e-47ce-9504-34ea45395eb6. As near as I can tell, all the `occurrenceIDs`, though integer-based, are reproduced in the now split datasets. However, there are of course whole new `gbifIDs` as a result.
