### ISSUE TITLE
Refactor Avro2ElasticSearchPipeline for code review

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#46]
The [Avro2ElasticSearchPipeline class](https://github.com/gbif/pipelines/blob/master/gbif/src/main/java/org/gbif/pipelines/indexing/Avro2ElasticSearchPipeline.java) contains hardcoded values etc.

This should be refactored to align with our practices of passing in configurations etc. to pass code quality review.

**Comment by aalbatross** [comment]
closes #46
