### ISSUE TITLE
Diagnose dropped records

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#463]
This issue serves to document the findings when investigating a [reported](https://twitter.com/dpsSpiders/status/1349914752408035329) case of records being dropped in indexing.

### Background
GBIF use the `occurrenceID` and the combination of the `institutionCode`, `collectionCode` and `catalogNumber` (referred to as the _triplet_) when ingesting a dataset.  We maintain a lookup table that is consulted to locate the GBIF integer ID for the record. 

For **DwC-A**-based datasets (others have different behaviour), we analyse the content to determine the availability and uniqueness (i.e. all records have a unique value) of the `occurrenceID` and the _triplet_. This analysis determines which local identifiers are used to find a GBIF ID as follows:

| _triplet_ present | _triplet_  unique | occurrenceID present | occurrenceID unique | Outcome |
|:-:|:-:|:-:|:-:|:-:|
| Y | Y | N | - | _triplet_ used to lookup GBIF ID |
| Y | N | N | - | validation fail, no ingestion |
| Y | Y | Y | Y | _triplet_ and occurrenceID used to lookup GBIF ID |
| * | * | Y | N | validation fail, no ingestion if occurrenceID present and not unique |
| Y | N | Y | Y | occurrenceID is used to lookup GBIF ID |
| N | - | N | - | validation fail, no ingestion |

This approach was designed and has been used since ~2011 allowing for publishers to add the (new at the time) `occurrenceID` value  maintaining GBIF IDs, and to allow many people since to change their IDs following a two-publishing-step approach (change occurrenceID, publish and GBIF index, and then change the triplet).

Importantly, in November 2019 GBIF deployed all new indexing infrastructure based on the [pipelines](https://github.com/gbif/pipelines). This brought two important changes:

1. Datasets are processed dataset-by-dataset and then loaded into the index atomically, replacing all records from a previous crawl attempt. Previously, GBIF streamed record by record, followed by a deletion process removing records not updated. Various safeguards could kick in halting deletion of records and resulted in an inconsistent index. Pipelines brings strong consistency, which is generally positive but reveals things abruptly that otherwise could have gone unnoticed.

2. Previously the deletion process removed all obsolete lookups for the record as it ran. With no deletion process in pipelines (we just replace all records) we do not prune lookups. It was assumed this would be positive as it _might_ allow things like restoring a record in the future, or analysing ID stability over time from the lookup table.

### What happened here?

The dataset [ingestion history](https://registry.gbif.org/dataset/5a3b50fa-c882-4129-9405-38e54c0a73f3/ingestion-history) shows 27 crawls and with data changing at crawl attempts 2, 5, 11, 15, 19 and 23. The important parts are:

| attempt | _triplet_  unique | occurrenceID unique | Verbatim records | Interpreted records
|:-:|:-:|:-:|:-:|:-:|
| 2 | Y | Y | 803,169 | 803,169 |
| 5 | N | Y | 804,068 | 804,068 |
| 11 | N | Y | 805,324 | 805,324 |
| 15| N | Y | 805,802 | 805,802 |
| 19 | N | Y | 806,417 | 806,417 |
| 23 | Y | Y | 806,415 | 3,247 |

Looking at the logs for crawl 23 we see that we discard many records, logging:
```
ERROR [01-15 14:21:47,666+0000] [pool-8-thread-1]  org.gbif.pipelines.fragmenter.common.Keygen: Found inconsistent occurrence keys in looking up unique identifiers:[5a3b50fa-c882-4129-9405-38e54c0a73f3|01c2a4e5-eee9-43c5-a2e8-da562711e9b8]=[2854020559][5a3b50fa-c882-4129-9405-38e54c0a73f3|PERTH|PERTH|PERTH 3994120|null]=[2827968094]
```

Deciphering this, it is saying that it used both the occurrenceID and _triple_ (since it is unique in this crawl) and found:

1. occurrenceID 01c2a4e5-eee9-43c5-a2e8-da562711e9b8 has GBIF ID 2854020559
2. PERTH / PERTH / PERTH 3994120 has GBIF ID 2827968094

I wrote a quick [diagnostic tool](https://github.com/gbif/pipelines/commit/6c18fa85d4da775608b9bc70e579a2b900fcf802) to log the triple and occurrenceID values for each crawl. For these IDs we see:

```
Attempt	institutionCode	collectionCode	catalogNumber	occurrenceID
2	PERTH	PERTH	PERTH 3994120	58e04de8-e994-4428-a0a4-7f22668ff8a1
5	PERTH	PERTH	PERTH 3994120	01c2a4e5-eee9-43c5-a2e8-da562711e9b8
11	PERTH	PERTH	PERTH 3994120	01c2a4e5-eee9-43c5-a2e8-da562711e9b8
19	PERTH	PERTH	PERTH 3994120	01c2a4e5-eee9-43c5-a2e8-da562711e9b8
23	PERTH	PERTH	PERTH 3994120	01c2a4e5-eee9-43c5-a2e8-da562711e9b8
```

Putting this all together, this is what happened:

1. Crawl 2 had unique triplets, so created lookups for the triplet and occurrenceID 
2. Crawl 5 did not have unique triplets, used all new occurrenceIDs resulting in new GBIF IDs being issued for all records (and lookups made)
3. Crawl 11, 19 added a few records but continued like 5
4. Crawl 23 had unique triplets, but found that "Perth 3994120" pointed to the ID created in crawl 2, while the occurrenceID pointed to the one created in 5. This is because we don't delete old lookups.

This is one scenario where lookups and IDs can become corrupted, and we need to be mindful to not make decisions only based on this case. 

Moreover, while we have fixed the dataset manually this will repeat again in the next crawl of the dataset while those old lookups remain (and while catalogNumbers remain unique).

**Comment by timrobertson100** [comment]
> Moreover, while we have fixed the dataset manually this will repeat again in the next crawl of the dataset while those old lookups remain (and while catalogNumbers remain unique).

I have discussed the cause of the `occurrenceID` change between attempt 2 and 5 with @djtfmartin for this dataset - we believe they were issued unintentionally as the AVH dataset was split and should always have been the ones seen in crawl 5. The IDs for this dataset are issued within the ALA infrastructure and there is no foreseeable reason they would ever be resurrected.

We will remove those occurrence IDs from the lookup so that this dataset will continue indexing normally in the future.

I'll leave this issue open as we consider improvements to ID management.

**Comment by MattBlissett** [comment]
Attempt 228 of this dataset has a similar problem, with 64 duplicate gbifIds from lookups: https://registry.gbif.org/dataset/1e61b812-b2ec-43d0-bdbb-8534a761f74c/ingestion-history

However, there are no "Found inconsistent occurrence keys in looking up unique identifiers" in logs.gbif.org. (And the datasetKey tag is missing from these log entries; it would be useful to add it.)

See helpdesk email.

**Comment by muttcg** [comment]
> Attempt 228 of this dataset has a similar problem, with 64 duplicate gbifIds from lookups: https://registry.gbif.org/dataset/1e61b812-b2ec-43d0-bdbb-8534a761f74c/ingestion-history
> 
> However, there are no "Found inconsistent occurrence keys in looking up unique identifiers" in logs.gbif.org. (And the datasetKey tag is missing from these log entries; it would be useful to add it.)
> 
> See helpdesk email.

It is a Spark job, information about keys is a specific executor log, probably possible (we did a similar thing before for Spark) to tweak logs settings and pass to ELK more data, but needs some research
