### ISSUE TITLE
Remove lookups for a specific attempt

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#465]
This is the outcome of the diagnostic on https://github.com/gbif/pipelines/issues/463

Attempt 2 created lookups for triplets and occurrenceIDs for the dataset, which has resulted in occurrenceIDs in the lookups that now cause us issue and need to be removed.

I can see two ways that we may tackle this:

1. Extract the occurrenceIDs from the DwC-A in attempt 2, and for those that do not exist in the most recent attempt (none should, but we should check) remove the lookups.

2. Create a job which extracts the GBIF ID, occurrenceID and triplet from the latest interpreted avro file, deletes all lookups for the dataset, and then creates new entries with only the correct values based on the current index state.

The benefit of doing option 2 would then be a robust, repeatable way to clean all lookups for a specific dataset to ensure they reflect only what the current index holds.

Thoughts @MattBlissett @muttcg  ?

**Comment by muttcg** [comment]
Run cli with one of the following collision flags:

- Delete triplet ID
- Delete occurrenceID
- Delete lower ID
- Delete higher ID

Process extracts all gbifID for the latest attempt and for gbifIDs with collisions apply the flag action

**Comment by timrobertson100** [comment]
I think that would give good flexibility. 

The "delete all" option It does mean that lookups for things that aren't in the latest attempt will hang around and may cause issue in the future. That's why I did the truncate and repopulate approach in my 2. above. 

My intuition is that ensuring a lookup that is consistent and only holding data from the latest attempt would be the most common use.
