### ISSUE TITLE
DwC-A: inconsistent column mismapping, seemingly ok at source

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/pipelines#481]
- dataset: https://www.gbif.org/dataset/963a6b96-4d22-4428-86e4-afee52cf4a8e
- error flagged: https://www.gbif.org/occurrence/search?dataset_key=963a6b96-4d22-4428-86e4-afee52cf4a8e&issue=COUNTRY_INVALID
- apparent issue: lifeStage erroneously also mapped to countryCode

At the time of checking, the source file mapping and data behind the registered endpoint in the archive appear correct.
![image](https://user-images.githubusercontent.com/13435656/108352419-1c3bd780-71e7-11eb-922a-8baeba6ab29a.png)

The fragment accessible behind the occurrence records duplicate the lifeStage value under countryCode: e.g. https://api.gbif.org/v1/occurrence/3017376326/fragment

The publisher reports that this error seems to disappear and reappear, and wonder whether this might be caused by data processing.

A re-crawl fixed the issue at gbif.org. Archive history at source still under evaluation.

**Comment by muttcg** [comment]
I checked the current and previous archives, and there is a metadata issue, don't know how this happened, but some archives contain duplicate in term to csv mapping:
<img width="662" alt="Screenshot 2021-02-18 at 12 59 28" src="https://user-images.githubusercontent.com/11806077/108354451-bf8dec00-71e9-11eb-8122-85da4f44bec9.png">

**Comment by MattBlissett** [comment]
This is valid DWCA, as it's possible that a field can map to multiple terms, e.g. eventDate and verbatimEventDate, or catalogNumber and occurrenceID.

(Obviously wrong in this case, but that is why the validator doesn't block it.)

Also, column 38 should be `http://rs.tdwg.org/dwc/terms/occurrenceStatus`.

**Comment by ahahn-gbif** [comment]
Concerning host and installation: the archive is not generated through an IPT; the linkage to an IPT installation that was deleted in 2012 was a human error in registration.
