### ISSUE TITLE
Migrating occurrenceIDs

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#499]
This issue serves to capture a mechanism employed to migrate occurrenceID (to CETAF style IDs) and triplets for a dataset while maintaining GBIF IDs. This is logged here for reference only, and we will spec and implement a better process.

The publisher was guided through a 4 step process:

1. Map your catalogNumber to the same as you use in your current occurrenceID and publish the dataset. Let it index and verify IDs remain the same and catalogNumbers were updated
   They MUST(!) be unique within the dataset which is why I suggest to use the current occurrenceID

2. Modify the occurrenceID to your new CETAF format. Publish in GBIF and verify that IDs were not changed
   In this publication we will recognize the unique combination in institutionCode, collectionCode and catalogNumber and create the mapping to the new occurrenceID

3. Now instruct GBIF to delete the old mappings for the catalogNumbers so only the new occurrenceID mapping remains
   After this, we’ll only know about the new CETAF format ID and how that maps to a GBIF ID.

4. Update the catalogNumber to the new value mapping and republish

During step 3, I ran:

```
# extract all the lookups
cd /tmp
/usr/local/bin/lookup-occurrence-keys-for-dataset 013860c3-aebd-4c2f-9a0c-dfa26722cc93 > /tmp/sant-cetaf.txt

# remove the preamble
cat sant-cetaf.txt | cut -c 41- > /tmp/sant-cetaf2.txt

# extract only the occurrenceIds and triplets
cut -f1 < /tmp/sant-cetaf2.txt > /tmp/sant-cetaf3.txt

# remove everything that isn't a CETAF style ID
cat /tmp/sant-cetaf3.txt| grep -v "http://" > /tmp/sant-cetaf4.txt    

# extract the occurrenceIDs
cat /tmp/sant-cetaf4.txt | grep -v '|' > /tmp/sant-cetaf-oldOccs.txt  
 
# extract the old triplets
cat /tmp/sant-cetaf4.txt | grep '|' > /tmp/sant-cetaf-old-triplets.txt
 tr '|' '\t' < /tmp/sant-cetaf-old-triplets.txt > /tmp/sant-cetaf-old-triplets2.txt

# add headers to those files to make them valid DwC-A
(manually using text tool, and zip)

java -jar diagnostics-2.8.1-shaded.jar --dataset-key 013860c3-aebd-4c2f-9a0c-dfa26722cc93 \
--input-source /tmp/triplets.txt.zip --zk-connection c4zk1.gbif-uat.org,c4zk2.gbif-uat.org,c4zk3.gbif-uat.org \
--lookup-table uat_occurrence_lookup --counter-table uat_occurrence_counter \
--occurrence-table uat_occurrence --deletion-strategy triplet

java -jar diagnostics-2.8.1-shaded.jar --dataset-key 013860c3-aebd-4c2f-9a0c-dfa26722cc93 \
--input-source /tmp/occurrenceIDs.txt.zip  --zk-connection c4zk1.gbif-uat.org,c4zk2.gbif-uat.org,c4zk3.gbif-uat.org \
--lookup-table uat_occurrence_lookup --counter-table uat_occurrence_counter \
--occurrence-table uat_occurrence --deletion-strategy occurrenceID
```

**Comment by timrobertson100** [comment]
Closing this issue, as it's kept here only to refer to as we spec a new process.

**Comment by dgasl** [comment]
>This is logged here for reference only, and we will spec and implement a better process.

Thanks for this @timrobertson100 
Is this better documented or with a more upated procedure somewhere else now?

@dgasl
(tagging @abubelinha who is also interested in this)

**Comment by abubelinha** [comment]
Just in case anybody else interested, this was helpdesk answer (2022.09.23):

> We now have an internal tool to handle this type of situation. If you send us a table of the old and new occurrenceID for each record, we will be able to make the change on our side.
> 
> You will then be able to publish a new update.
