### ISSUE TITLE
Request for more filters

### ISSUE THREAD

**Issue by MortenHofft** [gbif/pipelines#515]
Feature request based on https://github.com/gbif/hosted-portals/issues/56#issuecomment-826974495 from @tucotuco

The VertNet group is asking for filters (and download support) for following fields:

* fieldNumber (only in index as verbatim blob) https://github.com/gbif/pipelines/issues/514
* preparations (currently indexed as keywords) https://github.com/gbif/pipelines/issues/634
* sex (currently indexed as keywords)
* startDayOfYear (currently indexed as shorts)
* endDayOfYear (currently indexed as shorts)

**Comment by tucotuco** [comment]
The other on the list of interest, which aren't yet indexed, are:

- fieldNumber
- preparations
- higherGeography
- island
- islandGroup
- georeferencedBy
- higherClassification
- previousIdentifications

We have valid uses for all of these that can not be satisfied in any other way, but would be happy to have support for as many as you can muster. I have sorted the list from (our) highest priority at the top to lowest priority at the bottom.

**Comment by thomasstjerne** [comment]
As discussed at the standup:
Please make `associatedSequences` searchable. This field is mostly used for various INSDC accessions (sequences, samples etc).
Publishers often put full URIs like this https://www.gbif.org/occurrence/4422649838 and https://www.gbif.org/occurrence/4152824550

In these cases it would be nice if searching for the plain accession e.g. `OQ442330` would work.

`associatedSequences` sometimes contains multiple values, pipe-separated like https://www.gbif.org/occurrence/4058902638

**Comment by muttcg** [comment]
Deployed to PROD
