### ISSUE TITLE
Question: alternate codebases for processing codes

### ISSUE THREAD

**Issue by skybristol** [gbif/pipelines#519]
I'm curious about whether or not you all are thinking about an extension on the architecture that would support other communities introducing new processing codes in a microservices kind of context to the pipeline. From the traffic here, it looks like this process is now well along as (maybe) the main method for processing source data through various "enhancers" and getting things into the GBIF indexes. That's awesome!

Many of us in other communities have existing DarwinCore-based processing logic already built in R and Python, at least. It would be really nice to bring those proven codes directly into the framework as opposed to rewriting in Java. Avro provides a nice common intermediary that we can operate against with other languages.

Substantively, the two main areas of community or region specific need have to do with location and species traits that extend beyond what GBIF is already taking care of currently. For location, we need to put a number of pieces of information together to align with ecologically significant areas of interest like our hydrographic network for freshwater species in the US. For traits, we similarly need to bring together multiple pieces of information from source data to determine if certain traits can be applied like planktonic life stage for some marine species observations. We would, of course, want to contribute new logic and thinking to other existing modules where appropriate, but some of these needs are going to introduce something completely new. We're doing this kind of stuff now across the biodiversity research community, often pulling data from GBIF, running our processes wherever, and then putting out a GBIF derivative with our particular contributions. It would be great from a computational and data flow efficiency standpoint as well as value adds to the community at large, if we could start contributing that intellectual capital directly back to the "mothership."

From the basic depiction of the architecture, I'd think that alternative processing tools working against verbatim Avros could generate some kind of specific Avros fed into the indexing process. Those would need to be introduced to the processing pipeline through some kind of a microservices kind of architecture such as one or another Lambda function implementation.  I'd also assume that we'd want some kind of community governance on introducing these kinds of new capabilities, and of course, some solid testing and acceptance at the technical level by GBIF core operators. GitHub and CI/CD should be able to help.

So, the architecture here looks great. Where are we in terms of opening out to a more distributed community contribution process?

**Comment by timrobertson100** [comment]
Thank you, @skybristol 

It's reassuring to hear you like the architecture and see the potential for growth. It's certainly the intention for GBIF to expand.

You touch on a lot of areas here. I'll offer a few initial comments and give a proposal for _what next_.

We've recently expanded this project to align the GBIF and ALA codebases. The objective was to bring better consistency in data handling, increase our collective capacity and start the process of maturing our working practices to accommodate "external" groups. We will still run on separate infrastructure initially, but the potential increases for us to share more services. This approach also prompts us to start discussions around shared governance models and options (e.g. Apache  which some of us participate in)

There are operational aspects to consider in your proposal. GBIF grows at 1M records per day and has performance targets to hit (e.g. >250k records per second to enable feature deployment that requires a full reprocessing), have the overheads/restrictions associated with en-premise infrastructure (e.g. network access, security, and out-of-hours support etc). We use some microservices, but our throughput needs often require we deploy scalable caches (HBase for us) in front of them and then have cache invalidation and seeding headache. As a small team, we need to be realistic of what can be accommodated under the current models, or look to change them. 

Our choice of Beam as a processing framework was influenced by its promise of portability (execution frameworks like Spark, and Java/Python support). We haven't accommodated Python work, but it would be good to explore options. 

We've just started our track of getting monthly snapshots of GBIF on cloud providers. You'll find a view of GBIF on the [Microsoft Planetary Computer](https://planetarycomputer.microsoft.com/catalog) so you can run in Azure, and we hope to provide cloud-native views in AWS, Google and possibly others shortly. One option could be to consider a hybrid-cloud approach where GBIF process the core, with enhancements are easily possible using the snapshots.

We'd be keen to explore possibilities further, but propose we continue the discussion openly on the [GBIF Discourse forum](https://discourse.gbif.org/) so it gets the attention it deserves. I'm also happy to arrange a call between the teams, to help identify some concrete use cases we might explore.

I'd prefer to close this issue and continue the discussion on Discourse. Does that seem reasonable, please? You are always welcome to discuss directly with me (trobertson@gbif.org).

**Comment by skybristol** [comment]
Thank you, @timrobertson100. Sounds great! I'm happy to pick up the discussion in the discourse forum.
