### ISSUE TITLE
Wrong message type when metadata is updated

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#535]
Registry sends the wrong type for big datasets which causes OOM
What to check: Registry must send messages to pipelines-balancer
https://registry.gbif.org/dataset/aea17af8-5578-4b04-b5d3-7adf0c5a1e60/ingestion-history

**Comment by fmendezh** [comment]
@muttcg I looked into that but I don't see any significant changes in that code, what type is expected by pipelines?
