### ISSUE TITLE
Map basisOfRecord *DNA values to MaterialSample

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#538]
As requested by @elywallis [here](https://github.com/gbif/gbif-api/issues/84#issuecomment-853619658) we should map `basisOfRecord` values of `environmentalDNA` and `genomicDNA` to `MaterialSample` instead of `UNKNOWN`.

This is to improve the filtering capabilities as an interim solution, while the wider discussion is ongoing.

**Comment by MattBlissett** [comment]
See https://github.com/gbif/parsers/blob/master/src/main/resources/dictionaries/parse/basisOfRecord.tsv#L90 for the new mapping, I have added `environmental dna` and `genomic dna` (casing, spaces, _ etc don't matter).

We currently have this many occurrences for these values:

```
1171901 UNKNOWN EnvironmentalDNA
118835  UNKNOWN GenomicDNA
```

No others have "DNA" in the provided basis of record, @elywallis, are you aware of any more values we should map to MaterialSample?

**Comment by marcos-lg** [comment]
Closing it as it's done.
