### ISSUE TITLE
Copy https://github.com/gbif/occurrence/tree/master/occurrence-parser in the pipelines project

### ISSUE THREAD

**Issue by fmendezh** [gbif/pipelines#54]
occurrence-parser contains all the code to handle XML protocols (Digir, Tapir and Biocase), it must be copied to the pipelines project, clean dependencies, this projects depends on occurrence-common and gbif-common and we also have to evaluate if we should move some code form those projects too

**Comment by timrobertson100** [comment]
Replaced by #60
