### ISSUE TITLE
Define and implement a more flexible duplicate records policy 

### ISSUE THREAD

**Issue by fmendezh** [gbif/pipelines#553]
Currently, the occurrence indexing platform tries to index all the valid (records with unique IDs) found in a source dataset, which can make it hard to find later on those issues once the dataset is indexed or not indexed at all.

See, for example, this issue: https://github.com/gbif/portal-feedback/issues/3495 

As an initial proposal for a better approach for those situations must:

1. Pause or stop the indexing of the archive when a certain percentage of duplicate records are detected.
2. Notify the GBIF Helpdesk of the issue and provide useful information for further diagnosis.
3. Perform a comparison against currently indexed data to estimate a sensible decrease in records.

**Comment by MattBlissett** [comment]
I wondered why the crawler-dwca-validator didn't complain about this dataset.

Unique `coreid` values are only required by the [specification](https://dwc.tdwg.org/text/#212-elements) if extensions are used, so in this case we ought to be ignoring this column and using e.g. dwc:occurrenceId (or a triple) instead.

```
org.gbif.crawler.dwca.validator.ValidatorService: 7fd2f6e2-f762-11e1-a439-00145eb45e9a
Finished validating DwC-A for dataset [7fd2f6e2-f762-11e1-a439-00145eb45e9a], valid? is [true].
Full report [DwcaValidationReport[
  datasetKey=7fd2f6e2-f762-11e1-a439-00145eb45e9a,
  occurrenceReport=OccurrenceValidationReport[
    checkedRecords=50240, 
    uniqueTriplets=1, 
    recordsWithInvalidTriplets=0, 
    uniqueOccurrenceIds=50240, 
    recordsMissingOccurrenceId=0, 
    allRecordsChecked=true,  
    invalidationReason='null', 
    valid=true], 
  genericReport=null, 
  invalidationReason='null']
]
```

**Comment by timrobertson100** [comment]
This appears to be captured in the ID stability group #677 and #676  in particular
