### ISSUE TITLE
Investigate Date Ranges support in ElasticSearch/Solr

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#56]

**Comment by fmendezh** [comment]
DarwinCore allows the usage of date ranges in multiple terms (see for example: http://rs.tdwg.org/dwc/terms/#eventDate), new date parsing libraries must support identification of date ranges which later  must be stored in Avro files and indexed in  search engines such as Solr or ElasticSearch, the scope of this task is to evaluate different options of how date ranges and simple dates can be stored and later indexed in ES/Solr. 
Some questions that we have at this moment are:
1. Do we need 2 fields in ES/Solr to store dates: one for simple dates and another for date ranges?
2. How can we supply a uniform interface to query a single DwcTerm regardless of how this is stored in ES/Solr?

References:

https://wiki.apache.org/solr/DateRangeField
https://www.elastic.co/guide/en/elasticsearch/reference/current/range.html
