### ISSUE TITLE
Missing issues in HDFS view array

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#566]
[This download](https://www.gbif.org/occurrence/download/0315027-200613084148143) illustrates the problem where records are correctly filtered in ES based on issues, but are not in the occurrence Hive table issues array.

```
SELECT count(*) FROM prod_h.occurrence 
WHERE array_contains(issue,'INSTITUTION_MATCH_FUZZY') OR array_contains(issue,'COLLECTION_MATCH_FUZZY')

> 0 records
```

Please check all issue flags for this, but at least these two are missing.

**Comment by MattBlissett** [comment]
The issues are actually missing in the Pipelines HDFS view:

```
hdfs dfs -cat /data/hdfsview/occurrence/83ae84cf-88e4-4b5c-80b2-271a15a3e0fc_245-00000-of-00001.avro | java -jar /usr/local/bin/avro-tools.jar tojson - | jq .issue | grep -e string | sort | uniq -c
```

Multimedia issues are missing too.

**Comment by MattBlissett** [comment]
Almost 20,000 datasets will need re-hdfs-viewing when this is deployed.

`https://api.gbif.org/v1/occurrence/search?issue=INSTITUTION_COLLECTION_MISMATCH&issue=INSTITUTION_MATCH_NONE&issue=COLLECTION_MATCH_NONE&issue=INSTITUTION_MATCH_FUZZY&issue=COLLECTION_MATCH_FUZZY&issue=POSSIBLY_ON_LOAN&issue=DIFFERENT_OWNER_INSTITUTION&issue=AMBIGUOUS_COLLECTION&issue=AMBIGUOUS_INSTITUTION&issue=MULTIMEDIA_URI_INVALID&issue=MULTIMEDIA_DATE_INVALID&limit=0&facet=datasetKey&facetLimit=50000`

**Comment by MattBlissett** [comment]
> Please check all issue flags for this, but at least these two are missing.

Confirming it is only these issues that are missing:

```
AMBIGUOUS_COLLECTION
AMBIGUOUS_INSTITUTION
COLLECTION_MATCH_FUZZY
COLLECTION_MATCH_NONE
DIFFERENT_OWNER_INSTITUTION
INSTITUTION_COLLECTION_MISMATCH
INSTITUTION_MATCH_FUZZY
INSTITUTION_MATCH_NONE

MULTIMEDIA_DATE_INVALID
MULTIMEDIA_URI_INVALID
```
