### ISSUE TITLE
Institution and collection Code and ID not interpreted

### ISSUE THREAD

**Issue by gbif-portal** [gbif/pipelines#571]
**Institution and collection Code and ID not interpreted**

This specimens should be linked to GRSciColl or flagged but it isn't.

This is the corresponding GRSciColl entry: https://registry.gbif.org/institution/40452d31-2f91-460a-a624-7ecf27eac71e

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/8df59ae3de7e438e84050f31f69c8a54:a445d963dfc78edd8677097fd61ce33e85d96dc6a45c8f49329adaea26fb1d2ad4068eeb33f2f1420ae9936affeda858da7b426d21dc4ba5a3fcf36b79f0b61a)
System: Safari 14.1.1 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/2541250661
Window size: width 1339 - height 793
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-09T12:47:04.881Z',to:'2021-07-09T12:53:04.881Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-09T12:47:04.881Z',to:'2021-07-09T12:53:04.881Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 2814930a-3b93-48d6-b887-00979481ac9e
publishingOrgKey: 75642970-f855-11dd-8235-b8a03c50a862
Network keys: 17abcf75-2f1e-46dd-bf75-a5b21dd02655 
Node handles: @mnhn-paul

**Comment by mnhn-paul** [comment]
It actually seems to affect the records from this entire dataset: https://www.gbif.org/dataset/2814930a-3b93-48d6-b887-00979481ac9e
The collection and Institution does not seem to be flagged.
