### ISSUE TITLE
RBGE living plant occurrences dropped to zero

### ISSUE THREAD

**Issue by dshorthouse** [gbif/pipelines#573]
@timrobertson100 @MattBlissett @Cubey0
See https://www.gbif.org/dataset/7adf20e0-c955-11de-95c0-b8a03c50a862

**Comment by timrobertson100** [comment]
I suggest we should implement a safety check that stops the processing attempt and alerts managers, if >N% of records will be dropped (e.g. 25%)

**Comment by dshorthouse** [comment]
Yes, please! That would go a long way to helping collection managers & me too when triggering a big download. I have no practical way to learn of big losses like this one until after I've downloaded and done some initial processing.

**Comment by muttcg** [comment]
1) meta.xml core term is `rowType="http://rs.tdwg.org/dwc/xsd/simpledarwincore/SimpleDarwinRecord"` we expect it to be `rowType="http://rs.tdwg.org/dwc/terms/Occurrence"`, I can see that alternative names for Occurrence can be also `"DarwinCore", "SimpleDarwinCore"`, our term parser recognizes the main core term as unknown, so I am not sure it is a term parser issue or wrong rowType in the meta.xml
2) I will add an extra check for this case
3) I changed rowType to `rowType="http://rs.tdwg.org/dwc/terms/Occurrence"` as a queck fix to make data available

**Comment by Cubey0** [comment]
Roger Hyam said 

"Well I changed that our dump so it is now rowType="http://rs.tdwg.org/dwc/terms/Occurrence"

**Comment by muttcg** [comment]
Fix in PROD
