### ISSUE TITLE
Interpret new/updated Darwin Core terms establishmentMeans, degreeOfEstablishment and pathway

### ISSUE THREAD

**Issue by MattBlissett** [gbif/pipelines#581]
The Darwin Core term establishmentMeans has been updated with a standard vocabulary.

Two new Darwin Core terms, degreeOfEstablishment and pathway, also have vocabularies specified by Darwin Core.

We currently use the [establishmentMeans](https://github.com/gbif/gbif-api/blob/dev/src/main/java/org/gbif/api/vocabulary/EstablishmentMeans.java) enumeration. This can be abandoned (for occurrences, it's still used by ChecklistBank), similar to what happened for LifeStage.

The [new vocabulary](https://rs.gbif.org/sandbox/vocabulary/dwc/establishment_means_2021-08-22.xml) is already prepared in the registry: https://registry.gbif.org/vocabulary/EstablishmentMeans (some translations will be done later: https://github.com/gbif/vocabulary/issues/93).

- [x] Interpret dwc:establishmentMeans using the vocabulary from the vocabulary server, and use a String type.

We also have a vocabulary for degreeOfEstablishment: https://registry.gbif.org/vocabulary/DegreeOfEstablishment

And a vocabulary for pathway is ready for testing in UAT: https://github.com/gbif/vocabulary/issues/95 — @marcos-lg, could you export/copy/however this into production, with the name "Pathway".  It will then be at  https://registry.gbif.org/vocabulary/Pathway

- [x] (@marcos-lg) Copy/import/however the PathwayTest1 vocabulary from UAT to "Pathway" in production.
- [x] Interpret dwc:degreeOfEstablishment and dwc:pathway using the vocabulary from the vocabulary server, a String type, and add to the search index and downloads.  (Insert the new columns in downloads after establishmentMeans.)

https://github.com/gbif/portal-feedback/issues/3257 requests this improvement.

https://ipt.gbif.org/resource?r=2021-dwc-updates isn't yet ready, but something like it will be needed to test publication of these terms from the IPT.

**Comment by MattBlissett** [comment]
@muttcg, @fmendezh, @marcos-lg, I think implementation on this can start.

**Comment by marcos-lg** [comment]
Pathway vocabulary imported to PROD: https://registry.gbif.org/vocabulary/Pathway

Note that when ready all the vocabularies have to be released.

**Comment by muttcg** [comment]
deployed to prod
