### ISSUE TITLE
Recognize new Darwin Core terms

### ISSUE THREAD

**Issue by MattBlissett** [gbif/pipelines#583]
The recent update to Darwin Core brought some new terms.

#581, #582 handle the more complicated cases.

* http://rs.tdwg.org/dwc/terms/verticalDatum – I suggest no parsing or searching at first; perhaps we can normalize the elevation/depth terms using this datum later.  It should still be in downloads.
* http://rs.tdwg.org/dwc/terms/verbatimIdentification – no parsing required, potentially useful for searching.

<details><summary>Excluded</summary>
* ~http://rs.tdwg.org/dwc/terms/georeferenceVerificationStatus – no interpretation required, not required for searching~
* ~http://rs.tdwg.org/dwc/terms/subfamily http://rs.tdwg.org/dwc/terms/infragenericEpithet http://rs.tdwg.org/dwc/terms/cultivarEpithet – supporting these will need changes to name matching.  Until then, I think we need to keep them in the verbatim occurrence only.~
* Later ~http://rs.tdwg.org/dwc/terms/relationshipOfResourceID – nothing to do (ignore) for occurrences for now. (Not part of the Occurrence core, we aren't interpreting the resource relationship extension.)~
</details>

**Comment by tucotuco** [comment]
In case it matters, georeferenceVerificationStatus isn't new. It was just rearranged to be under Occurrence instead of under Location.

**Comment by MattBlissett** [comment]
Thanks John, in that case there's probably nothing to be done for that term.

**Comment by MattBlissett** [comment]
@muttcg, verticalDatum and verbatimIdentification can be added, as above.

https://github.com/gbif/ipt/issues/1532 links some test datasets present in UAT.

**Comment by MattBlissett** [comment]
If it helps for controlling index size, verbatimIdentification probably isn't useful to search alone at this point. It will often duplicate the rest of the identification.

**Comment by muttcg** [comment]
deployed to prod
