### ISSUE TITLE
IndexRecordToDwcaPipeline - archives fail GBIF validation

### ISSUE THREAD

**Issue by djtfmartin** [gbif/pipelines#585]
The archives produced by [IndexRecordToDwcaPipeline](https://github.com/gbif/pipelines/blob/dev/livingatlas/pipelines/src/main/java/au/org/ala/pipelines/beam/IndexRecordToDwcaPipeline.java)

More info here: https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/505

There are two identified problems:

1) Invalid meta.xml - problem with the definition of the Multimedia extension

```
  <extension encoding="UTF-8" linesTerminatedBy="\r\n" fieldsTerminatedBy="," fieldsEnclosedBy="&quot;" ignoreHeaderLines="0" rowType="http://rs.gbif.org/terms/1.0/Multimedia">
    <files>
      <location>image.csv</location>
    </files>
    <coreid index="0"/>
    <field index="0" term="id"/>
    <field index="1" term="http://purl.org/dc/terms/identifier"/>
```    

The following line should be removed

```
    <field index="0" term="id"/>    
```    

2) Escaping of fields in the occurrence.csv

Here the file contains JSON in `dynamicProperties` field which breaks the CSV escaping of comma and " delimitation. Similarly fields containing `"AM".` become `""AM"."` which breaks the file.
A workaround for this might be to switch to tab-delimited rather than comma and quotes

**Comment by timrobertson100** [comment]
Examples of errors observed are in the history of https://registry.gbif-uat.org/dataset/ba11ce97-648b-4213-9221-ecab3f0519fc/ingestion-history

**Comment by djtfmartin** [comment]
Work for this is merged now.
