### ISSUE TITLE
IdentifiedByIds do not filter out empty strings

### ISSUE THREAD

**Issue by MortenHofft** [gbif/pipelines#590]
Example
https://api.gbif.org/v1/occurrence/2867560301/fragment

The publisher provides `"identifiedByID": "| https://www.wikidata.org/wiki/Q21338542"`
That isn't the best data, but we could also do better in interpretation

We interpret
```
"identifiedByIDs": [
{
"type": "OTHER"
},
{
"type": "WIKIDATA",
"value": "https://www.wikidata.org/wiki/Q21338542"
}
],
```

**Comment by dagendresen** [comment]
Also notice that the PID for Reidar Elven is reported as the [Wikidata URL](https://www.wikidata.org/wiki/Q21338542), while the [Wikidata concept URI](http://www.wikidata.org/entity/Q21338542) would be better, and still his [ORCID ID](https://orcid.org/0000-0003-3375-7408) would be even better...

... which is on the GBIF Norway work plan to try to fix, through [building an annotator into the node information infrastructure](https://github.com/gbif-norway/helpdesk/issues/68).

**Comment by rukayaj** [comment]
What's the correct way to show that the first agent name in the identifiedBy list does not have an ID, but the subsequent one does? I think that is what is happening here.

**Comment by dshorthouse** [comment]
@rukayaj re: ordering of list of URIs. We thought carefully about this when the `identifiedByID` and `recordedByID` terms were created. The recommended best practices states on https://dwc.tdwg.org/terms/#dwc:identifiedByID states, "If a list is used, the order of the identifiers on the list should not be assumed to convey any semantics." And so, I'd strip out all the unknowns that seem to be meant to convey semantics (i.e. ordering). None can be assumed.
