### ISSUE TITLE
Smithsonian records missing from large download index

### ISSUE THREAD

**Issue by dshorthouse** [gbif/pipelines#595]
Many records from https://www.gbif.org/dataset/821cc27a-e3bb-4bc5-ac34-89ada245069d are present/visible from the front-end but missing from the large download index. One such record is gbifID 1317220352, which was present prior to latest re-harvest Sep 22.

Apologies if this is not the appropriate place for such a ticket @MattBlissett @timrobertson100 but am uncertain if this is unusual behaviour for the pipeline, the expected 24-48hr lag in data stores post-harvest, or other. The fact that this particular gbifID above was present prior to Sep 22 in the large data store index and not present now yet visible on the website struck me as peculiar.

**Comment by muttcg** [comment]
The record is present in the storage systems, please use gbif.org portal to create issues and link the download identifier
