### ISSUE TITLE
Living Atlas integration tests fail on Jenkins

### ISSUE THREAD

**Issue by djtfmartin** [gbif/pipelines#629]
@muttcg has temporarily disabled them

https://github.com/gbif/pipelines/commit/eddd9392ea094527b331ed7a74994e241317b802

**Comment by muttcg** [comment]
Started to work again, reopen if needed

**Comment by muttcg** [comment]
@djtfmartin Unfortunately, I have to disable IT tests for ALA module, they get stuck(hours and hours) and it might be related to biocache solr docker image, so be aware of that.
