### ISSUE TITLE
No mapping of abcd:utmDatum or any "geodetic datum" term from abdc archives? 

### ISSUE THREAD

**Issue by jhnwllr** [gbif/pipelines#632]
https://github.com/gbif/portal-feedback/issues/603

It appears that we don't interpret any geodetic datum terms from **abdc archives**. 
https://github.com/gbif/pipelines/blob/dev/tools/archives-converters/src/main/resources/mapping/indexMapping_abcd_1_2.properties

https://abcd.tdwg.org/terms/#utmDatum

It appears all abdc archives are interpreted as **WGS84**.

**Comment by muttcg** [comment]
Added new mapping and deployed to PROD
