### ISSUE TITLE
validation of structurally wrong archive: a bit more verbose feedback would be nice

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/pipelines#633]
label: validator 
(sorry, I don't seem to have permissions to set labels here)

https://www.gbif-uat.org/tools/data-validator/03c11c8e-9ca4-4bac-881b-b6ff04bf241e

The old validator provides some minimum feedback for cases where the archive content does not match the meta.xml definition, e.g.:
![image](https://user-images.githubusercontent.com/13435656/145434355-86a1e81f-c763-4df8-8921-2fd16e247c98.png)
In a test of the same dataset in the new validator, validation seems to fail after a rather long time (>30min) with "The system is currently not able to process your request. (...)", and on page reload appears to be still running.

The test archive used here (helpdesk case, 9.12.21) has a typo in the meta.xml file, misspelling "occurence.csv" for "occurrence.csv". The error message in the current validator (screenshot) is helpful to identify why the archive is considered wrong format due to this. In the new one, the validation seems to still be running after 1h.

**Comment by muttcg** [comment]
@ahahn-gbif Fix was deployed to UAT, please check the result https://www.gbif-uat.org/tools/data-validator/30d8fe1f-a60a-406e-945e-3515fdb4132d

**Comment by ahahn-gbif** [comment]
Perfect, thank you!

I don't have permissions on the repo to comment or close – this issue can be closed now :)

Best,
Andrea
