### ISSUE TITLE
Support new basis of record Material Citation, deprecate Literature

### ISSUE THREAD

**Issue by MattBlissett** [gbif/pipelines#635]
The new DWC basis of record `MaterialCitation` should be added to the enumeration.

The old `Literature` value should be deprecated, and can be removed from display by the portal. (To allow existing download filters to be deserialized it must remain in the enumeration.)

Current values that parse to `Literature` should instead parse to `MaterialCitation`.

Based on searching source code, this will require changes to:

- [x] pipelines,
- [x] gbif-api, 
- [x] parsers, 
- [x] download-query-tools, 
- [x] rgbif, 
- [ ] pygbif, 
- [x] gbif-web, 
- [x] portal16, 
- [ ] analytics, 
- [x] maps, 
- [x] occurrence, 
- [ ] the AI For Earth 
- [ ] Google open datasets
- [ ] and AWS open datasets documentation, 
- [ ] and probably documentation on gbif.org.

**Comment by muttcg** [comment]
deployed to prod
