### ISSUE TITLE
Is it possible to avoid interpretation of institutionCode when the basis OfRecord is MaterialSample?

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/pipelines#637]
Hi,

We have a [dataset](https://www.gbif.org/es/dataset/b9461088-6f97-49b0-8f76-17e5be9e2df0) with mixed basisOfRecord, HumanObservation and MaterialSample.

The problem is that we get the issue "institution match none" for the [records with MaterialSample](https://www.gbif.org/occurrence/search?dataset_key=b9461088-6f97-49b0-8f76-17e5be9e2df0&issue=INSTITUTION_MATCH_NONE), I guess is because it try to match it with GRSciColl, but this is not part of a collection, just indirect records (footprints, hair, marks, etc).
And it looks estrange that we get the issue just for 24 records when the whole dataset has the same institutionCode.

So, we should like to know if there is a way to avoid that interpretation, maybe just use the interpretation when collectionCode is docummented.

Thanks in advance and have a good day,

**Comment by muttcg** [comment]
deployed to prod
