### ISSUE TITLE
Use NE (Not evaluated) as a status for occurrences of unassessed species

### ISSUE THREAD

**Issue by MattBlissett** [gbif/pipelines#645]
> The IUCN filter should show apply a NE - Not Evaluated - category to those species that have not been assessed by IUCN.  This category is not applied systematically by IUCN and thus not available through their API, we will need to apply this category to all species with no IUCN assessment.

Further comment:

> I am interested to see how that would pan out with synonyms i.e. would synonyms of an accepted name be given NE even though the accepted name was assessed as LC?

I believe so, although @muttcg and @mdoering will know better.

_Originally posted by @andrewrodrigues in https://github.com/gbif/pipelines/issues/257#issuecomment-990675222_

**Comment by mdoering** [comment]
My immediate gut feeling is to keep synonyms the same as their accepted species. Otherwise we would recognise them as separate taxon concepts. But as we follow rather IUCN concepts than our own backbone ones I am not entirely sure.

**Comment by andrewrodrigues** [comment]
Apply NE to all animal, fungi and plant occurrences with a null value for threat category

**Comment by mdoering** [comment]
I would also exclude all OTU names, correct?

**Comment by andrewrodrigues** [comment]
Yes

**Comment by kcopas** [comment]
@MattBlissett we (@andrewrodrigues and I) were expecting that this would be part of what's on UAT for review. Is that not the case?

Also, can you confirm that the changes you're preparing will align with the updated filter names (w/IUCN capitalization and parenthetical abbreviations) on prod?
![Screenshot 2022-01-17 at 14 10 33](https://user-images.githubusercontent.com/12379236/149775128-c92f05ae-17dd-418c-86af-57f1bc78e8d2.png)

**Comment by MattBlissett** [comment]
Do you wish to see it on UAT before we run the update on prod? I hadn't planned to do that.

"Not Evaluated (NE)" will show below Data Deficient (DD), once some data with this status exists.

**Comment by kcopas** [comment]
Not necessary to see it on UAT if it's going to prod (in the same format as above—I see that the string's in Contentful, so it shouldn't surprise the GBIF.org). Just wanted to make sure that it's coming, as I call it out in the news item.

**Comment by andrewrodrigues** [comment]
Just had confirmation from IUCN that we should apply Not Evaluated (NE)  for anything in GBIF that does not appear on the Red List this includes species that have not been assessed, fossil species and micro-organisms

**Comment by mdoering** [comment]
so we should remove the restrictions to animal, plants & fungi and instead apply it all over, yes?

**Comment by mdoering** [comment]
well, I would still keep OTUs out and restrict it to Linnean names only

**Comment by mdoering** [comment]
I have changed to code to do the above

**Comment by andrewrodrigues** [comment]
IUCN Categories and Criteria can be applied to lower ranks than species but only if the species has been assessed first.  For that reason apply NE  only to species with Linnaean names.
