### ISSUE TITLE
Fail interpretation if GBIF ID collisions hit allowed threshold

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#649]
We silently drop index record when have GBIF ID collisions, better to highlight each dataset issue and have configurable threshold.

Add configurable allowed threshold for GBIF ID collision.

**Comment by timrobertson100** [comment]
One approach we might consider is to do a pre-check that identifies things like all records getting a new ID, or ID collisions, and then aborting the ingestion entirely and notifying data managers to intervene.

**Comment by muttcg** [comment]
By now I added simple validation right after interpretation:
```
if collisions > 5%(configurable)
   abort interpretation
```

And I plan to add Nagios alerts when we have failed interpretations

**Comment by timrobertson100** [comment]
It might also make sense to check that if >n% of records get new IDs, also abort?

(MachineTags in the registry would be the best place to manage per-dataset configuration for these kind of checks)

**Comment by muttcg** [comment]
deployed to prod
