### ISSUE TITLE
Create a new CLI command that listens to  DwcaDownloadFinishedMessage

### ISSUE THREAD

**Issue by fmendezh** [gbif/pipelines#65]
This task involves the creation of the Command, Service and Configuration classes required to enable a new CLI listener. It does NOT involve the processing of the DarwinCore file.
- [x] Create a new branch on https://github.com/gbif/crawler 
- [x] Create new Jenkins Job pointing the new branch
- [x] Understand basic concepts around RabbitMQ: virtual hosts, exchanges, routing keys, etc.
- [x]  Implement a command, service and configuration classes

This issues is part of epic #59

**Comment by timrobertson100** [comment]
This should listen to the validation finished not the download finished message

**Comment by aalbatross** [comment]
closes #65
