### ISSUE TITLE
Validator: Add tabular data format support

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#659]
We reuse production workflow for validation and because we don't use tabular formats as sources new validator doesn't support them by default, but looking at statistics many people use csv/tsv/xlsx for old one and it seems critical add support of those formats.

Technical aspect:
Add tabular-to-avro cli converter

**Comment by timrobertson100** [comment]
Might it be worth reviewing all aspects of https://tools.gbif.org/dwca-validator/ so it can be switched off?

**Comment by muttcg** [comment]
Deployed to PROD
