### ISSUE TITLE
Create a new CLI command that listens to CrawlFinishedMessage

### ISSUE THREAD

**Issue by fmendezh** [gbif/pipelines#66]
This tasks involves the creation of the skeleton classes to handle the message consumption. It ONLY requires the creation of Command, Service and Configuration classes.
- [x] Understand basic concepts around RabbitMQ: exchanges, virtual hosts, routing keys, publish-subscribe.
- [x] Implement the Commnad, Service and Configuration classes
- [x] Tests that the new command is able to consume messages from running crawl queues.
- [x] Decide if we can create configuration files in the gbif-configuration project for future use

This issues is part of epic #58.

**Comment by asturcon** [comment]
Configuration files can be created in the gbif-configuration project since they are not gonna be used in any script. Configuration files are usually passed as a parameter in the scripts that start the services.
