### ISSUE TITLE
Make DwC term otherCatalogNumbers searchable

### ISSUE THREAD

**Issue by FedorSteeman** [gbif/pipelines#664]
It's crucial that the DarwinCore term otherCatalogNumbers (http://rs.tdwg.org/dwc/terms/otherCatalogNumbers) is made searchable. 

Many institutions around the world are merging as are their cataloging systems. For many such mergers the adoption of a novel institution-wide catalog numbering system is not uncommon. 

Legacy catalogue numbers ("alternate catalog numbers") are typically mapped to this otherCatalogNumbers field and many researchers/curators and collection managers can attest to the "old" numbers being referrred to in a large body of older literature. 

Attempts at doing a free text search on an alternate catalog number has turned out to be problematic due to the stemming algorithm used by your systems. For instance search on old catalog number "ZMUC-R771281" on one of our datasets is fruitless, as you can see here: 
https://www.gbif.org/occurrence/search?q=ZMUC-R771281&dataset_key=8c834f97-c5df-4280-9623-86594979f91a

In one concrete case, we are currently trying to persuade our own Botany department to migrate their data to Specify so this data can be shared via GBIF. They're currently limited to sharing data via JSTOR. It will be easier to convince them if we can show them that their legacy catalog numbers will remain useful to search on in this new data integration via GBIF.

**Comment by MortenHofft** [comment]
**Multiple values**
The documentation says values should be separated by a pipe `|`. So I suppose it would make sense if we interpreted it as such (an array of values) for search?

**Response format**
But what about the response format then? Should it continue to be a single string or should it be an array of strings? Same question as in https://github.com/gbif/pipelines/issues/662#issuecomment-1034710906

**Comment by FedorSteeman** [comment]
**Multiple values**
Although we will try to only have a single alternate catalog number served via this field, I will make sure that any multiple values will be separated by pipes. 

**Response format**
For as far as we will share multiple values, which will be limited if occurring at all, having the response format being an array of values would make most sense.

**Comment by MortenHofft** [comment]
Regarding response format please see this comment https://github.com/gbif/pipelines/issues/662#issuecomment-1035044686

in short: to avoid a breaking change we should keep the response format a string. Even if it is searchable as individual values

**Comment by marcos-lg** [comment]
Deployed to PROD.
