### ISSUE TITLE
Store DwC-A as ExtendedRecord Avro using pipelines/core

### ISSUE THREAD

**Issue by fmendezh** [gbif/pipelines#67]
Once the message consumer receives a message that a  DwCA Validation  has finished event it must be converted into a ExtendendRecord/Avro in /data/ingest/<datasetUUID>/<attemptId>verbatim.avro. This will require that the crawler-cli project includes a dependency on the pipelines/core artifact for the Avro objects and the DwCA Reader.

This task is part of epic #59 "Propagate changes from DwC-A crawling to Avro files"

**Comment by aalbatross** [comment]
Pull request linked to the issue
https://github.com/gbif/crawler/pull/15
