### ISSUE TITLE
Pipelines release takes too long

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#671]
Current release takes around 4hr which is a lot and compare to regular build ~30min. 

A guess:
It might be some issue with artefacts IO, Jenkins re-download the same artefacts for different modules, maybe there is a way to avoid that

**Comment by MattBlissett** [comment]
I'm surprised by the behaviour of Nexus here.  I thought it was supposed to cache artifacts and metadata indefinitely, but I'm not sure it does (see last column):

```
192.38.28.2 - - [16/Feb/2022:11:16:30 +0000] "GET /content/groups/public/org/geotools/gt-api/15.0/gt-api-15.0.jar HTTP/1.1" 200 207868 2515258µs 
192.38.28.2 - - [16/Feb/2022:11:23:45 +0000] "GET /content/groups/public/org/geotools/gt-api/15.0/gt-api-15.0.jar HTTP/1.1" 200 207868 13239µs 
192.38.28.2 - - [16/Feb/2022:11:26:32 +0000] "GET /content/groups/public/org/geotools/gt-api/15.0/gt-api-15.0.jar HTTP/1.1" 200 207868 20506µs 
# Cache invalidated for osgeo repo in Nexus UI
192.38.28.2 - - [16/Feb/2022:11:31:35 +0000] "GET /content/groups/public/org/geotools/gt-api/15.0/gt-api-15.0.jar HTTP/1.1" 200 207868 539354µs 
```

That said, I don't think this would make much difference to re-downloading artifacts, just the first download on any particular day.

**Comment by muttcg** [comment]
I don't think that is a Nexus side, my guess is that wrong pipelines settings, maybe repositories settings, not sure, but it tries to download same artefacts from all repositories

```
[INFO] Downloading from gbif-central-mirror: http://repository.gbif.org/content/repositories/central/org/gbif/dwca-io/2.11/dwca-io-2.11-javadoc-resources.jar
[INFO] Downloading from gbif-all: https://repository.gbif.org/content/groups/gbif/org/gbif/dwca-io/2.11/dwca-io-2.11-javadoc-resources.jar
[INFO] Downloading from ALA: https://nexus.ala.org.au/content/repositories/releases/org/gbif/dwca-io/2.11/dwca-io-2.11-javadoc-resources.jar
[INFO] Downloading from ALA-snapshots: https://nexus.ala.org.au/content/repositories/snapshots/org/gbif/dwca-io/2.11/dwca-io-2.11-javadoc-resources.jar
[INFO] Downloading from gbif-public-mirror: http://repository.gbif.org/content/groups/public/org/gbif/dwca-io/2.11/dwca-io-2.11-javadoc-resources.jar
[INFO] Downloading from gbif-thirdparty: http://repository.gbif.org/content/repositories/thirdparty/org/gbif/dwca-io/2.11/dwca-io-2.11-javadoc-resources.jar
```

**Comment by MattBlissett** [comment]
I think we have something like this in the Jenkins configuration, but maybe it's not being picked up:

```
        <mirrors>
                <mirror>
                        <id>gbif-public-mirror</id>
                        <mirrorOf>*,!gbif-all,!gbif-mirror,!gbif-thirdparty</mirrorOf>
                        <name>GBIF mirror of public repositories</name>
                        <url>https://repository.gbif.org/content/groups/public/</url>
                </mirror>
        </mirrors>
```

(And maybe gbif-all, gbif-mirror, gbif-thirdparty don't need to be excluded, as they're part of the public group anyway, IIRC.)

**Comment by muttcg** [comment]
I added ALA and ALA-snapshots into mirrors and build time decreased by 1.5h, but still 4 calls per artifact, so it can be less:
```
[INFO] Downloading from gbif-central-mirror: http://repository.gbif.org/content/repositories/central/it/unimi/dsi/fastutil/8.2.2/fastutil-8.2.2-test-javadoc-resources.jar
[INFO] Downloading from gbif-all: https://repository.gbif.org/content/groups/gbif/it/unimi/dsi/fastutil/8.2.2/fastutil-8.2.2-test-javadoc-resources.jar
[INFO] Downloading from gbif-public-mirror: http://repository.gbif.org/content/groups/public/it/unimi/dsi/fastutil/8.2.2/fastutil-8.2.2-test-javadoc-resources.jar
[INFO] Downloading from gbif-thirdparty: http://repository.gbif.org/content/repositories/thirdparty/it/unimi/dsi/fastutil/8.2.2/fastutil-8.2.2-test-javadoc-resources.jar
```

**Comment by timrobertson100** [comment]
That specific example doesn't appear to be [in maven central](https://repo1.maven.org/maven2/it/unimi/dsi/fastutil/8.2.2/) so it's reasonable it'd try all repos for that.

Presumably, there are only a few artifacts that show those logs which could be expected or are there others?

**Comment by muttcg** [comment]
I think all https://builds.gbif.org/view/Pipelines/job/pipelines-master/261/consoleFull

**Comment by timrobertson100** [comment]
It looks to always be  `*-javadoc-resources.jar` and `*-test-javadoc-resource.jar` trying on each location for artifacts that don't exist.

It looks like it's behaving correctly I _think_, but perhaps we can disable it doing that to reduce those 900+ HTTP calls. I don't think that will bring much improvement in build time though.

**Comment by timrobertson100** [comment]
> It looks to always be *-javadoc-resources.jar and *-test-javadoc-resource.jar trying on each location for artifacts that don't exist.

I suspect this part is caused by the [motherpom](https://github.com/gbif/motherpom/blob/master/pom.xml#L221).

```
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-eclipse-plugin</artifactId>
          <version>${maven-eclipse-plugin.version}</version>
          <configuration>
            <downloadSources>true</downloadSources>
            <downloadJavadocs>true</downloadJavadocs>
          </configuration>
        </plugin>
```

I honestly don't know if we care to remove that or not.

**Comment by timrobertson100** [comment]
> It looks to always be *-javadoc-resources.jar and *-test-javadoc-resource.jar trying on each location for artifacts that don't exist.

We have this in the [motherpom](https://github.com/gbif/motherpom/blob/master/pom.xml#L608) which instructs the javadoc plugin to import javadocs only from `org.gbif` dependency projects.

```
        <configuration>
          <includeDependencySources>true</includeDependencySources>
          <dependencySourceIncludes>
            <!-- include ONLY dependencies I control -->
            <dependencySourceInclude>org.gbif:*</dependencySourceInclude>
          </dependencySourceIncludes>
```

Perhaps the pipeline pom overwrites that [here](https://github.com/gbif/pipelines/blob/dev/pom.xml#L212)?
