### ISSUE TITLE
Implement simple DwC-A to ES pipelines in Java

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#672]
To help iDigBio evaluate the pipelines codebase, we'll put together Java-only pipelines for the following 3 steps:

1. DwC-A to verbatim Avro file
2. Verbatim Avro to interpreted view, stored in Avro files
3. Interpreted Avro Files joined and posted to Elasticsearch

These will run on a single JVM without embedded Spark, using a local filesystem and without GBIF registry dependencies. 

Note that this will make calls across the internet to the GBIF API for the taxonomy and geospatial lookup so are not expected to run quickly. Those steps could be adapted with some local caching, or calling local services in a future enhancement.

**Comment by muttcg** [comment]
[Scripts ready for testing](https://github.com/gbif/pipelines/tree/dev/examples/dwca-to-elasticsearch)
