### ISSUE TITLE
Workflow to migrate occurrenceID, maintaining GBIF ID stability

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#673]
There are cases when publishers change their identifiers and codes. It is common for `collectionCodes` to change, while `occurrenceID` changes are often the result of a technical change (e.g. `http` to `https` or `acme.org/occurrence.php?id=123` to `api.acme.org/occurrence/123`) applied unwittingly or by adopting a new scheme such as the CETAF identifier format.

To allow publishers to maintain stability I propose an API and web form that allows the following workflow:

- A logged in user with email associated with the dataset can initiate an ID migration
- They upload a tab-delmited file for the dataset containing 2 columns (occurrenceID, gbifID)
- The file is verified to be readable (sanity check)
- The lookup rows for the dataset are archived (e.g. NFS txt file) and the table is flushed for the dataset, and rewritten with the new mapping
  - It is important to verify that the GBIF IDs provided are indeed associated with the dataset to avoid abuse   

An additional service could be provided to migratation of records between datasets (two or more)

- A logged in user with email associated with the datasets can initiate an ID migration
- They upload a tab-delmited file for the datasets containing 3 columns (datasetKey, occurrenceID, gbifID)
- The file is verified to be readable (sanity check)
- The lookup rows for the datasets are archived (e.g. NFS txt files) and the table is flushed for all dataset, and rewritten with the new mappings

**Comment by muttcg** [comment]
Current version implemented as a internal GBIF tool and already was used in PROD, further changes/improvements of that tool will appear as new issues
