### ISSUE TITLE
Use occurrenceID only for GBIF identifier matching when present

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#675]
GBIF currently use the _triplet_ and `occurrenceID` for detecting if a record has previously been seen before.

It will likely be simpler to understand and communicate, improve throughput, ease [diagnostics](https://github.com/gbif/pipelines/issues?q=is%3Aissue+diagnostic+id) and avoid edge cases (contradicting pairs) if we used only the `occurrenceID` when it is in use by a dataset as it becomes a simple `"yourID"->"gbifID"` mapping.

We still need to accommodate the 9208 datasets that don't use `occurrenceID`.

_triplet_ use does allow the ability to migrate IDs under some circumstances, but this has not proved to be fully robust. A simpler migration approach is proposed in #673

**Comment by muttcg** [comment]
In PROD
