### ISSUE TITLE
Improve process around detection of ID instability

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#676]
The current process aborts if >5% (configurable) records IDs are detected as unstable after interpretation, and nagios alerts the GBIF informatics team.

This could be improved by the following:

- [ ] Running the ID check as a pre-ingestion step in a way that does not pollute the lookup table
- [ ] Allow a `machine-tag` of e.g. `crawler.gbif.org:idThresholdPercent:100` be applied to a dataset to bypass the test (some datasets are known to always change ID)
- [ ] When the threshold is breached, notify helpdesk@gbif.org and the technical contact of the dataset by email
  - this email should provide links that allow them to disable this test permanently (sets the machine tag)
  - or disable the test for a one-time only (sets a `crawler.gbif.org:idThresholdOnce:true`, which is then deleted on the first run)
  - the email should link to documentation on how to migrate ids (see #673)

**Comment by mdoering** [comment]
Do we track IDs from older versions than the current one in case they get "resurrected"? Not sure if that happens often or even at all, but I could imagine records to drop out temporarily before they get included again and it would be good to have identifiers that stick.

**Comment by timrobertson100** [comment]
> Do we track IDs ... good to have identifiers that stick.

Yes, we do. The idea here is to detect it before they drop

**Comment by muttcg** [comment]
In PROD
