### ISSUE TITLE
Enable publishingCountry for iNat

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#678]
The [current implementation](https://github.com/gbif/pipelines/blob/dev/sdks/core/src/main/java/org/gbif/pipelines/core/interpreters/core/LocationInterpreter.java#L173-L188) only supports a declaration of publisher country by eBird.

iNaturalist have [added](https://github.com/inaturalist/inaturalist/commit/ebff0a4a0052f93d2b632aced0cbaeabd588f39f) this capability and the pipeline and website need to allow this

**Comment by timrobertson100** [comment]
@ahahn-gbif should we support this for all datasets or only iNat and eBird please?

**Comment by ahahn-gbif** [comment]
In principle I see no reason why we should not allow it in general. It might be helpful to have explicit communications around it (also because country reports may need an explanation on changes), but on the technical side, I cannot see an issue.

**Comment by muttcg** [comment]
@timrobertson100 

Does this look ok?
```
String verbatimPublishingCountryCode = extractNullAwareValue(er, GbifTerm.publishingCountry);
OccurrenceParseResult<Country> result = new OccurrenceParseResult<(COUNTRY_PARSER.parse(verbatimPublishingCountryCode));

if (result.isSuccessful()) {
  return Optional.of(result.getPayload().getIso2LetterCode());
} else {
  return Optional.ofNullable(mr.getDatasetPublishingCountry());
}
```

**Comment by MattBlissett** [comment]
I checked, and no-one other than eBird is currently using this field. (We expect iNaturalist's export on Wednesday to use it.)

**Comment by muttcg** [comment]
Deployed to PROD
