### ISSUE TITLE
Implement a skeleton pipeline for event based data

### ISSUE THREAD

**Issue by fmendezh** [gbif/pipelines#682]
This task aims to provide an skeleton pipeline that reads an DwC-A that contains data based on the [Darwin Core Event specification](https://rs.gbif.org/core/dwc_event_2022-02-02.xml) and produces a set of intermediate Avro files and a Elasticsearch index that allows to search and aggregate occurrence records in hierarchical list of events.

The expected artifact from this task is a library that can be executed in isolation of the GBIF and ALA ingestion platforms, and that that later on can be used as a starting point to further developments.

**Comment by djtfmartin** [comment]
Can this be closed ?
