### ISSUE TITLE
Re-interpretation of dataset after mapping to GRSciColl entry doesn't link occurrences to GRSciColl

### ISSUE THREAD

**Issue by ManonGros** [gbif/pipelines#695]
I just reinterpreted one of the datasets that I had mapped to a GRSciColl entry but the occurrences aren’t linked.

* Here is the GRSciColl entry: https://api.gbif.org/v1/grscicoll/collection/dbc640f7-0584-4a31-8e90-5eaea7cf0956
* The reinterpretation of the dataset: https://registry.gbif.org/dataset/b5cdf587-3342-48ec-9130-ba1281d7166f/ingestion-history
* What I would expect from the lookup tool: https://api.gbif.org/v1/grscicoll/lookup?institutionCode=MNHN&collectionCode=IK&datasetKey=b5cdf587-3342-48ec-9130-ba1281d7166f
* Example of what I get for occurrences: https://www.gbif.org/occurrence/3497363492

**Comment by marcos-lg** [comment]
Fixed. all the caches are refreshed now
