### ISSUE TITLE
Add acceptedKey to the new index for proper synonym linkeage

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/pipelines#7]
It should be possible to search and retrieve all occurrences for a taxon using any name, regardless if its a synonym.
Not least will this be very usefull when more occurrence data linked to OTU names is coming in. 

This has been discussed before [here](http://dev.gbif.org/issues/browse/POR-1984) and also [here](https://github.com/gbif/portal16/issues/622)

**Comment by MortenHofft** [comment]
It has been added to the index https://github.com/gbif/pipelines/issues/537
But remains to be added to the API as far as I can see
https://api.gbif.org/v1/occurrence/search?acceptedKey=1

**Comment by MortenHofft** [comment]
@muttcg isn't this closed prematurely? It still isn't in the API at least
