### ISSUE TITLE
Clustering: Improve NCBI (iBOL) record links

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#733]
https://www.gbif.org/occurrence/search?q=KJ139497 

These Arctos and NCBI records should link I think (see catalogNumber)

**Comment by timrobertson100** [comment]
The records are in the candidates table, but are dropped in final comparison as the NCBI record has no location or date information so the rules don't trigger. Given how sparse the NCBI data often is, we might consider a more relaxed rule that allows a link when 1. the accepted species and identifiers overlap and 2. the date/location doesn't contradict and 3. one side is NCBI/EMBL or an iBOL dataset.

What do you think @manongros 

An alternative might be to try and unpack associatedSequences and relatedResources which will be populated in some cases (in this record for example) but looking at the variation in those fields suggest it won't be all that easy.

**Comment by timrobertson100** [comment]
I've implemented this as described and created the Hive table, but not deployed this in Elasticsearch.

Currently [792k NCBI specimen-related records](https://www.gbif.org/occurrence/search?dataset_key=d8cd16ba-bb74-4420-821e-083f2bac17c2&advanced=1&is_in_cluster=true) link (with 4.6M edges in total).

After running this we see 1,155,931 records from NCBI connect (with 5.04M edges in total) including the examples here above.

`SELECT count(distinct id1) AS recs, count(*) AS links FROM prod_h.occurrence_relationships WHERE dataset1='d8cd16ba-bb74-4420-821e-083f2bac17c2'`.

**Comment by ManonGros** [comment]
Let me know when this is implemented in production, I will update the blogpost (https://data-blog.gbif.org/post/clustering-occurrences/)

**Comment by timrobertson100** [comment]
@ManonGros this is live now and implemented as described.

If a record comes from iBOL or EMBL, then we link anything with the same accepted scientific name and sharing an identifier (i.e. allow both date and location can be non_conflicting)

**Comment by ManonGros** [comment]
Thanks! I updated the blogpost

**Comment by abubelinha** [comment]
Related to [this clustering issue](https://github.com/gbif/pipelines/issues/781#issuecomment-1590896297) I was looking for info about how to **link sequences to specimens or the other way round** and I found this nice clustering example. 

I didn't know about that [INSDC Sequences dataset](https://www.gbif.org/dataset/d8cd16ba-bb74-4420-821e-083f2bac17c2).

As [INSDC](https://en.wikipedia.org/wiki/International_Nucleotide_Sequence_Database_Collaboration) is a collaboration of the 3 big Japan/USA/Europe sequence databases, should I understand the dataset contains (or will at some point contain) a darwincore-styled version of those nucleotide sequence databases ... including NCBI's Genbank? (that's the most used one in my institution context).

I don't see the words _NCBI_ or _Genbank_ in dataset description, so I wonder if this dataset is limited to just the European databases for now.
Do you know of any particular dwc field where I can check where the original sequence was published? (Japan, US or European dabase)
https://www.gbif.org/occurrence/3349660497

Years ago I tested [NCBI's LinkOut](https://www.ncbi.nlm.nih.gov/projects/linkout/) system trying to relate some Genbank published sequences back to our specimens.  
I'd like to explore possibilites of just doing the opposite thing inside gbif context.

Thanks
@abubelinha

**Comment by timrobertson100** [comment]
Thanks @abubelinha  - yes this should be pulling from the Europe mirror which - I understand - includes all the data submitted through the NCBI genbank too.

If you find we miss something, please do let us know.

**Comment by abubelinha** [comment]
Thanks for answering. 
I have very little knowledge of the internals of those genetic databases, but researchers do use them a lot to publish molecular analysis of preserved-specimens, so I try to link our specimens to their "related" sequences.

"related"? I can't believe the low quality requirements of NCBI on how voucher specimens (if any) are cited in their database.

Different researchers do it in different ways, many don't even cite `catalogNumber`, some other cite their personal field record ids, and so on. No way to solve those numbers on GBIF's end.  

Perhaps a little effort could be done trying to [extract institution/collection codes info (and map it to the dwc version) when GBIF pulls data from the source api](https://github.com/gbif/embl-adapter/issues/19).

**Comment by timrobertson100** [comment]
Thanks @abubelinha - that reflects my own experience too.

I know there are some discussions to improve guidelines/requirements for submission in the 3 Genbank mirrors. I'm not sure how far those have progressed.

Thanks for taking the time to write up those ideas in the other issue - I'll respond to that next week when I have time to digest it.
