### ISSUE TITLE
TaxonID is no more used in ALA Taxonomic Interpreter

### ISSUE THREAD

**Issue by sylmorin-gbif** [gbif/pipelines#748]
Before, in biocache-store, taxonID was used first to identify the taxon:

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/3bf0e8f5e3361ada5f20c8033edf50e8748eb41e/src/main/scala/au/org/ala/biocache/caches/ClassificationDAO.scala#L95

Now, in ALATaxonomyInterpreter, it's not even used:

https://github.com/gbif/pipelines/blob/dev/livingatlas/pipelines/src/main/java/au/org/ala/pipelines/interpreters/ALATaxonomyInterpreter.java#L141

Can I re-add it as the first check? or was it removed on purpose?

**Comment by djtfmartin** [comment]
thanks @sylmorin-gbif  - we should re-add.

**Comment by vjrj** [comment]
thanks @sylmorin-gbif

**Comment by sylmorin-gbif** [comment]
An option has been added:
```
alaNameMatchConfig:
  matchOnTaxonID: true
```

By default, the match on TaxonID is activated.
(DRs with wrong taxonIds shoud no be the most common)

**Comment by djtfmartin** [comment]
Merged in PR: https://github.com/gbif/pipelines/pull/749
