### ISSUE TITLE
Logs not being sent to kibana?

### ISSUE THREAD

**Issue by marcos-lg** [gbif/pipelines#766]
In the logs link that we have in the running ingestions UI (https://registry.gbif.org/monitoring/running-ingestions) where we filter by `datasetKey` and `attempt` we can only see logs from the `crawler-coordinator-cleanup` service but not from the rest of the services.

**Comment by muttcg** [comment]
Indices are exist, but prefix was changed to **coordinator**(to the name of package) and by default logstash uses class name as a prefix name, I updated kibana index pattern to **dev|uat|prod-coordinator-***
