### ISSUE TITLE
eventDate  dateIdentified is not being validated

### ISSUE THREAD

**Issue by camiplata** [gbif/pipelines#774]
Dear Team, the previus version of the validator was able to detect if the date was not using ISO 8601,  but the current version lost this function.  was this intentional or a bug?

We are uploading a dataset with the followin dates, with intentional issues as part of a data quality course for publishers

![fechas data validator](https://user-images.githubusercontent.com/5700527/186728785-059c3962-6133-4338-9b33-bdea76e3047f.png)

And we get this valitation:
http://www.gbif.org/tools/data-validator/d49e00c1-66a1-4f2f-83e2-3f2414dde836

**Comment by muttcg** [comment]
Thank you. It is a bug. Issues weren't correctly propagated during interpretation.

**Comment by muttcg** [comment]
Deployed to PROD
