### ISSUE TITLE
GADM filter for Ciudad Real in Spain (ESP.4.2_1) includes 114 occurrences in northern Spain

### ISSUE THREAD

**Issue by gbif-portal** [gbif/pipelines#783]
**GADM filter for Ciudad Real in Spain (ESP.4.2_1) includes 114 occurrences in northern Spain**

A GADM filter for "Ciudad Real" (central Spain) includes records from a disconnected area in northern Spain. From the content of those records (https://www.gbif.org/occurrence/search?advanced=1&geometry=POLYGON((-5.15479%2042.26221,-2.1665%2042.26221,-2.1665%2044.50342,-5.15479%2044.50342,-5.15479%2042.26221))&gadm_gid=ESP.4.2_1), it is not clear why they would be part of the gadm filter.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/62bf36af06eca15d674a3bba7f6dec27:22932a0d15756e6782c80f164a2076284909ce2e052fff7979969f9e8ac93a5765f328a5c4aee5fb176b877f906a7ab88cbe829bf34d2b8f7547024dfa85a4d4)
System: Firefox 90.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?advanced=1&geometry=POLYGON((-5.15479%2042.26221,-2.1665%2042.26221,-2.1665%2044.50342,-5.15479%2044.50342,-5.15479%2042.26221))&gadm_gid=ESP.4.2_1
Window size: width 1536 - height 684
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-04T08:28:27.438Z',to:'2021-08-04T08:34:27.438Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-04T08:28:27.438Z',to:'2021-08-04T08:34:27.438Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
@muttcg, this is because the bitmap cache image used by pipelines is out of date.

It should be updated to https://api.gbif.org/v1/geocode/bitmap, ideally retrieved by HTTP on startup/use.

I wonder if it could be also the cause of the bad interpretation of https://www.gbif.org/occurrence/3454729933

A fallback to https://github.com/gbif/geocode/blob/master/geocode-ws/src/main/resources/org/gbif/geocode/ws/resource/black.png would be best, if necessary for tests etc.

**Comment by MattBlissett** [comment]
https://github.com/gbif/portal-feedback/issues/4255 may also relate to this, although it's odd how the levels are mixed up there.

**Comment by MattBlissett** [comment]
I think this was fixed in b0b18a78a98209c4aca8b13cf7ce0d4720131f4b and we reinterpreted shortly after.
