### ISSUE TITLE
Create GH issue when GBIF identifier stage fails

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#788]
Pros:

- Easier to keep track of them and follow up
- Allow us to generate stats later on

Cons:

- As a part of a crawling/ingestion workflow Identifier stage can fail because of the technical issue (Issue with HDFS/network/Cluster pressure/etc)
- The process is automated and can create as many issues as datasets we have (by now 70k+) in worst case scenario
- The process fails every time when dataset is crawled, until identifiers were fixes, so we need more complex issue creation (create new, reopen, ignore, etc)
- By now pipelines use only GBIF api and don't use any 3rd party APIs
- Detection mechanism is primitive and can create many false positive issues

**Comment by timrobertson100** [comment]
FWIW, creating issues in a dedicated GH repo seems reasonable to me with a single issue per dataset, either created or reopened, with each new crawl adding a new comment and tidying up labels. A crawl that successfully completes could ensure the related dataset issue is closed. 

Using GH issue labels to indicate the count or percentage of records in bins (0-100,100-1000 or 0-5%, 5-10% etc) would make it easy to bulk close and review issues, and adding the country code of the publisher would help other data managers navigate, such as the distributed helpdesk team.

An alternative could be to develop something bespoke for this, but I'd think a GH solution would be a simple addition before going down that route.

**Comment by ManonGros** [comment]
Thanks @muttcg for explaining the challenges with this idea. Not sure what would be best here.
I suppose we could just continue with emails and I could log manually things on GitHub if I want to keep track of the datasets paused.

**Comment by muttcg** [comment]
@ManonGros I'd split this integration into several improvements to have less false positive issues and:
1) Improve identification wf
2) Improve email template
3) Create GH instead of/and emails

**Comment by ManonGros** [comment]
Sounds reasonable to me, thanks Nikolay
