### ISSUE TITLE
Restructure of the Pipelines project

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#790]
Initial thoughts and ideas about what can be improved within the project restructure

- Leave only core and main modules as part of the common project and move GBIF and ALA parts to "implementation" repositories
- Change build/release structure, projects like fragmenter/tool/ect don't need to be released every time when we change core/ingest/etc
- Move all IT tests to a module as implemented for GBIF registry and Occurrence
- Improve contribution guidelines

**Comment by djtfmartin** [comment]
thanks @muttcg 

Being simplistic, i see the modules in this repository falling into 2 categories:

1) Data pipelines
2) Tools for automating / running data pipelines (only used by GBIF)

So i suggest moving the following to separate repository:

* gbif/coordinator
* gbif/diagnostics
* gbif/keygen
* gbif/validator

I'd like use to keeping the following in a single repo:

* gbif/pipelines
* livingatlas
* sdks
* tools/pipelines-maven-repo

Separating ALA and GBIF pipelines will lead to divergence (and im hoping the current differences will diminish over time).
Im not sure about the rest of the tools/* modules. I suspect they don't change too frequently.

I favour keeping IT tests together with the relevant code, just because if they are separate, they risk being neglected/forgotten.

**Comment by timrobertson100** [comment]
> So i suggest moving the following to separate repository

We could of course leave these all in the same GH repo to keep things together, but isolate them from the same maven build (assuming the release tools handle this).

> I favour keeping IT tests together with the relevant code

I agree although designing for a fast build (1-minute target?) and a profile for a more rigorous build would be something I'd appreciate as an occasional contributor.

**Comment by djtfmartin** [comment]
@timrobertson100  - yes isolating the builds might be quicker solution

**Comment by muttcg** [comment]
Thanks @djtfmartin
I am exploring the options:
1) Use https://www.mojohaus.org/versions-maven-plugin for maven and tweak release system to release only module with changes
2) Use monorepo friendly build system such as Bazel instead of Maven
3) Use 3 repos Common, ALA, GBIF and GIT submodules

PS. I collect ideas and personally think about 1 or 2

**Comment by fmendezh** [comment]
@muttcg and I met today to discuss the scope of this issue, we identified some immediate work and changes that can bring some benefits.
Initially, we'll focus on fixing some know issues:

1.  Fix the circular dependency between pipelines and occurrence projects.
2.  Remove unnecessary modules and tools, specially the one inherited form the motherpom, this will requires some analysis.
3.  Evaluate the impact of having _isolated_ integrations tests modules, we initially identify at least three modules: core it tests, gbif it tests and ala it tests. The main intention of moving these tests from existing modules is to achieve better parallelism at build time by running unit tests in parallel. It will also help isolated the use of test containers and embedded servers in specific modules for further refactors and improvements.
4.  Enable ALA IT tests and migrate them to use managed containers, this will bring a more consistent use of containers in IT tests. We should also consider to use test containers only in cases when we need to test side-effect on external storages and systems, or when a mocking services implies a significant effort.
5. Restructuring this project into a monorepo, initially seems to bring little benefits, there are some modules like tools and examples that can be moved out of the Maven multi-module project to reduce complexity and save some build and release times.
6. We will explore strategies to release modules independently to speed-up the release time when only a few modules, or only one,  changed.

**Comment by djtfmartin** [comment]
thanks @fmendezh  - sounds good
