### ISSUE TITLE
dwca validator does not find EML

### ISSUE THREAD

**Issue by mdoering** [gbif/pipelines#791]
see https://github.com/gbif/portal-feedback/issues/4260 and also the validation report of the attached [archive](https://github.com/gbif/portal-feedback/files/9665290/wcvp_dwca.zip) where there is a regular `eml.xml` file linked via `metadata="eml.xml"`

https://www.gbif.org/tools/data-validator/dca59832-93c1-4468-8b9f-43bd3a11d267

**Comment by muttcg** [comment]
Fixed
