### ISSUE TITLE
Remove `examples` module

### ISSUE THREAD

**Issue by djtfmartin** [gbif/pipelines#795]
I believe we can safely remove the `examples` module which was setup at the start of the events work.
To my knowledge this is no longer in use.

**Comment by muttcg** [comment]
It is standart module. It contins examples of the code, configs and scripts (e.g for iDigBio). Iniatilay I added events as an extra module there, but when the code was moved to main module I deleted all events releated sources

**Comment by djtfmartin** [comment]
thanks for clarification @muttcg
