### ISSUE TITLE
Enable Maven release plugin for pipelines project

### ISSUE THREAD

**Issue by fmendezh** [gbif/pipelines#82]
The Jenkins Job https://builds.gbif.org/job/pipelines/ needs to have enable the Maven Release plugin, please use an existing project to copy all configuration settings (use https://builds.gbif.org/job/gbif-api/ as example/template)

This issue is part of the epic https://github.com/gbif/pipelines/issues/61

**Comment by aalbatross** [comment]
Done. Refer https://builds.gbif.org/job/pipelines/configure.
