### ISSUE TITLE
How to deal with intermediate ranks not used in backbone?

### ISSUE THREAD

**Issue by CecSve** [gbif/pipelines#850]
On helpdesk (January 2nd 2023), a correspondence was initiated on whether GBIF should be more strict with ranks and provide a much higher penalty for wrong rank "groups", i.e. suprafamily, family, genus, species & infraspecific names which will be continued in this issue.  

There is a similar problems with other higher taxa which are also often rare genera, e.g. Vertebrata. Its a simple change, but might have more impact than desired, e-g- if a very wrong rank was given. The coding change would be simple if we think it's worth trying.

@mdoering can you expand on how such a penalty would work?

**Comment by timrobertson100** [comment]
The problem lies [here](https://github.com/gbif/key-value-store/blob/dev/kvs-gbif/src/main/java/org/gbif/kvs/species/NameUsageMatchKVStoreFactory.java#L177) and [here](https://github.com/gbif/key-value-store/blob/dev/kvs-gbif/src/main/java/org/gbif/kvs/species/NameUsageMatchKVStoreFactory.java#L217) where the client is parsing the rank to null before executing the HTTP call.

@mdoering - should it be using an updated [RankParser](https://github.com/gbif/parsers/blob/dev/src/main/java/org/gbif/common/parsers/RankParser.java) or should it just be passing through the verbatim value, please?

**Comment by mdoering** [comment]
the verbatim value would not harm at all. Think thats the safest option, but updating the RankParser would also address the problem at hand.

**Comment by timrobertson100** [comment]
It's also used for normalizing the taxon rank, so I opted to add it to the vocabulary. Passing verbatim values may bring in some other regression (e.g. a value the parser is able to handle but the service not) so I err on the side of caution and take the conservative approach. With the `SUPERDOMAIN` in the rank, I think we should just need to bump the gbif-api versions in `key-value-store` and `pipelines`.

**Comment by mdoering** [comment]
The RankParser is used in the matching service, so unless something else is done to the verbatim data the service does it already

**Comment by timrobertson100** [comment]
Thanks. The parser is used to normalise the key for the cache, and for interpreting the field.

@mdoering - [this](https://github.com/gbif/key-value-store/pull/28) should mirror the change you applied behind the service. I see we just made it a synonym of domain.

**Comment by CecSve** [comment]
@timrobertson100 will you let me know once this should work?

**Comment by timrobertson100** [comment]
@CecSve Just for an update.

We're testing the fix [in dev](https://www.gbif-dev.org/occurrence/search?dataset_key=0eaac298-1fef-4102-9e3d-b80f3dc04f05&issue=TAXON_MATCH_NONE) before a release to production

**Comment by CecSve** [comment]
Is the test done?

**Comment by muttcg** [comment]
Yes, I will release the fixed version today. I plan to re-interpret all data today/tomorrow

**Comment by CecSve** [comment]
> I plan to re-interpret all data today/tomorrow

Great - thank you!

**Comment by muttcg** [comment]
Deployed to prod
