### ISSUE TITLE
Country Information ABCD Mapping

### ISSUE THREAD

**Issue by samleeflang** [gbif/pipelines#860]
Hi everyone,

Just noticed a small issue in how the country information is mapped from ABCD records.
It seems that the ISO value for Country in ABCD is mapped to `dwc:country` instead of `dwc:countryCode`
On the other hand the value for Country does not seem to be mapped at all.
This is an example: https://www.gbif.org/occurrence/874769969

```
Country or area | Croatia | HR | Altered
Country code    | HR      |    | Inferred
```
It shows an altercations and inference for country and countryCode while this information is correctly in the record.
```
		<Country>
			<Name>Croatia</Name>
			<ISO3166Code>HR</ISO3166Code>
		</Country>
```
Nothing serious and probably it gets inferred correctly but might be a small fix in the mapping.

Regards,
Sam

**Comment by muttcg** [comment]
Fixed
