### ISSUE TITLE
Frontend dreams that might influence technology choices

### ISSUE THREAD

**Issue by MortenHofft** [gbif/pipelines#9]
Ideas for what things that could be interesting to do in the future that might influence our choice of technology (SOLR vs ElasticSearch).

* Faster maps in better resolution
* Chloropleth maps based on various geo-partitions
* 3/4 dimensional bubblecharts (say x:avg latitude, y:month, value: count, slider:year) to see how 
* mean/avg of a field (e.g. latitude)
* negated query params (a recurring request)
* easy multi-dimensional aggregations (currently we have to do multiple calls) e.g. basisOfRecord and MONTH [[count]] for a given filter ([ES example](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations.html)).
* total facet count (not just the top n) - it is often useful to know how many distinct values (e.g. species for an occurrence search).
* estimated counts might be useful for faster charts and knowing wether to do something (e.g. we often ask for search results just to know if we should show some other component). knowning if there are results are often enough. the exact amount might not matter. This of course is only a performance thing.
* [aggregations by ranges](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-range-aggregation.html). say counts per decade ([ES histogram aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-histogram-aggregation.html))
* sort results
* sort facets on something else than counts (alphabetically by species name for speciesKey facet fx)

**Comment by dschigel** [comment]
Re "interesting to do" - are these possibilities we see internally or demands from the users? This might affect the decision :)

**Comment by MortenHofft** [comment]
Hi @dschigel, swing by my table and I can explain in more details what these experiments are about. It is really a tech thing, but if you are interested I'll gladly explain. Regarding above ideas and this repository in general, it isn't as much about exact interface options, but about enabling development in general.

**Comment by MortenHofft** [comment]
Create a taxon tree explorer for a given occurrence filter.
So for an occurrence filter do something aking to:
![screen shot 2018-01-09 at 15 38 11](https://user-images.githubusercontent.com/6759267/34726049-27925424-f553-11e7-90f2-7a51ff4313c6.png)

Above is made by first faceting on `kingdomKey`. Upon node expansion a new search is made with `kingdomKey=Fungi` and `facet=phylumKey`. Seemingly works fine.

But what happens when I click `Zygomycota`. `Zygomycota` have no classes, but only subphyla.
Even worse what happens to all of the families that are attached directly to `Fungi`. There is currently no way from the occurrence API to get to that data as far as I can see. A tree generated like this will not allow you to navigate to say https://www.gbif.org/species/2558273

What I want is probably something like: `taxonKey=Fungi` and `facet=immediateChildren` that will return me the list of distinct keys (with counts) that have a taxa that lists `Fungi` as their immediate parent. 

Not at all clear how this api would look like. But it seems relevant. Especially as taxonomy is moving away from Linnean ranks and also if we wish to support multiple taxonomies in the future.

**Comment by MortenHofft** [comment]
Incorporate DNA sequences into search. One could imagine many ways to do this. But some way of me arriving with a sequence (that I might not know what is) and get all occurrences in GBIF of that species.

Could also be: here is a sequence and here is my similarity threshold. Now give me all matches (and optional include occurrences of species that is matched to this sequence but hasn't been sequenced themselves). Is SOLR or Elastic a better choice for this. Or are they both inadequate and we need something complementary anyhow?

**Comment by dschigel** [comment]
This has been discussed several times and I understood that sequence search = molecular identification system is not a GBIF plan in the short term, to be confirmed with Donald. If stable OTUs with DOIs are successfully added to the backbone, external molecular identification pipelines and systems need to match a target sequence to a BIN or species hypothesis for a sequence-based occurrence or sample in question. Such a record will have an OTU name instead of Latin, an OTU name with a match in the backbone.

**Comment by MortenHofft** [comment]
Some way of keeping context during ingestion and having info flow back to the dataset. 
examples that could be interesting to infer from occurrence indexing: 

* temporal range
* list of all species
* country coverage
* km2 cell coverage

having this would allow users to 

* search datasets that deal with Annelida from 1972-1985 in Norway
* show a density map of dataset coverage.

**Comment by mdoering** [comment]
> Create a taxon tree explorer for a given occurrence filter.
> But what happens when I click `Zygomycota`. `Zygomycota` have no classes, but only subphyla.
> Even worse what happens to all of the families that are attached directly to `Fungi`. There is currently no way from the occurrence API to get to that data as far as I can see. 

@MortenHofft would it not help to include NULL values in the facet? At least if you had a fixed set of ranks to explore you could then show a virtual "incertae sedis" group that leads to these by querying for explicit nulls.

**Comment by dschigel** [comment]
Fungi has really messy situation. Anything between class and genus is a mess, so most mycologists just ignore these ranks, which is likely reflected in the checklist and the backbone. @thomasstjerne can tell you more.

**Comment by MortenHofft** [comment]
Perhaps. I haven't thought it through, but on the face of it I don't think it is ideal. Currently when expanding a node in the tree we filter on `taxonKey=96facet=class` or similar. But since there could be `NULL` many places in the tree I cannot do that for the missing node as far as I can see.
`taxonKey=NULL&facet=class` would give me data from many places in the tree. I guess we could then do `taxonKey=96&taxonKey=NULL&facet=class`. That would scope the tree to an area, but it doesn't feel elegant. But I guess it would do? 

But it would only work if I know what ranks to expect/show wouldn't it? I like the idea that it could work with other exotic taxonomies as well. Perhaps that could be worked around if I knew what ranks to show for each taxonomy.

In the - admittedly inelegant - backbone in the [current ES index](http://c6n1.gbif.org:9200/occurrence/_search) we can show arbitrary classifications I believe. But doing the actual implementation might prove differently.

```
"backbone": [
{
"taxonKey": 1,
"name": "Animalia",
"depthKey_0": 1,
"kingdomKey": 1,
"rank": "KINGDOM"
},
{
"taxonKey": 54,
"name": "Arthropoda",
"depthKey_1": 54,
"kingdomKey": 54,
"rank": "PHYLUM"
},
{
"taxonKey": 216,
"name": "Insecta",
"depthKey_2": 216,
"kingdomKey": 216,
"rank": "CLASS"
},
{
"taxonKey": 797,
"name": "Lepidoptera",
"depthKey_3": 797,
"kingdomKey": 797,
"rank": "ORDER"
},
{
"taxonKey": 6950,
"name": "Geometridae",
"depthKey_4": 6950,
"kingdomKey": 6950,
"rank": "FAMILY"
},
{
"taxonKey": 1978749,
"name": "Campaea",
"depthKey_5": 1978749,
"kingdomKey": 1978749,
"rank": "GENUS"
},
{
"taxonKey": 1978776,
"name": "Campaea margaritaria",
"depthKey_6": 1978776,
"kingdomKey": 1978776,
"rank": "SPECIES"
}
],
```
