### ISSUE TITLE
Extend pipeline commands to broadcast a message when crawl has finished

### ISSUE THREAD

**Issue by fmendezh** [gbif/pipelines#91]
[DwCAToAvroCommand.java](https://github.com/gbif/crawler/blob/master/crawler-cli/src/main/java/org/gbif/crawler/pipelines/service/dwca/DwCAToAvroCommand.java) and [XmlToAvroCommand.java](https://github.com/gbif/crawler/blob/master/crawler-cli/src/main/java/org/gbif/crawler/pipelines/service/dwca/DwCAToAvroCommand.java]) must be extended to broadcast a message notifying that the crawl has finished, the resulting message must include: the dataset key being crawled and hdfs location of new dataset data. 
A new RabbitMQ exchange must used in order to be used as the target for the new message type.

**Comment by fmendezh** [comment]
(DwCAToAvroCommand.java)[https://github.com/gbif/crawler/blob/master/crawler-cli/src/main/java/org/gbif/crawler/pipelines/service/dwca/DwCAToAvroCommand.java] and (XmlToAvroCommand.java)[https://github.com/gbif/crawler/blob/master/crawler-cli/src/main/java/org/gbif/crawler/pipelines/service/dwca/DwCAToAvroCommand.java]

**Comment by aalbatross** [comment]
closes #91
