### ISSUE TITLE
Support CamtrapDP v1.0

### ISSUE THREAD

**Issue by fmendezh** [gbif/pipelines#916]
Pipelines currently supports a draft version of the CamtrapDP specification, once this version is released and fully supported by the IPT, the pipelines  data ingestion components must adapted to work against that specification.
@peterdesmet and @mike-podolskiy90 can provide further details about the specification. 
The intention is to continue using the R libraries  provided by https://github.com/inbo/camtraptor 
The library was dockerized here
https://github.com/gbif/camtrap-dp-pipeline/blob/master/docker/R/convert-dp-dwca.R

**Comment by peterdesmet** [comment]
Also tagging @pietrH and @damianooldoni (developers of the camtraptor package).
