### ISSUE TITLE
ingestion management - create tag with publisher key and/or ipt installation of dataset

### ISSUE THREAD

**Issue by jhnwllr** [gbif/pipelines#937]
@marcos-lg 

When ids change datasets are often updated in bulk, so that an entire ipt installation has new ids. It would be helpful if the publisher key and/or the ipt installation appeared as a tag in the issue. The same way that uuid of the dataset now appears in the issue.

**Comment by marcos-lg** [comment]
@jhnwllr I'm thinking that if I add the tag with just the key it could be confusing with the labels of the dataset keys? Alternatively the tags could be `publisher: f99f2c09-1353-4f24-aab2-f4cbaef67eb1` or just the name of the publisher. The same for the installations.

What do you prefer?

**Comment by marcos-lg** [comment]
For the installations I'll put `inst: f99f2c09-1353-4f24-aab2-f4cbaef67eb1` since it's more generic.

**Comment by marcos-lg** [comment]
Deployed to production.
