### ISSUE TITLE
Reprocessing old event datasets causes registry state update issues 

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#938]
Reprocessing an event dataset that was unchanged for 2 years hung in the "running ingestions".
On forcing it to finish in the ingestion history and retrying, the result appeared in the history as this screenshot.
 
[Page 8 (attempt 24)](https://registry.gbif.org/dataset/c1e31227-6595-4797-b75a-d9d9f75e4cca/ingestion-history)
![image](https://github.com/gbif/pipelines/assets/237221/8d9e240c-d7fd-4bb2-a03c-1b11d2b28ee9)

The suspicion is this was processed before the Event pipelines were deployed and there is some kind of mismatch in the messages being sent around.

We could fixup the code, or perhaps it is simpler to touch all the DwC-A to an earlier date and force crawl all the old event datasets to avoid this situation?

**Comment by muttcg** [comment]
Fixed history data for all related datasets
Page 8, attempt 24
https://registry.gbif.org/dataset/c1e31227-6595-4797-b75a-d9d9f75e4cca/ingestion-history

**Comment by timrobertson100** [comment]
Thanks @muttcg
