### ISSUE TITLE
GRSciColl - only link occurrence specimens to GRSciColl

### ISSUE THREAD

**Issue by ManonGros** [gbif/pipelines#939]
Until now, I have been of the opinion that if an institution wants to show case their observation records, they should be able to. So it made sense to link any occurrence with an institution code or identifier to GRSciColl.

With the new website, this decision make a few things confusing like the specimens in GBIF "counts" which are observations. Also increases the risk of incorrect linking (since observations might be using codes that happen to be in GRSciColl without any relationship to the entry).
See:
https://github.com/gbif/portal-feedback/issues/4497

I think it is time to change the behaviour.
@marcos-lg

**Comment by marcos-lg** [comment]
Deployed to production and all datasets have been reinterpreted.
