### ISSUE TITLE
Linking occurrences to GRSciColl institution

### ISSUE THREAD

**Issue by ManonGros** [gbif/pipelines#940]
I am trying to link this occurrence https://www.gbif.org/occurrence/3314093373 to http://api.gbif.org/v1/grscicoll/institution/3448c872-18f9-4d70-8237-148cd1d87b3f
I previously made a default value for that dataset to link the occurrences to a different entry but I have since then be told the correct one is the one above.
I have removed the default value and regingested the dataset.

The data is reinterpreted with the default value I have removed.

**Comment by timrobertson100** [comment]
Please can you try again @ManonGros ?

I have truncated the GRSciColl lookup cache

**Comment by ManonGros** [comment]
The occurrences are still linked to the previous GRSciColl entry. @marcos-lg said to wait until the GRSciColl cache is updated next week and try again.

**Comment by marcos-lg** [comment]
I just found out that the wrong institution is manually linked to that dataset: https://api.gbif.org/v1/grscicoll/institution/54915ead-6124-4878-ad04-d14b9876832a/occurrenceMapping

That mapping should be removed.

**Comment by ManonGros** [comment]
Thanks Marcos! I thought I checked but clearly I didn't look in the right place. I have removed them. I will wait for the cache to update an reinterpret the data. Sorry for the bother.

**Comment by marcos-lg** [comment]
Since we just reinterpreted all the datasets this got fixed too.
