### ISSUE TITLE
Generic name set for higher ranks

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#945]
Following the species match step, we are incorrectly setting a `genericName` on records that have been matched to ranks higher than a genus. An [example record](https://www.gbif.org/occurrence/4011499125) has:

```
"taxonKey": 7881,
"kingdomKey": 1,
"phylumKey": 54,
"classKey": 216,
"orderKey": 809,
"familyKey": 7881,
"acceptedTaxonKey": 7881,
"scientificName": "Gerridae",
"acceptedScientificName": "Gerridae",
"kingdom": "Animalia",
"phylum": "Arthropoda",
"order": "Hemiptera",
"family": "Gerridae",
"genericName": "Gerridae",
"taxonRank": "FAMILY",
"taxonomicStatus": "ACCEPTED",
```

`genericName` should be null here

**Comment by timrobertson100** [comment]
I suspect this might be happening [here](https://github.com/gbif/pipelines/blob/dev/sdks/core/src/main/java/org/gbif/pipelines/core/converters/OccurrenceHdfsRecordConverter.java#L366), where I think we need rank checks before setting these 3 predicates.

This is called `OccurrenceHdfsRecordConverter` does that also affect the JSON posted to ES please @fmendezh ?

**Comment by fmendezh** [comment]
@timrobertson100 It looks that those are the two only places where we change the generic name,  maybe better if we change the function _convertGenericName_ in the JsonConverter class

**Comment by timrobertson100** [comment]
Fixed in dev
