### ISSUE TITLE
Killed / failed ingestions that are removed cannot be reprocessed

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#949]
When a dataset processing fails or is deliberately killed (e.g. kill a yarn job) it appears "stuck" in the running ingestion monitor.
You can "Finish" it using the UI but afterward cannot then run a specific step to reprocess it - I suspect it's related to something like being in a state in the registry that blocks new runs.

**Comment by muttcg** [comment]
Fixed in #935
