### ISSUE TITLE
VERBATIM_TO_IDENTIFIER runs small datasets on Spark

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#953]
The `VERBATIM_TO_IDENTIFIER` stage is running everything on Spark (Yarn), even for tiny datasets such as [this one](https://www.gbif.org/dataset/fe4d614a-8796-4c12-93c7-ae6ad4f2741d).

We should either fix the config to be something reasonable (e.g. 1M records or >1GB uncompressed size or so) or rework this stage so that it doesn't require distributed computing.

**Comment by muttcg** [comment]
There is only one implementation of that workflow - yarn

**Comment by muttcg** [comment]
Deployed to PROD
