### ISSUE TITLE
GRSciColl - link occurrences with basis of record "material sample"

### ISSUE THREAD

**Issue by ManonGros** [gbif/pipelines#964]
I think the occurrences with the material sample basis of records can be considered specimens (https://discourse.gbif.org/t/we-changed-the-way-we-link-occurrences-to-grscicoll/4147).
Especially if the samples are stored (essentially physical collections). Plus, it would be valuable to have DNA-based records linked to GRSciColl entries.

Could we link the occurrences with the basis of records: Preserved Specimen, Fossil Specimen, Living Specimen, **Material Sample** to GRSciColl?

Thanks!

**Comment by ManonGros** [comment]
One of our contractors pointed out that [MaterialCitation](https://dwc.tdwg.org/terms/#materialcitation) relates to specimens. They quote: "a citation of a physical specimen from a scientific collection in a taxonomic treatment in a scientific publication".

Could we link those as well?

**Comment by muttcg** [comment]
Deployed to PROD
