### ISSUE TITLE
Diagnostic: Missing names on record 

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#973]
[This record](https://www.gbif.org/occurrence/3447673047) shows as _incertae sedis_ but [the lookup](https://api.gbif.org/v1/species/match?verbose=true&name=Lissotarsus%20reticulata%20Chaudoir,%201842) should find the species.   

I'll investigate, cc @mdoering

**Comment by timrobertson100** [comment]
The lookup cache contains no values:

```
hbase(main):001:0> scan 'name_usage_kv', { FILTER => "RowFilter(=, 'substring:Lissotarsus reticulatus')" }
ROW                                                       COLUMN+CELL                                                                                                                                                             
0 row(s) in 42.7360 seconds
```

**Comment by timrobertson100** [comment]
As it happens, this is a narrowly scoped dataset (titled "Coleoptera...") so we could add a default of kingdom = Animalia in the registry which would at least improve this dataset.

**Comment by mdoering** [comment]
Ah, that makes sense. It would be great to understand why that has happened from a user perspective, but yes we should keep it. And for sure add a default classification to the dataset. Can we only add the kingdom or also other ranks like Arthropoda & Coleoptera?

**Comment by timrobertson100** [comment]
We could add more, but I'll start conservatively

**Comment by timrobertson100** [comment]
Animalia was enough for this example. but there were records being interpreted as Fungi as well, so I added Animalia / Arthropoda / Insecta and that has put this [into a better shape](https://www.gbif.org/occurrence/taxonomy?dataset_key=3d29ff16-884f-40f3-b98e-f54f715b55d9).
