### ISSUE TITLE
Add new fields to the index and api

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#993]
@MortenHofft Please specify the new fields you want to have in the API.

**Comment by MortenHofft** [comment]
I colated the ones i could find here: https://github.com/gbif/pipelines/issues/666 
but I believe those from https://github.com/gbif/pipelines/issues/400 might need some more work before adding them. @ahahn-gbif ?

**Comment by ahahn-gbif** [comment]
Concerning stratigraphy terms: I would recommend to wait until we have the upload of the vocabulary, currently in the works with the paleodata working group. Checking for an update via #400.

**Comment by muttcg** [comment]
New fields added to index and the API:

earliestEonOrLowestEonothem
latestEonOrHighestEonothem
earliestEraOrLowestErathem
latestEraOrHighestErathem
earliestPeriodOrLowestSystem
latestPeriodOrHighestSystem
earliestEpochOrLowestSeries
latestEpochOrHighestSeries
earliestAgeOrLowestStage
latestAgeOrHighestStage
lowestBiostratigraphicZone
highestBiostratigraphicZone
group (reserved word _group)
formation
member
bed
gbifRegion
publishedByGbifRegion
fieldNumber
preparations
sex
startDayOfYear
endDayOfYear
higherGeography
island
islandGroup
georeferencedBy
previousIdentifications
datasetName
datasetID
otherCatalogNumbers
taxonConceptID
isSequenced
associatedSequences
